#!/bin/sh

# Author : Arturo Huerta
# Copyright (c) Emerson.com
# Script follows here:

export EMAIL_TO_ALL=arturo.huerta@emerson.com
#export EMAIL_TO_ALL=arturo.huerta@emerson.com,tom.ayars@Emerson.com,Don.Shilonie@Emerson.com,Mark.Eyman@Emerson.com,JerryW.Wang@Emerson.com,fli@emerson.com,Abhitab.Khutale@emerson.com,Jane.Yang@Emerson.com
export BUILD_DROP=/media/samba_share/BuildArchive/GSX-P1-Base/Staging/DailyBuilds/QT
#export BUILD_DROP=/root/Scripts
export SOFTWARE_CHANGE_CONFIG=SoftwareChange.json
export BUILD_NAME=GSX21
export WORKSPACE=/root/GSX-P1-Stream-Build
export BUILD_SCRIPTS=/root/Scripts
export MY_PASS=123456Aa#
export USERNAME=builder5
export WORK_ITEM=5402
export SERVER=https://jazz.bucclm.com/ccm

export FORCE_BUILD=0

clear

cd $BUILD_SCRIPTS

rm P1*.txt

export SOFTWARE_CHANGE_FILE=P1_Result.txt

export SOFTWARE_CHANGE_UICONTROLLER_FILE=P1_P1_UIController.txt
export SOFTWARE_CHANGE_UICONTROLLER_FILE_UUID=P1_P1_UIController_UUID.txt

export SOFTWARE_CHANGE_BASELINE_FILE=P1_Baseline.txt

export SOFTWARE_CHANGE_STREAM_FILE=P1_Stream.txt

export SOFTWARE_CHANGE_WORKSPACE_FILE=P1_Workspace.txt
export SOFTWARE_CHANGE_WORKSPACE_FILE_UUID=P1_Workspace_UUID.txt

export SOFTWARE_CHANGE_SERVER_FILE=P1_Server.txt

export SOFTWARE_CHANGE_MACHINE_DETAILS_FILE=P1_version.h.txt

java -jar SoftwareChange.jar $SOFTWARE_CHANGE_CONFIG

export SOFTWARE_CHANGE_VALUE=$(head -1 $SOFTWARE_CHANGE_FILE)
export SOFTWARE_CHANGE_FLAG=$(($SOFTWARE_CHANGE_VALUE + 0))
echo "SOFTWARE_CHANGE_FLAG: $SOFTWARE_CHANGE_FLAG"

export SOFTWARE_CHANGE_UICONTROLLER_VALUE=$(head -1 $SOFTWARE_CHANGE_UICONTROLLER_FILE)
export SOFTWARE_CHANGE_UICONTROLLER_FLAG=$(($SOFTWARE_CHANGE_UICONTROLLER_VALUE + 0))
echo "SOFTWARE_CHANGE_UICONTROLLER_FLAG: $SOFTWARE_CHANGE_UICONTROLLER_FLAG"
export SOFTWARE_CHANGE_UICONTROLLER_UUID=$(head -1 $SOFTWARE_CHANGE_UICONTROLLER_FILE_UUID)
echo "SOFTWARE_CHANGE_UICONTROLLER_UUID: $SOFTWARE_CHANGE_UICONTROLLER_UUID"

export SOFTWARE_CHANGE_MACHINE_DETAILS_VALUE=$(head -1 $SOFTWARE_CHANGE_MACHINE_DETAILS_FILE)
export SOFTWARE_CHANGE_MACHINE_DETAILS_FLAG=$(($SOFTWARE_CHANGE_MACHINE_DETAILS_VALUE + 0))
echo "SOFTWARE_CHANGE_MACHINE_DETAILS_FLAG: $SOFTWARE_CHANGE_MACHINE_DETAILS_FLAG"

export SOFTWARE_CHANGE_BASELINE_VALUE=$(head -1 $SOFTWARE_CHANGE_BASELINE_FILE)
echo "SOFTWARE_CHANGE_BASELINES_VALUE: $SOFTWARE_CHANGE_BASELINE_VALUE"

export SOFTWARE_CHANGE_STREAM_VALUE=$(head -1 $SOFTWARE_CHANGE_STREAM_FILE)
echo "SOFTWARE_CHANGE_STREAM_VALUE: $SOFTWARE_CHANGE_STREAM_VALUE"

export SOFTWARE_CHANGE_SERVER_VALUE=$(head -1 $SOFTWARE_CHANGE_SERVER_FILE)
echo "SOFTWARE_CHANGE_SERVER_VALUE: $SOFTWARE_CHANGE_SERVER_VALUE"

export SOFTWARE_CHANGE_WORKSPACE_UUID=$(head -1 $SOFTWARE_CHANGE_WORKSPACE_FILE_UUID)
echo "SOFTWARE_CHANGE_WORKSPACE_UUID: $SOFTWARE_CHANGE_WORKSPACE_UUID"

if [ $FORCE_BUILD -eq 0 ]; then
	if [ $SOFTWARE_CHANGE_FLAG -eq 0 ]; then
	  	echo "SOFTWARE NOT CHANGE"	
		java -jar EmailServer.jar EmailSetup.json "GSX P1 UIController Daily Build" "No Builds :("
	fi

	if [ $SOFTWARE_CHANGE_FLAG -eq 1 ]; then
		echo "SOFTWARE CHANGE"  
		./build_common_general.sh
	fi
fi

if [ $FORCE_BUILD -eq 1 ]; then
	echo "FORCE BUILD"  
	./build_common_general.sh
fi

