#!/bin/bash

# Author : Arturo Huerta
# Copyright (c) emerson.com
# Script follows here:

echo "Start Build..."

export QT_COMPONENT=P1_UIController
export SOFTWARE_CHANGE_UICONTROLLER=$WORKSPACE/P1_UIController/c++Source
export SOFTWARE_CHANGE_UICONTROLLER_HEADER=$WORKSPACE/P1_UIController/c++Source
export SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE=version.h
export SOFTWARE_CHANGE_MACHINE_DETAILS_FILE=P1_version.h.txt

export BuildDate="Build_"$(date +"%m-%d-%Y-%H-%M")
export UIC_VERSION_NUM_MAJOR=0
export UIC_VERSION_NUM_MINOR=0
export UIC_VERSION_NUM_BUILD=0
export UIC_VERSION_NUM_AUTO_OLD=0
export UIC_VERSION_NUM_AUTO_NEW=0
export BUILD_ERROR_FLAG=0
export RELEASE_VERSION_SNAPHOT=""
export HISTORY_DETAILED_OUTPUT=$BUILD_SCRIPTS/History_Detailed.txt
export HISTORY_VERSION_OUTPUT=$BUILD_SCRIPTS/Version.txt
export HISTORY_LOG_OUTPUT=$BUILD_SCRIPTS/Log.txt

rm $HISTORY_LOG_OUTPUT
rm $HISTORY_VERSION_OUTPUT

# DO VERSION CHANGE
grep UIC_VERSION_NUM_MAJOR $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE | gawk '{print $3}' > $BUILD_SCRIPTS/delme.txt
UIC_VERSION_NUM_MAJOR=$(head -1 $BUILD_SCRIPTS/delme.txt)
grep UIC_VERSION_NUM_MINOR $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE | gawk '{print $3}' > $BUILD_SCRIPTS/delme.txt
UIC_VERSION_NUM_MINOR=$(head -1 $BUILD_SCRIPTS/delme.txt)
grep UIC_VERSION_NUM_BUILD $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE | gawk '{print $3}' > $BUILD_SCRIPTS/delme.txt
UIC_VERSION_NUM_BUILD=$(head -1 $BUILD_SCRIPTS/delme.txt)
grep UIC_VERSION_NUM_AUTOS $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE | gawk '{print $3}' > $BUILD_SCRIPTS/delme.txt
UIC_VERSION_NUM_AUTOS_OLD=$(head -1 $BUILD_SCRIPTS/delme.txt)
UIC_VERSION_NUM_AUTOS_NEW=$((UIC_VERSION_NUM_AUTOS_OLD))
	
# SHOW VERSION INFO
echo "UIC_VERSION_NUM_MAJOR     $UIC_VERSION_NUM_MAJOR" >> $HISTORY_LOG_OUTPUT
echo "UIC_VERSION_NUM_MINOR     $UIC_VERSION_NUM_MINOR" >> $HISTORY_LOG_OUTPUT
echo "UIC_VERSION_NUM_BUILD     $UIC_VERSION_NUM_BUILD" >> $HISTORY_LOG_OUTPUT
echo "UIC_VERSION_NUM_AUTOS_OLD $UIC_VERSION_NUM_AUTOS_OLD" >> $HISTORY_LOG_OUTPUT
	
if [ $FORCE_BUILD -eq 0 ]; then
	# EXIT NO UICONTROLLER CHANGES
	if [ $SOFTWARE_CHANGE_UICONTROLLER_FLAG -eq 0 ]; then
		echo "NO UICONTROLLER CHANGES"
		java -jar EmailServer.jar EmailSetup.json "GSX P1 UIController Daily Build" "No UICONTROLLER changes :("
		exit 1
	fi

	# RELOAD ALL THE COMPONENETS
	cd $WORKSPACE
	scm login -r $SERVER -u $USERNAME -P $MY_PASS -n Jazz >> $HISTORY_LOG_OUTPUT
	scm load --force $SOFTWARE_CHANGE_WORKSPACE_UUID $SOFTWARE_CHANGE_UICONTROLLER_UUID --repository-uri Jazz >> $HISTORY_LOG_OUTPUT
	scm logout --repository-uri Jazz >> $HISTORY_LOG_OUTPUT

	if [ $SOFTWARE_CHANGE_UICONTROLLER_FLAG -eq 1 ]; then
		echo "Raspberry Pi Build..."

		# DO VERSION CHANGE
	        UIC_VERSION_NUM_AUTOS_NEW=$(($UIC_VERSION_NUM_AUTOS_OLD+1))

		# SHOW VERSION INFO
		echo "UIC_VERSION_NUM_AUTOS_NEW $UIC_VERSION_NUM_AUTOS_NEW" >> $HISTORY_LOG_OUTPUT

	        # UPDATE VERSION FILE
		sed -i "s/UIC_VERSION_NUM_AUTOS $UIC_VERSION_NUM_AUTOS_OLD/UIC_VERSION_NUM_AUTOS $UIC_VERSION_NUM_AUTOS_NEW/g" $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE
		mv $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE.bak
		mv $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE.bak $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE
		sleep 1

		# VALIDATE THE FILE WAS CHANGE IN THE WORKSPACE
	        java -jar $BUILD_SCRIPTS/SoftwareChange.jar $BUILD_SCRIPTS/$SOFTWARE_CHANGE_CONFIG

		SOFTWARE_CHANGE_MACHINE_DETAILS_VALUE=$(head -1 $SOFTWARE_CHANGE_MACHINE_DETAILS_FILE)
		SOFTWARE_CHANGE_MACHINE_DETAILS_FLAG=$(($SOFTWARE_CHANGE_MACHINE_DETAILS_VALUE + 0))
		echo "SOFTWARE_CHANGE_MACHINE_DETAILS_FLAG: $SOFTWARE_CHANGE_MACHINE_DETAILS_FLAG"

		if [ $SOFTWARE_CHANGE_MACHINE_DETAILS_FLAG -eq 0 ]; then
			echo "VERSION FILE WAS NOT CHANGE"
			java -jar $BUILD_SCRIPTS/EmailServer.jar $BUILD_SCRIPTS/EmailSetup.json "GSX P1 UIController Daily Build" "Version was not change :/"
			exit 1
		fi

		# ACCEPTING, DELIVER, SNAPSHOT & DIFF
	        scm login -r $SERVER -u $USERNAME -P $MY_PASS -n Jazz >> $HISTORY_LOG_OUTPUT

		sleep 1
	        scm show status  
	        scm accept --no-merge --overwrite-uncommitted >> $HISTORY_LOG_OUTPUT
	
		sleep 1        
		scm show status
	        scm checkin --workitem $WORK_ITEM $SOFTWARE_CHANGE_UICONTROLLER_HEADER/$SOFTWARE_CHANGE_UICONTROLLER_VERSION_FILE --comment "Auto Build" >> $HISTORY_LOG_OUTPUT

		sleep 1        
		scm show status
	        scm resolve conflict --checkedin $SOFTWARE_CHANGE_QT_RPI_UICONTROLLER_UUID >> $HISTORY_LOG_OUTPUT
	
		sleep 1
		scm show status        
		scm deliver --components $SOFTWARE_CHANGE_UICONTROLLER_UUID >> $HISTORY_LOG_OUTPUT
		scm deliver --components $SOFTWARE_CHANGE_UICONTROLLER_UUID >> $HISTORY_LOG_OUTPUT
		scm deliver --components $SOFTWARE_CHANGE_UICONTROLLER_UUID >> $HISTORY_LOG_OUTPUT	
	
		RELEASE_VERSION_SNAPHOT="Build_UI_$UIC_VERSION_NUM_MAJOR.$UIC_VERSION_NUM_MINOR.$UIC_VERSION_NUM_BUILD.$UIC_VERSION_NUM_AUTOS_NEW"
	        echo "RELEASE_VERSION_SNAPHOT $RELEASE_VERSION_SNAPHOT"
	        #echo "Version: UI $UIC_VERSION_NUM_MAJOR.$UIC_VERSION_NUM_MINOR.$UIC_VERSION_NUM_BUILD.$UIC_VERSION_NUM_AUTOS_NEW" >> $HISTORY_VERSION_OUTPUT

		sleep 1	
		scm show status
		scm create snapshot --description "$RELEASE_VERSION_SNAPHOT" --forceBaselineCreation --name $RELEASE_VERSION_SNAPHOT --repository-uri $SERVER -- $SOFTWARE_CHANGE_WORKSPACE_UUID >> $HISTORY_LOG_OUTPUT || BUILD_ERROR_FLAG=$((BUILD_ERROR_FLAG+1))

	        sleep 1	
		scm show status
		scm accept --no-merge --overwrite-uncommitted >> $HISTORY_LOG_OUTPUT

		sleep 1	
		scm show status        
		scm deliver --components $SOFTWARE_CHANGE_UICONTROLLER_UUID >> $HISTORY_LOG_OUTPUT
		scm deliver --components $SOFTWARE_CHANGE_UICONTROLLER_UUID >> $HISTORY_LOG_OUTPUT
		scm deliver --components $SOFTWARE_CHANGE_UICONTROLLER_UUID >> $HISTORY_LOG_OUTPUT

		sleep 1	
		scm show status
		rm $HISTORY_DETAILED_OUTPUT
		echo "Getting Diffs from previous version $SOFTWARE_CHANGE_BASELINE_VALUE and $RELEASE_VERSION_SNAPHOT" >> $HISTORY_DETAILED_OUTPUT
		echo "Build Path $BUILD_DROP" >> $HISTORY_DETAILED_OUTPUT
		
		scm compare --include-types bwsf --show cdio snapshot "$RELEASE_VERSION_SNAPHOT" snapshot "$SOFTWARE_CHANGE_BASELINE_VALUE" >> $HISTORY_DETAILED_OUTPUT || BUILD_ERROR_FLAG=$((BUILD_ERROR_FLAG+1))

		cat $HISTORY_DETAILED_OUTPUT >> $HISTORY_LOG_OUTPUT
		scm logout --repository-uri Jazz >> $HISTORY_LOG_OUTPUT

		# SEND EMAIL NOTIFICATION
		java -jar $BUILD_SCRIPTS/EmailServer.jar $BUILD_SCRIPTS/EmailSetup.json "GSX P1 UIController Daily Build" "Build Started :)"
	fi
fi

# UPDATE VERSION FILE
echo "Version: UI $UIC_VERSION_NUM_MAJOR.$UIC_VERSION_NUM_MINOR.$UIC_VERSION_NUM_BUILD.$UIC_VERSION_NUM_AUTOS_NEW" >> $HISTORY_VERSION_OUTPUT

# DO THE BUILD & ZIP IT
cd $WORKSPACE
cd $QT_COMPONENT
"/opt/qt5pi/bin/qmake" UIController.pro -spec devices/linux-rasp-pi3-vc4-g++ CONFIG+=debug CONFIG+=qml_debug >> $HISTORY_LOG_OUTPUT
"/usr/bin/make" clean -j2 >> $HISTORY_LOG_OUTPUT
"/usr/bin/make" -j2 >> $HISTORY_LOG_OUTPUT || BUILD_ERROR_FLAG=$((BUILD_ERROR_FLAG+1))

if [ $BUILD_ERROR_FLAG -eq 0 ]; then
	tar -czvf $BUILD_SCRIPTS/$BuildDate.tar.gz UIController >> $HISTORY_LOG_OUTPUT
	cd $BUILD_DROP >> $HISTORY_LOG_OUTPUT
	mkdir $BuildDate >> $HISTORY_LOG_OUTPUT
	cp $BUILD_SCRIPTS/$BuildDate.tar.gz $BUILD_DROP/$BuildDate >> $HISTORY_LOG_OUTPUT
	cp $HISTORY_VERSION_OUTPUT $BUILD_DROP/$BuildDate >> $HISTORY_LOG_OUTPUT
	if [ $FORCE_BUILD -eq 0 ]; then
		java -jar $BUILD_SCRIPTS/EmailServer.jar $BUILD_SCRIPTS/EmailSetup.json "GSX P1 UIController Daily Build" "Build Finish :D \n $BUILD_DROP/$BuildDate" $HISTORY_DETAILED_OUTPUT $HISTORY_VERSION_OUTPUT
	else
		java -jar $BUILD_SCRIPTS/EmailServer.jar $BUILD_SCRIPTS/EmailSetup.json "GSX P1 UIController Daily Build" "Force Build >:( \n $BUILD_DROP/$BuildDate" $HISTORY_VERSION_OUTPUT
	fi	
else
	java -jar $BUILD_SCRIPTS/EmailServer.jar $BUILD_SCRIPTS/EmailSetup.json "GSX P1 UIController Daily Build" "Build Fail :(.." $HISTORY_LOG_OUTPUT $HISTORY_DETAILED_OUTPUT $HISTORY_VERSION_OUTPUT
fi

cd $BUILD_SCRIPTS


