# tcInfo.tcl - generated by tcInfoGen.tcl


set tcWIND_HOME [file normalize [prjEnv WIND_HOME]]

set tcWIND_HOST_TYPE [prjEnv WIND_HOST_TYPE]

if {$tcWIND_HOST_TYPE == "x86-win32"} {
# this will be the WIN subst
set tct1 /WIN64/bin
} else {
# this will be the LINUX subst
set tct1 /LINUX64/bin
}


# toolchain : ARMARCH7llvm

namespace eval tcInfo {}

lappend tcInfo::ToolFamilies(ARMARCH7) llvm
set tcInfo_ARMARCH7llvm(TOOL_FAMILY) llvm
set ::tcInfo_ARMARCH7llvm(CC) "${tcWIND_HOME}/compilers/llvm-11.1.0.1${tct1}/clang"
set ::tcInfo_ARMARCH7llvm(CPP) "${tcWIND_HOME}/compilers/llvm-11.1.0.1${tct1}/clang -E"
set ::tcInfo_ARMARCH7llvm(AS) "${tcWIND_HOME}/compilers/llvm-11.1.0.1${tct1}/clang"
set ::tcInfo_ARMARCH7llvm(LD) "${tcWIND_HOME}/compilers/llvm-11.1.0.1${tct1}/ldarm"
set ::tcInfo_ARMARCH7llvm(NM) "${tcWIND_HOME}/compilers/llvm-11.1.0.1${tct1}/nmarm -g"
set ::tcInfo_ARMARCH7llvm(SIZE) "${tcWIND_HOME}/compilers/llvm-11.1.0.1${tct1}/sizearm"
set ::tcInfo_ARMARCH7llvm(AR) "${tcWIND_HOME}/compilers/llvm-11.1.0.1${tct1}/ararm"
set ::tcInfo_ARMARCH7llvm(HEX_FLAGS) ""
set ::tcInfo_ARMARCH7llvm(OPTION_INCLUDE_DIR) -I
set ::tcInfo_ARMARCH7llvm(OPTION_DEFINE_MACRO) -D
set ::tcInfo_ARMARCH7llvm(OPTION_UNDEFINE_MACRO) -U
set ::tcInfo_ARMARCH7llvm(OPTION_LANG_CDF) "-xassembler-with-cpp"
set ::tcInfo_ARMARCH7llvm(OPTION_LANG_C) "-xc"
set ::tcInfo_ARMARCH7llvm(OPTION_GENERATE_DEPENDENCY_FILE) -MD
set ::tcInfo_ARMARCH7llvm(OPTION_DEPEND) "-M -w"
set ::tcInfo_ARMARCH7llvm(CC_ARCH_SPEC) "-fno-builtin -mabi=aapcs -mlittle-endian --target=arm-eabi -mfpu=vfpv4 -mfloat-abi=hard -mcpu=cortex-a15"
namespace eval ::tc_ARMARCH7llvm { }

set ::tc_ARMARCH7llvm::tcname(little_hard) llvm

namespace eval ::tc_ARMARCH7llvm::tool_cc {

    proc type {} {
	return "C compiler"
    }

    proc inputSuffixes {} {
	return ".c"
    }

    proc outputFiles {inFile} {
	return [file rootname [file tail $inFile]].o
    }

    proc buildCmds {flags file} {
	return [list "\$(CC) $flags -c $file"]
    }

    proc toolMacro {} {
	return CC
    }

    proc flagsMacro {} {
	return CFLAGS
    }

    proc sdFlagsMacro {} {
	return CC_SDA_FLAGS
    }
}

namespace eval ::tc_ARMARCH7llvm::tool_cxx {

    proc type {} {
	return "C++ compiler"
    }

    proc inputSuffixes {} {
	return ".cxx .cpp .cc .cp .c++ .CPP .C"
    }

    proc outputFiles {inFile} {
	return [file rootname [file tail $inFile]].o
    }

    proc buildCmds {flags file} {
	return [list "\$(CXX) $flags -c $file"]
    }

    proc toolMacro {} {
	return CXX
    }

    proc flagsMacro {} {
	return C++FLAGS
    }

    proc sdFlagsMacro {} {
	return CC_SDA_FLAGS
    }
}

namespace eval ::tc_ARMARCH7llvm::tool_as {

    proc type {} {
	return assembler
    }

    proc inputSuffixes {} {
	return ".s .S"
    }

    proc outputFiles {inFile} {
	return [file rootname [file tail $inFile]].o
    }

    proc buildCmds {flags file} {
	set tc [namespace parent]
	if {[${tc}::asmHasCpp]} {
	    return [list "\$(CC) $flags -c $file -o [outputFiles $file]"]
	}
	global tcInfo_[${tc}::name]
	regsub -all -- " -MD" $flags "" cppFlags
	set tmpFile [file rootname $file]_tmp.s
	return [list "\$(CPP) $cppFlags $file > ${tmpFile}" "\$(CC) $flags -c ${tmpFile} -o [outputFiles $file]" "\$(RM) ${tmpFile}"]
    }

    proc toolMacro {} {
	return CC
    }

    proc flagsMacro {} {
	return CFLAGS_AS
    }
    proc sdFlagsMacro {} {
	return 
    }
}

namespace eval ::tc_ARMARCH7llvm::tool_ld {

    proc type {} {
	return "linker"
    }

    proc inputSuffixes {} {
	return ""
    }

    proc outputFiles {inFile} {
	return [file rootname [file tail $inFile]].o
    }

    proc buildCmds {flags file} {
	return [list "${tcWIND_HOME}/compilers/llvm-11.1.0.1${tct1}/ldarm $flags -c $file"]
    }

    proc toolMacro {} {
	return LD
    }

    proc flagsMacro {} {
	return LDFLAGS
    }
}

namespace eval ::tc_ARMARCH7llvm {

    proc type {} {
	return C++
    }

    proc tool {} {
	return llvm
    }

    proc family {} {
	return llvm
    }

    proc cpu {} {
	return ARMARCH7
    }

    proc archDir {} {
	return arm
    }

    proc name {} {
	return ARMARCH7llvm
    }

    proc toolListGet {} {
	return [namespace children [namespace current] tool_*]
    }

    proc toolFindByFile {file} {
	foreach tool [toolListGet] {
	    if {[lsearch [${tool}::inputSuffixes] [file extension $file]] != -1} {
		return $tool
	    }
	}
	prjWarnLog "no tool works on file $file"
	return ""
    }

    proc toolFindByType {type} {
	foreach tool [toolListGet] {
	    if {[${tool}::type] == $type} {
		return $tool
	    }
	}
	prjWarnLog "no tool of type $type"
	return ""
    }

    proc dependFiles {tool flags file} {
	regsub -all -- " -MD" $flags "" cppFlags
	if {[catch {set bUseQuickScan [::Dependencies::UseQuickScan?]}] || !$bUseQuickScan || [catch {set result [DependencyAnalyzer::GenerateDependenciesFromFile $cppFlags $file]}]} {
	    set result [oldDependFiles $tool $flags $file]
	}
	return $result
    }

    proc oldDependFiles {tool flags file} {

	global tcInfo_[name]

	regsub -all -- " -MD" $flags "" cppFlags
	set errorFile [tempFileGet]
	if {[catch {eval exec ${tcWIND_HOME}/compilers/llvm-11.1.0.1${tct1}/clang -E -M -w $cppFlags $file 2>  [filenameQuoteIfNecessary $errorFile]} depend]} {
	    set fd [open $errorFile r]
	    set dependError [read $fd]
	    close $fd
	    error "dependency generation failed: $dependError"
	}
	file delete $errorFile
	regsub -all { \\} $depend {} depend
	regsub -all {\\} $depend {\/} depend
	return [lrange $depend 2 end]
    }

    proc macroListGet {} {
	global tcInfo_[name]
	return [array names tcInfo_[name]]
    }

    proc macroDefaultValGet {macro} {
	global tcInfo_[name]
	return [set tcInfo_[name]($macro)]
    }

    proc commSymLink {} {
	switch -glob [archDir] {
	    mc68k {return symbol}
	    default {return module}
	}
    }

    proc defaultWtxDownloadFlags {strFilename} {
	set bufNmOutput {}
	regsub -- -g [macroDefaultValGet NM] {} strCmd
	set bFailed [catch {set bufNmOutput "\n[eval exec $strCmd $strFilename ]" } ]
	if {$bFailed || [regexp "\n0+\[ \t]+\[A-Za-z]\[ \t]+___gnu_compiled_cplusplus" $bufNmOutput] } {
	    return {LOAD_GLOBAL_SYMBOLS|LOAD_COMMON_MATCH_ALL}
	} else {
	    return {LOAD_GLOBAL_SYMBOLS|LOAD_COMMON_MATCH_NONE}
	}
    }

    proc asmHasCpp {} {
	return 1
    }

    proc endian {} {
	return little
    }

    proc fp {} {
	return hard
    }

    proc dm {} {
	return [list ILP32 ]
    }

    proc default_VSB {} {
	return arm/ARMARCH7
    }

}

if {[info commands prjTcAdd] == "prjTcAdd"} {
    prjTcAdd ::tc_ARMARCH7llvm
}
