# Makefile generated by the project manager
#


# GENERATED: Mon Aug 07 09:37:06 EDT 2023
# DO NOT EDIT - file is regenerated whenever the project changes


## core information

ifeq ($(wildcard Makefile.mk),)
PRJ_DIR        = ..
else
PRJ_DIR        = .
endif
PRJ_FILE       = AM5728_P1_VIP.wpj
PRJ_FULL_PATH  = C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VIP
PRJ_TYPE       = vxWorks
PRJ_OBJS       = prjConfig.o linkSyms.o loadInvokeModule.o loggerModule.o
USER_OBJS      = 
PRJ_MAKEFILE   = $(PRJ_DIR)/Makefile.mk
BOOT_OBJS      =  $(BOOT_EXTRA)
BUILD_SPEC     = default
BSP_DIR        = $(PRJ_DIR)/ti_sitara_ctxa15_branson_2_1_0_0
VSB_DIR        = $(PRJ_DIR)/../AM5728_P1_VSB
VXBUILD        = SMP
OPT            = -inet6



## set searching BSP directories for dependencies

vpath %.c $(BSP_DIR)
vpath %.cpp $(BSP_DIR)
vpath %.cxx $(BSP_DIR)
vpath %.cc $(BSP_DIR)
vpath %.cp $(BSP_DIR)
vpath %.c++ $(BSP_DIR)
vpath %.CPP $(BSP_DIR)
vpath %.C $(BSP_DIR)
vpath %.s $(BSP_DIR)
vpath %.s $(BSP_DIR)

## build-configuration info

CPU            = ARMARCH7
TOOL           = llvm
TOOL_FAMILY    = llvm
TOOL_VERSION   = llvm_2016_04
_CC_VERSION    = llvm_11_1_0_1
ifeq ($(BUILD_SPEC),default)
DEFAULT_RULE   = uVxWorks
endif


## Memory adresses variables

RAM_LOW_ADRS = 0x00100000
RAM_HIGH_ADRS = 0x01000000
LOCAL_MEM_PHYS_ADRS = 0x84000000
KERNEL_LOAD_ADRS = 0x84100000

## component-configuration info

COMPONENTS = DRV_AM35XX_SPI \
	DRV_AM38XX_I2C \
	DRV_AM572x_QSPI \
	DRV_ARM_GEN_TIMER_SYSTIMERDEV \
	DRV_CLK_FDT_AM4 \
	DRV_END_FDT_TI_CPSW \
	DRV_GPIO_FDT_OMAP \
	DRV_I2C_EEPROM \
	DRV_I2C_PCFRTC \
	DRV_MMCSTORAGE_CARD \
	DRV_PINMUX_FDT_AM3 \
	DRV_SDSTORAGE_CARD \
	DRV_SIO_TI_AM3 \
	DRV_TIMER_FDT_OMAP3 \
	DRV_TI_EDMA3 \
	DRV_TI_MMCHS_CTRL \
	DRV_USB_DWC3_TI \
	INCLUDE_DOSFS \
	INCLUDE_EXTPWR_GPIO_ENA \
	INCLUDE_FDT_MICREL_PHY \
	INCLUDE_HRFS \
	INCLUDE_IPSSL \
	INCLUDE_LEDDRV \
	INCLUDE_MEM_LAYOUT_CHECK \
	INCLUDE_STANDALONE_DTB \
	INCLUDE_USB_GEN2_MOUSE_INIT \
	INCLUDE_USB_GEN2_STORAGE_INIT \
	INCLUDE_USB_PHY_TI_AM572X \
	INCLUDE_VXBUS_RTC_LIB

USER_CONFIGLETTES =

SUBPROJECTS = BSP  

SUBPROJECT_DIR_BSP = $(BSP_DIR)
MANAGED_LIBS = 
COMPONENT_LIBS = 

PROJECT_LINK_SYMDEFS = 


include $(WIND_KRNL_MK)/defs.project.mk


## project-configuration info


## build-configuration info

ifeq ($(BUILD_SPEC),default)
EXTRA_MODULES    = $(SUB_TARGETS)
endif

# override make definitions only below this line


# override make definitions only above this line

include $(WIND_KRNL_MK)/rules.project.mk


## build-configuration info

ifeq ($(BUILD_SPEC),default)

loadInvokeModule.o:  $(PRJ_DIR)/loadInvokeModule.c 
	$(RM) loadInvokeModule.o
	$(CC) \
	$(CFLAGS) \
	$(CC_SDA_FLAGS) \
	$(CFLAGS_OPTIONS_ALL) \
	-c \
	$(PRJ_DIR)/loadInvokeModule.c

loggerModule.o:  $(PRJ_DIR)/loggerModule.c 
	$(RM) loggerModule.o
	$(CC) \
	$(CFLAGS) \
	$(CC_SDA_FLAGS) \
	$(CFLAGS_OPTIONS_ALL) \
	-c \
	$(PRJ_DIR)/loggerModule.c
endif


## user defined rules

prjConfig.o : $(PRJ_DIR)/prjConfig.c
	$(CC) \
	$(OPTION_OBJECT_ONLY) \
	$(CFLAGS) \
	$(CFLAGS_OPTIONS_ALL) \
	$(PROJECT_BSP_FLAGS_EXTRA) \
	-fno-stack-protector \
	$(PRJ_DIR)/prjConfig.c \
	-o \
	$@

linkSyms.o : $(PRJ_DIR)/linkSyms.c
	$(CC) \
	$(OPTION_OBJECT_ONLY) \
	$(CFLAGS) \
	$(CFLAGS_OPTIONS_ALL) \
	$(PROJECT_BSP_FLAGS_EXTRA) \
	-fno-stack-protector \
	$(PRJ_DIR)/linkSyms.c \
	-o \
	$@


src_build :

src_depend :

$(PRJ_FULL_PATH)/compObjs.lst : $(PRJ_MAKEFILE)
	@ $(RM) $@
	@ touch $@

src_clean :
	@ $(RM) compObjs.lst
	@ $(RM) default/build_vars_list
	@ $(RM) vip_config.json
