
# this file is automatically generated by defs.vsb.tmpl.mk

global env


    
    

set _VSB_CONFIG_TOOL_VERSION_WIN_PATH [file join $env(WIND_HOME) ./compilers/llvm-11.1.0.1/WIN64/bin] 

set _VSB_CONFIG_TOOL2_VERSION_WIN_PATH [file join {}] 
    

set _VSB_CONFIG_TOOL_VERSION_LINUX_PATH [file join $env(WIND_HOME) ./compilers/llvm-11.1.0.1/LINUX64/bin] 

set _VSB_CONFIG_TOOL2_VERSION_LINUX_PATH [file join {}]
