
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_BDM_SATA)
__FILES_GENERATED += $(__FILES_GENERATED_BDM_SATA)




	
	

	
# copying directory h to $(VSB_DIR)/krnl/h/public




PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbSataLib.h

__FILES_TO_COPY_BDM_SATA += $(VSB_DIR)/krnl/h/public/vxbSataLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSataLib.h
$(error "while processing layer= BDM_SATA target $(VSB_DIR)/krnl/h/public/vxbSataLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbSataLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSataLib.h = BDM_SATA
endif





 

$(VSB_DIR)/krnl/h/public/vxbSataLib.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata/h/vxbSataLib.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbSataXbd.h

__FILES_TO_COPY_BDM_SATA += $(VSB_DIR)/krnl/h/public/vxbSataXbd.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSataXbd.h
$(error "while processing layer= BDM_SATA target $(VSB_DIR)/krnl/h/public/vxbSataXbd.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbSataXbd.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSataXbd.h = BDM_SATA
endif





$(VSB_DIR)/krnl/h/public/vxbSataXbd.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata/h/vxbSataXbd.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	


	
	
	
	
	
	
	
	
	

	

	
	
	
	
	
	
	


	


	


	

	
BUILD : BDM_SATA_src_llvm__BUILD

.PHONY : BDM_SATA_src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_SATA_src_llvm

BDM_SATA_src_llvm__BUILD : 
	@ echo building BUILD layer BDM_SATA directory src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_SATA VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_SATA_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD


	

	

	

	

	

	

	


	
# copying directory cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFslSataStorage.cdf

__FILES_TO_COPY_BDM_SATA += $(VSB_DIR)/krnl/cdf/40vxbFslSataStorage.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFslSataStorage.cdf
$(error "while processing layer= BDM_SATA target $(VSB_DIR)/krnl/cdf/40vxbFslSataStorage.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFslSataStorage.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFslSataStorage.cdf = BDM_SATA
endif





 

$(VSB_DIR)/krnl/cdf/40vxbFslSataStorage.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata/cdf/40vxbFslSataStorage.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbAhciStorage.cdf

__FILES_TO_COPY_BDM_SATA += $(VSB_DIR)/krnl/cdf/40vxbAhciStorage.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbAhciStorage.cdf
$(error "while processing layer= BDM_SATA target $(VSB_DIR)/krnl/cdf/40vxbAhciStorage.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbAhciStorage.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbAhciStorage.cdf = BDM_SATA
endif





$(VSB_DIR)/krnl/cdf/40vxbAhciStorage.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata/cdf/40vxbAhciStorage.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40ataDevNameConfig.cdf

__FILES_TO_COPY_BDM_SATA += $(VSB_DIR)/krnl/cdf/40ataDevNameConfig.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40ataDevNameConfig.cdf
$(error "while processing layer= BDM_SATA target $(VSB_DIR)/krnl/cdf/40ataDevNameConfig.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40ataDevNameConfig.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40ataDevNameConfig.cdf = BDM_SATA
endif





$(VSB_DIR)/krnl/cdf/40ataDevNameConfig.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata/cdf/40ataDevNameConfig.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbSI31xxStorage.cdf

__FILES_TO_COPY_BDM_SATA += $(VSB_DIR)/krnl/cdf/40vxbSI31xxStorage.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSI31xxStorage.cdf
$(error "while processing layer= BDM_SATA target $(VSB_DIR)/krnl/cdf/40vxbSI31xxStorage.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbSI31xxStorage.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSI31xxStorage.cdf = BDM_SATA
endif





$(VSB_DIR)/krnl/cdf/40vxbSI31xxStorage.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata/cdf/40vxbSI31xxStorage.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbPiixStorage.cdf

__FILES_TO_COPY_BDM_SATA += $(VSB_DIR)/krnl/cdf/40vxbPiixStorage.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbPiixStorage.cdf
$(error "while processing layer= BDM_SATA target $(VSB_DIR)/krnl/cdf/40vxbPiixStorage.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbPiixStorage.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbPiixStorage.cdf = BDM_SATA
endif





$(VSB_DIR)/krnl/cdf/40vxbPiixStorage.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata/cdf/40vxbPiixStorage.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	# PRENOBUILD=(PRENOBUILD) BDM_SATA=(layer) cdf=(dir)

PRENOBUILD_BDM_SATA_cdf_FILES = cdf/40vxbFslSataStorage.cdf cdf/40vxbAhciStorage.cdf cdf/40ataDevNameConfig.cdf cdf/40vxbSI31xxStorage.cdf cdf/40vxbPiixStorage.cdf

PRENOBUILD_BDM_SATA_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_SATA_cdf_DIR)/,$(PRENOBUILD_BDM_SATA_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_SATA

PRENOBUILD_BDM_SATA : cdf_PRENOBUILD_BDM_SATA

cdf_PRENOBUILD_BDM_SATA : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SATA_cdf.cdf

__FILES_TO_GENERATE_BDM_SATA += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SATA_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SATA_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SATA_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SATA_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_SATA_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_SATA_cdf_FILES))),BDM_SATA))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SATA_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_SATA -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SATA_cdf.tmp

	
	
	
	

	
# copying directory cfg to $(VSB_DIR)/krnl/configlette




PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrAta.c

__FILES_TO_COPY_BDM_SATA += $(VSB_DIR)/krnl/configlette/usrAta.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrAta.c
$(error "while processing layer= BDM_SATA target $(VSB_DIR)/krnl/configlette/usrAta.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrAta.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrAta.c = BDM_SATA
endif





 

$(VSB_DIR)/krnl/configlette/usrAta.c : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sata/cfg/usrAta.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



	

	
__DIR_TARGETS += $(__DIR_TARGETS_BDM_SATA)

__DIR_TARGETS_BDM_SATA += $(VSB_DIR)/krnl/cdf $(VSB_DIR)/krnl/configlette $(VSB_DIR)/krnl/h/public C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/cdf C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/configlette C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/share/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/usr/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/vsblCdf

