
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_BDM_NVRAM)
__FILES_GENERATED += $(__FILES_GENERATED_BDM_NVRAM)




	
	

	
# copying directory h to $(VSB_DIR)/krnl/h/public





	


	
	
	
	
	
	
	
	
	

	

	
	
	
	
	
	
	


	


	


	

	
BUILD : BDM_NVRAM_src_llvm__BUILD

.PHONY : BDM_NVRAM_src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_NVRAM_src_llvm

BDM_NVRAM_src_llvm__BUILD : 
	@ echo building BUILD layer BDM_NVRAM directory src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/nvram/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_NVRAM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_NVRAM_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD


	

	

	

	

	

	

	


	
# copying directory cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40bdm_nvram.cdf

__FILES_TO_COPY_BDM_NVRAM += $(VSB_DIR)/krnl/cdf/40bdm_nvram.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40bdm_nvram.cdf
$(error "while processing layer= BDM_NVRAM target $(VSB_DIR)/krnl/cdf/40bdm_nvram.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40bdm_nvram.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40bdm_nvram.cdf = BDM_NVRAM
endif





 

$(VSB_DIR)/krnl/cdf/40bdm_nvram.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/nvram/cdf/40bdm_nvram.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	# PRENOBUILD=(PRENOBUILD) BDM_NVRAM=(layer) cdf=(dir)

PRENOBUILD_BDM_NVRAM_cdf_FILES = cdf/40bdm_nvram.cdf

PRENOBUILD_BDM_NVRAM_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/nvram

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_NVRAM_cdf_DIR)/,$(PRENOBUILD_BDM_NVRAM_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_NVRAM

PRENOBUILD_BDM_NVRAM : cdf_PRENOBUILD_BDM_NVRAM

cdf_PRENOBUILD_BDM_NVRAM : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_NVRAM_cdf.cdf

__FILES_TO_GENERATE_BDM_NVRAM += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_NVRAM_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_NVRAM_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_NVRAM_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_NVRAM_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_NVRAM_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_NVRAM_cdf_FILES))),BDM_NVRAM))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_NVRAM_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_NVRAM -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_NVRAM_cdf.tmp

	
	
	
	

	
# copying directory cfg to $(VSB_DIR)/krnl/configlette




PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrNullNvRam.c

__FILES_TO_COPY_BDM_NVRAM += $(VSB_DIR)/krnl/configlette/usrNullNvRam.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrNullNvRam.c
$(error "while processing layer= BDM_NVRAM target $(VSB_DIR)/krnl/configlette/usrNullNvRam.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrNullNvRam.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrNullNvRam.c = BDM_NVRAM
endif





 

$(VSB_DIR)/krnl/configlette/usrNullNvRam.c : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/nvram/cfg/usrNullNvRam.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrFlashNvRam.c

__FILES_TO_COPY_BDM_NVRAM += $(VSB_DIR)/krnl/configlette/usrFlashNvRam.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrFlashNvRam.c
$(error "while processing layer= BDM_NVRAM target $(VSB_DIR)/krnl/configlette/usrFlashNvRam.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrFlashNvRam.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrFlashNvRam.c = BDM_NVRAM
endif





$(VSB_DIR)/krnl/configlette/usrFlashNvRam.c : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/nvram/cfg/usrFlashNvRam.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



	

	
__DIR_TARGETS += $(__DIR_TARGETS_BDM_NVRAM)

__DIR_TARGETS_BDM_NVRAM += $(VSB_DIR)/krnl/cdf $(VSB_DIR)/krnl/configlette C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/cdf C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/configlette C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/share/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/usr/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/vsblCdf

