
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_BDM_SDMMC)
__FILES_GENERATED += $(__FILES_GENERATED_BDM_SDMMC)




	
	

	
# copying directory core/h to $(VSB_DIR)/krnl/h/public




PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbSdMmcLib.h

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/h/public/vxbSdMmcLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSdMmcLib.h
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/h/public/vxbSdMmcLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbSdMmcLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSdMmcLib.h = BDM_SDMMC
endif





 

$(VSB_DIR)/krnl/h/public/vxbSdMmcLib.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/core/h/vxbSdMmcLib.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory device/storage/h to $(VSB_DIR)/krnl/h/public




PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbSdStorage.h

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/h/public/vxbSdStorage.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSdStorage.h
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/h/public/vxbSdStorage.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbSdStorage.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSdStorage.h = BDM_SDMMC
endif





$(VSB_DIR)/krnl/h/public/vxbSdStorage.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/device/storage/h/vxbSdStorage.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/blkXbd.h

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/h/public/blkXbd.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/blkXbd.h
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/h/public/blkXbd.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_blkXbd.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/blkXbd.h = BDM_SDMMC
endif





$(VSB_DIR)/krnl/h/public/blkXbd.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/device/storage/h/blkXbd.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbMmcStorage.h

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/h/public/vxbMmcStorage.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbMmcStorage.h
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/h/public/vxbMmcStorage.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbMmcStorage.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbMmcStorage.h = BDM_SDMMC
endif





$(VSB_DIR)/krnl/h/public/vxbMmcStorage.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/device/storage/h/vxbMmcStorage.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory host/sdhc/h to $(VSB_DIR)/krnl/h/public




PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbSdhcCtrl.h

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/h/public/vxbSdhcCtrl.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSdhcCtrl.h
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/h/public/vxbSdhcCtrl.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbSdhcCtrl.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSdhcCtrl.h = BDM_SDMMC
endif





$(VSB_DIR)/krnl/h/public/vxbSdhcCtrl.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/sdhc/h/vxbSdhcCtrl.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory host/timmchs/h to $(VSB_DIR)/krnl/h/public




PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbTiMmchsCtrl.h

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/h/public/vxbTiMmchsCtrl.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbTiMmchsCtrl.h
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/h/public/vxbTiMmchsCtrl.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbTiMmchsCtrl.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbTiMmchsCtrl.h = BDM_SDMMC
endif





$(VSB_DIR)/krnl/h/public/vxbTiMmchsCtrl.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/timmchs/h/vxbTiMmchsCtrl.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory host/rcarsdhi/h to $(VSB_DIR)/krnl/h/public




PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbRcarH3Mmc.h

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/h/public/vxbRcarH3Mmc.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbRcarH3Mmc.h
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/h/public/vxbRcarH3Mmc.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbRcarH3Mmc.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbRcarH3Mmc.h = BDM_SDMMC
endif





$(VSB_DIR)/krnl/h/public/vxbRcarH3Mmc.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/rcarsdhi/h/vxbRcarH3Mmc.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory host/spisdhi/h to $(VSB_DIR)/krnl/h/public




PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbSpiSdhi.h

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/h/public/vxbSpiSdhi.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSpiSdhi.h
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/h/public/vxbSpiSdhi.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbSpiSdhi.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbSpiSdhi.h = BDM_SDMMC
endif





$(VSB_DIR)/krnl/h/public/vxbSpiSdhi.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/spisdhi/h/vxbSpiSdhi.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	


	
	
	
	
	
	
	
	
	

	

	
	
	
	
	
	
	


	
PREBUILD_GENHEADERS : BDM_SDMMC_core/genh_llvm__PREBUILD_GENHEADERS

PREBUILD_GENHEADERS_BDM_SDMMC_TARGETS += BDM_SDMMC_core/genh_llvm__PREBUILD_GENHEADERS



BDM_SDMMC_core/genh_llvm__PREBUILD_GENHEADERS : 
	@ echo building PREBUILD_GENHEADERS layer BDM_SDMMC directory core/genh
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/core/genh && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_SDMMC VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=_PREBUILD_GENHEADERS_BDM_SDMMC_core_genh_llvm __WRS_TARGET=PREBUILD_GENHEADERS BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0  BUILDSTAGE=PREBUILD_GENHEADERS



	


	

	
BUILD : BDM_SDMMC_core/src_llvm__BUILD

.PHONY : BDM_SDMMC_core/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_SDMMC_core_src_llvm

BDM_SDMMC_core/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_SDMMC directory core/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/core/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_SDMMC VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_SDMMC_core_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : BDM_SDMMC_device/storage/src_llvm__BUILD

.PHONY : BDM_SDMMC_device/storage/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_SDMMC_device_storage_src_llvm

BDM_SDMMC_device/storage/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_SDMMC directory device/storage/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/device/storage/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_SDMMC VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_SDMMC_device_storage_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : BDM_SDMMC_host/sdhc/src_llvm__BUILD

.PHONY : BDM_SDMMC_host/sdhc/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_SDMMC_host_sdhc_src_llvm

BDM_SDMMC_host/sdhc/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_SDMMC directory host/sdhc/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/sdhc/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_SDMMC VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_SDMMC_host_sdhc_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : BDM_SDMMC_host/timmchs/src_llvm__BUILD

.PHONY : BDM_SDMMC_host/timmchs/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_SDMMC_host_timmchs_src_llvm

BDM_SDMMC_host/timmchs/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_SDMMC directory host/timmchs/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/timmchs/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_SDMMC VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_SDMMC_host_timmchs_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : BDM_SDMMC_host/rcarsdhi/src_llvm__BUILD

.PHONY : BDM_SDMMC_host/rcarsdhi/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_SDMMC_host_rcarsdhi_src_llvm

BDM_SDMMC_host/rcarsdhi/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_SDMMC directory host/rcarsdhi/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/rcarsdhi/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_SDMMC VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_SDMMC_host_rcarsdhi_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : BDM_SDMMC_host/spisdhi/src_llvm__BUILD

.PHONY : BDM_SDMMC_host/spisdhi/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_SDMMC_host_spisdhi_src_llvm

BDM_SDMMC_host/spisdhi/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_SDMMC directory host/spisdhi/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/spisdhi/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_SDMMC VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_SDMMC_host_spisdhi_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD


	

	

	

	

	

	

	


	
# copying directory core/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbSdMmc.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbSdMmc.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSdMmc.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbSdMmc.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbSdMmc.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSdMmc.cdf = BDM_SDMMC
endif





 

$(VSB_DIR)/krnl/cdf/40vxbSdMmc.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/core/cdf/40vxbSdMmc.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory device/storage/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbSdStorage.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbSdStorage.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSdStorage.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbSdStorage.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbSdStorage.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSdStorage.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbSdStorage.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/device/storage/cdf/40vxbSdStorage.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbMmcStorage.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbMmcStorage.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbMmcStorage.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbMmcStorage.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbMmcStorage.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbMmcStorage.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbMmcStorage.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/device/storage/cdf/40vxbMmcStorage.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory host/sdhc/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbZynqSdhcCtrl.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbZynqSdhcCtrl.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbZynqSdhcCtrl.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbZynqSdhcCtrl.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbZynqSdhcCtrl.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbZynqSdhcCtrl.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbZynqSdhcCtrl.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/sdhc/cdf/40vxbZynqSdhcCtrl.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbTiSdhcCtrl.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbTiSdhcCtrl.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbTiSdhcCtrl.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbTiSdhcCtrl.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbTiSdhcCtrl.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbTiSdhcCtrl.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbTiSdhcCtrl.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/sdhc/cdf/40vxbTiSdhcCtrl.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFslImxSdhcCtrl.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbFslImxSdhcCtrl.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFslImxSdhcCtrl.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbFslImxSdhcCtrl.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFslImxSdhcCtrl.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFslImxSdhcCtrl.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbFslImxSdhcCtrl.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/sdhc/cdf/40vxbFslImxSdhcCtrl.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFslSdhcCtrl.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbFslSdhcCtrl.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFslSdhcCtrl.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbFslSdhcCtrl.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFslSdhcCtrl.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFslSdhcCtrl.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbFslSdhcCtrl.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/sdhc/cdf/40vxbFslSdhcCtrl.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbPciSdhcCtrl.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbPciSdhcCtrl.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbPciSdhcCtrl.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbPciSdhcCtrl.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbPciSdhcCtrl.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbPciSdhcCtrl.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbPciSdhcCtrl.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/sdhc/cdf/40vxbPciSdhcCtrl.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbMcpSdhcCtrl.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbMcpSdhcCtrl.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbMcpSdhcCtrl.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbMcpSdhcCtrl.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbMcpSdhcCtrl.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbMcpSdhcCtrl.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbMcpSdhcCtrl.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/sdhc/cdf/40vxbMcpSdhcCtrl.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbRzn1Sdhc.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbRzn1Sdhc.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbRzn1Sdhc.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbRzn1Sdhc.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbRzn1Sdhc.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbRzn1Sdhc.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbRzn1Sdhc.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/sdhc/cdf/40vxbRzn1Sdhc.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory host/timmchs/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbTiMmchsCtrl.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbTiMmchsCtrl.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbTiMmchsCtrl.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbTiMmchsCtrl.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbTiMmchsCtrl.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbTiMmchsCtrl.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbTiMmchsCtrl.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/timmchs/cdf/40vxbTiMmchsCtrl.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory host/rcarsdhi/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbRcarH3Mmc.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbRcarH3Mmc.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbRcarH3Mmc.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbRcarH3Mmc.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbRcarH3Mmc.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbRcarH3Mmc.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbRcarH3Mmc.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/rcarsdhi/cdf/40vxbRcarH3Mmc.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory host/spisdhi/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbSpiSdhi.cdf

__FILES_TO_COPY_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/40vxbSpiSdhi.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSpiSdhi.cdf
$(error "while processing layer= BDM_SDMMC target $(VSB_DIR)/krnl/cdf/40vxbSpiSdhi.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbSpiSdhi.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSpiSdhi.cdf = BDM_SDMMC
endif





$(VSB_DIR)/krnl/cdf/40vxbSpiSdhi.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc/host/spisdhi/cdf/40vxbSpiSdhi.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	# PRENOBUILD=(PRENOBUILD) BDM_SDMMC=(layer) core_cdf=(dir)

PRENOBUILD_BDM_SDMMC_core_cdf_FILES = core/cdf/40vxbSdMmc.cdf

PRENOBUILD_BDM_SDMMC_core_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_SDMMC_core_cdf_DIR)/,$(PRENOBUILD_BDM_SDMMC_core_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_SDMMC

PRENOBUILD_BDM_SDMMC : core/cdf_PRENOBUILD_BDM_SDMMC

core/cdf_PRENOBUILD_BDM_SDMMC : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_core_cdf.cdf

__FILES_TO_GENERATE_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_core_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_core_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_core_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_core_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_SDMMC_core_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_SDMMC_core_cdf_FILES))),BDM_SDMMC))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_core_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_SDMMC -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_core_cdf.tmp
 # PRENOBUILD=(PRENOBUILD) BDM_SDMMC=(layer) device_storage_cdf=(dir)

PRENOBUILD_BDM_SDMMC_device_storage_cdf_FILES = device/storage/cdf/40vxbSdStorage.cdf device/storage/cdf/40vxbMmcStorage.cdf

PRENOBUILD_BDM_SDMMC_device_storage_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_SDMMC_device_storage_cdf_DIR)/,$(PRENOBUILD_BDM_SDMMC_device_storage_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_SDMMC

PRENOBUILD_BDM_SDMMC : device/storage/cdf_PRENOBUILD_BDM_SDMMC

device/storage/cdf_PRENOBUILD_BDM_SDMMC : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_device_storage_cdf.cdf

__FILES_TO_GENERATE_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_device_storage_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_device_storage_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_device_storage_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_device_storage_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_SDMMC_device_storage_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_SDMMC_device_storage_cdf_FILES))),BDM_SDMMC))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_device_storage_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_SDMMC -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_device_storage_cdf.tmp
 # PRENOBUILD=(PRENOBUILD) BDM_SDMMC=(layer) host_sdhc_cdf=(dir)

PRENOBUILD_BDM_SDMMC_host_sdhc_cdf_FILES = host/sdhc/cdf/40vxbZynqSdhcCtrl.cdf host/sdhc/cdf/40vxbTiSdhcCtrl.cdf host/sdhc/cdf/40vxbFslImxSdhcCtrl.cdf host/sdhc/cdf/40vxbFslSdhcCtrl.cdf host/sdhc/cdf/40vxbPciSdhcCtrl.cdf host/sdhc/cdf/40vxbMcpSdhcCtrl.cdf host/sdhc/cdf/40vxbRzn1Sdhc.cdf

PRENOBUILD_BDM_SDMMC_host_sdhc_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_SDMMC_host_sdhc_cdf_DIR)/,$(PRENOBUILD_BDM_SDMMC_host_sdhc_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_SDMMC

PRENOBUILD_BDM_SDMMC : host/sdhc/cdf_PRENOBUILD_BDM_SDMMC

host/sdhc/cdf_PRENOBUILD_BDM_SDMMC : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_sdhc_cdf.cdf

__FILES_TO_GENERATE_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_sdhc_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_sdhc_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_sdhc_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_sdhc_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_SDMMC_host_sdhc_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_SDMMC_host_sdhc_cdf_FILES))),BDM_SDMMC))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_sdhc_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_SDMMC -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_sdhc_cdf.tmp
 # PRENOBUILD=(PRENOBUILD) BDM_SDMMC=(layer) host_timmchs_cdf=(dir)

PRENOBUILD_BDM_SDMMC_host_timmchs_cdf_FILES = host/timmchs/cdf/40vxbTiMmchsCtrl.cdf

PRENOBUILD_BDM_SDMMC_host_timmchs_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_SDMMC_host_timmchs_cdf_DIR)/,$(PRENOBUILD_BDM_SDMMC_host_timmchs_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_SDMMC

PRENOBUILD_BDM_SDMMC : host/timmchs/cdf_PRENOBUILD_BDM_SDMMC

host/timmchs/cdf_PRENOBUILD_BDM_SDMMC : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_timmchs_cdf.cdf

__FILES_TO_GENERATE_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_timmchs_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_timmchs_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_timmchs_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_timmchs_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_SDMMC_host_timmchs_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_SDMMC_host_timmchs_cdf_FILES))),BDM_SDMMC))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_timmchs_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_SDMMC -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_timmchs_cdf.tmp
 # PRENOBUILD=(PRENOBUILD) BDM_SDMMC=(layer) host_rcarsdhi_cdf=(dir)

PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf_FILES = host/rcarsdhi/cdf/40vxbRcarH3Mmc.cdf

PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf_DIR)/,$(PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_SDMMC

PRENOBUILD_BDM_SDMMC : host/rcarsdhi/cdf_PRENOBUILD_BDM_SDMMC

host/rcarsdhi/cdf_PRENOBUILD_BDM_SDMMC : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf.cdf

__FILES_TO_GENERATE_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf_FILES))),BDM_SDMMC))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_SDMMC -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_rcarsdhi_cdf.tmp
 # PRENOBUILD=(PRENOBUILD) BDM_SDMMC=(layer) host_spisdhi_cdf=(dir)

PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf_FILES = host/spisdhi/cdf/40vxbSpiSdhi.cdf

PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/sdmmc

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf_DIR)/,$(PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_SDMMC

PRENOBUILD_BDM_SDMMC : host/spisdhi/cdf_PRENOBUILD_BDM_SDMMC

host/spisdhi/cdf_PRENOBUILD_BDM_SDMMC : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf.cdf

__FILES_TO_GENERATE_BDM_SDMMC += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf_FILES))),BDM_SDMMC))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_SDMMC -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_SDMMC_host_spisdhi_cdf.tmp

	
	
	
	

	
# copying directory core/cfg to $(VSB_DIR)/krnl/configlette




 
# copying directory host/sdhc/cfg to $(VSB_DIR)/krnl/configlette




 
# copying directory host/timmchs/cfg to $(VSB_DIR)/krnl/configlette




 
# copying directory host/rcarsdhi/cfg to $(VSB_DIR)/krnl/configlette




 
# copying directory host/spisdhi/cfg to $(VSB_DIR)/krnl/configlette






	

	
__DIR_TARGETS += $(__DIR_TARGETS_BDM_SDMMC)

__DIR_TARGETS_BDM_SDMMC += $(VSB_DIR)/krnl/cdf $(VSB_DIR)/krnl/h/public C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/cdf C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/configlette C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/share/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/usr/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/vsblCdf

