
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_BDM_FLASH)
__FILES_GENERATED += $(__FILES_GENERATED_BDM_FLASH)




	
	

	
# copying directory mtd/h to $(VSB_DIR)/krnl/h/public




# copying directory mtd/h/norflash to $(VSB_DIR)/krnl/h/public/norflash




PRENOBUILD : $(VSB_DIR)/krnl/h/public/norflash/vxbNorFlashLib.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/norflash/vxbNorFlashLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/norflash/vxbNorFlashLib.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/norflash/vxbNorFlashLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/norflash_vxbNorFlashLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/norflash/vxbNorFlashLib.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/norflash/vxbNorFlashLib.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/norflash/vxbNorFlashLib.h | $(VSB_DIR)/krnl/h/public/norflash
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/norflash/vxbNorFlash.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/norflash/vxbNorFlash.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/norflash/vxbNorFlash.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/norflash/vxbNorFlash.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/norflash_vxbNorFlash.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/norflash/vxbNorFlash.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/norflash/vxbNorFlash.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/norflash/vxbNorFlash.h | $(VSB_DIR)/krnl/h/public/norflash
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory mtd/h/nfc to $(VSB_DIR)/krnl/h/public/nfc




PRENOBUILD : $(VSB_DIR)/krnl/h/public/nfc/vxbNfcCore.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/nfc/vxbNfcCore.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/nfc/vxbNfcCore.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/nfc/vxbNfcCore.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/nfc_vxbNfcCore.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/nfc/vxbNfcCore.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/nfc/vxbNfcCore.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/nfc/vxbNfcCore.h | $(VSB_DIR)/krnl/h/public/nfc
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/nfc/vxbNfc.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/nfc/vxbNfc.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/nfc/vxbNfc.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/nfc/vxbNfc.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/nfc_vxbNfc.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/nfc/vxbNfc.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/nfc/vxbNfc.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/nfc/vxbNfc.h | $(VSB_DIR)/krnl/h/public/nfc
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/mtdCore.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/mtdCore.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/mtdCore.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/mtdCore.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_mtdCore.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/mtdCore.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/mtdCore.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/mtdCore.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory mtd/h/fcm to $(VSB_DIR)/krnl/h/public/fcm




PRENOBUILD : $(VSB_DIR)/krnl/h/public/fcm/vxbFcmCore.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/fcm/vxbFcmCore.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/fcm/vxbFcmCore.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/fcm/vxbFcmCore.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/fcm_vxbFcmCore.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/fcm/vxbFcmCore.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/fcm/vxbFcmCore.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/fcm/vxbFcmCore.h | $(VSB_DIR)/krnl/h/public/fcm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/fcm/vxbFcm.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/fcm/vxbFcm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/fcm/vxbFcm.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/fcm/vxbFcm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/fcm_vxbFcm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/fcm/vxbFcm.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/fcm/vxbFcm.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/fcm/vxbFcm.h | $(VSB_DIR)/krnl/h/public/fcm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory mtd/h/nand to $(VSB_DIR)/krnl/h/public/nand




PRENOBUILD : $(VSB_DIR)/krnl/h/public/nand/vxbNandFlash.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/nand/vxbNandFlash.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/nand/vxbNandFlash.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/nand/vxbNandFlash.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/nand_vxbNandFlash.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/nand/vxbNandFlash.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/nand/vxbNandFlash.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/nand/vxbNandFlash.h | $(VSB_DIR)/krnl/h/public/nand
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/nand/vxbNandFlashLib.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/nand/vxbNandFlashLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/nand/vxbNandFlashLib.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/nand/vxbNandFlashLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/nand_vxbNandFlashLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/nand/vxbNandFlashLib.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/nand/vxbNandFlashLib.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/nand/vxbNandFlashLib.h | $(VSB_DIR)/krnl/h/public/nand
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbFlash.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/vxbFlash.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbFlash.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/vxbFlash.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbFlash.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbFlash.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/vxbFlash.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/vxbFlash.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory mtd/h/alt5qspiflash to $(VSB_DIR)/krnl/h/public/alt5qspiflash




PRENOBUILD : $(VSB_DIR)/krnl/h/public/alt5qspiflash/vxbFdtAlt5QspiFlash.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/alt5qspiflash/vxbFdtAlt5QspiFlash.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/alt5qspiflash/vxbFdtAlt5QspiFlash.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/alt5qspiflash/vxbFdtAlt5QspiFlash.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/alt5qspiflash_vxbFdtAlt5QspiFlash.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/alt5qspiflash/vxbFdtAlt5QspiFlash.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/alt5qspiflash/vxbFdtAlt5QspiFlash.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/alt5qspiflash/vxbFdtAlt5QspiFlash.h | $(VSB_DIR)/krnl/h/public/alt5qspiflash
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory mtd/h/gpmc to $(VSB_DIR)/krnl/h/public/gpmc




PRENOBUILD : $(VSB_DIR)/krnl/h/public/gpmc/vxbGpmcCore.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/gpmc/vxbGpmcCore.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmc/vxbGpmcCore.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/gpmc/vxbGpmcCore.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmc_vxbGpmcCore.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmc/vxbGpmcCore.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/gpmc/vxbGpmcCore.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/gpmc/vxbGpmcCore.h | $(VSB_DIR)/krnl/h/public/gpmc
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/gpmc/vxbGpmc.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/gpmc/vxbGpmc.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmc/vxbGpmc.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/gpmc/vxbGpmc.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmc_vxbGpmc.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmc/vxbGpmc.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/gpmc/vxbGpmc.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/gpmc/vxbGpmc.h | $(VSB_DIR)/krnl/h/public/gpmc
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory mtd/h/rzn1qspiflash to $(VSB_DIR)/krnl/h/public/rzn1qspiflash




PRENOBUILD : $(VSB_DIR)/krnl/h/public/rzn1qspiflash/vxbRzn1QspiFlash.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/rzn1qspiflash/vxbRzn1QspiFlash.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/rzn1qspiflash/vxbRzn1QspiFlash.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/rzn1qspiflash/vxbRzn1QspiFlash.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/rzn1qspiflash_vxbRzn1QspiFlash.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/rzn1qspiflash/vxbRzn1QspiFlash.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/rzn1qspiflash/vxbRzn1QspiFlash.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/rzn1qspiflash/vxbRzn1QspiFlash.h | $(VSB_DIR)/krnl/h/public/rzn1qspiflash
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/flash.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/flash.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/flash.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/flash.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_flash.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/flash.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/flash.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/flash.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory mtd/h/gpmi to $(VSB_DIR)/krnl/h/public/gpmi




PRENOBUILD : $(VSB_DIR)/krnl/h/public/gpmi/vxbGpmi.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/gpmi/vxbGpmi.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmi/vxbGpmi.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/gpmi/vxbGpmi.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmi_vxbGpmi.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmi/vxbGpmi.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/gpmi/vxbGpmi.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/gpmi/vxbGpmi.h | $(VSB_DIR)/krnl/h/public/gpmi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/gpmi/vxbGpmiCore.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/gpmi/vxbGpmiCore.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmi/vxbGpmiCore.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/gpmi/vxbGpmiCore.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmi_vxbGpmiCore.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/gpmi/vxbGpmiCore.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/gpmi/vxbGpmiCore.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/gpmi/vxbGpmiCore.h | $(VSB_DIR)/krnl/h/public/gpmi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/vxbFlashCommon.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/vxbFlashCommon.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbFlashCommon.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/vxbFlashCommon.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_vxbFlashCommon.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/vxbFlashCommon.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/vxbFlashCommon.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/vxbFlashCommon.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/mtd.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/mtd.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/mtd.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/mtd.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_mtd.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/mtd.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/mtd.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/mtd.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory mtd/h/spiflash to $(VSB_DIR)/krnl/h/public/spiflash




PRENOBUILD : $(VSB_DIR)/krnl/h/public/spiflash/vxbSp25SpiFlash.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/spiflash/vxbSp25SpiFlash.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/spiflash/vxbSp25SpiFlash.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/spiflash/vxbSp25SpiFlash.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/spiflash_vxbSp25SpiFlash.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/spiflash/vxbSp25SpiFlash.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/spiflash/vxbSp25SpiFlash.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/h/spiflash/vxbSp25SpiFlash.h | $(VSB_DIR)/krnl/h/public/spiflash
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


 
# copying directory nftl/h to $(VSB_DIR)/krnl/h/public




# copying directory nftl/h/private to $(VSB_DIR)/krnl/h/public/private




PRENOBUILD : $(VSB_DIR)/krnl/h/public/private/ftlOsIf.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/private/ftlOsIf.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlOsIf.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/private/ftlOsIf.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private_ftlOsIf.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlOsIf.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/private/ftlOsIf.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/h/private/ftlOsIf.h | $(VSB_DIR)/krnl/h/public/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/private/ftlUtilP.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/private/ftlUtilP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlUtilP.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/private/ftlUtilP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private_ftlUtilP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlUtilP.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/private/ftlUtilP.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/h/private/ftlUtilP.h | $(VSB_DIR)/krnl/h/public/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/private/ftlCacheP.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/private/ftlCacheP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlCacheP.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/private/ftlCacheP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private_ftlCacheP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlCacheP.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/private/ftlCacheP.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/h/private/ftlCacheP.h | $(VSB_DIR)/krnl/h/public/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/private/ftlLibP.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/private/ftlLibP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlLibP.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/private/ftlLibP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private_ftlLibP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlLibP.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/private/ftlLibP.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/h/private/ftlLibP.h | $(VSB_DIR)/krnl/h/public/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/private/ftlFlashIf.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/private/ftlFlashIf.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlFlashIf.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/private/ftlFlashIf.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private_ftlFlashIf.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlFlashIf.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/private/ftlFlashIf.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/h/private/ftlFlashIf.h | $(VSB_DIR)/krnl/h/public/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/private/ftlBm.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/private/ftlBm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlBm.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/private/ftlBm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private_ftlBm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/ftlBm.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/private/ftlBm.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/h/private/ftlBm.h | $(VSB_DIR)/krnl/h/public/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/ftlLib.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/ftlLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/ftlLib.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/ftlLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_ftlLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/ftlLib.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/ftlLib.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/h/ftlLib.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory tffs/h to $(VSB_DIR)/krnl/h/public




# copying directory tffs/h/tffs to $(VSB_DIR)/krnl/h/public/tffs




PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/flcustom.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/flcustom.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flcustom.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/flcustom.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_flcustom.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flcustom.h = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/h/public/tffs/flcustom.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/flcustom.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/flsysfun.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/flsysfun.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flsysfun.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/flsysfun.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_flsysfun.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flsysfun.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/flsysfun.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/flsysfun.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/pcic.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/pcic.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/pcic.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/pcic.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_pcic.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/pcic.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/pcic.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/pcic.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/fltl.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/fltl.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/fltl.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/fltl.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_fltl.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/fltl.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/fltl.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/fltl.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/dosformt.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/dosformt.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/dosformt.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/dosformt.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_dosformt.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/dosformt.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/dosformt.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/dosformt.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/backgrnd.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/backgrnd.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/backgrnd.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/backgrnd.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_backgrnd.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/backgrnd.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/backgrnd.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/backgrnd.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/reedsol.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/reedsol.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/reedsol.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/reedsol.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_reedsol.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/reedsol.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/reedsol.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/reedsol.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/flsystem.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/flsystem.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flsystem.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/flsystem.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_flsystem.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flsystem.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/flsystem.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/flsystem.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/flbase.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/flbase.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flbase.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/flbase.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_flbase.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flbase.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/flbase.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/flbase.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/flflash.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/flflash.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flflash.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/flflash.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_flflash.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flflash.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/flflash.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/flflash.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/fatlite.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/fatlite.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/fatlite.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/fatlite.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_fatlite.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/fatlite.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/fatlite.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/fatlite.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/tffsDrv.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/tffsDrv.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/tffsDrv.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/tffsDrv.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_tffsDrv.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/tffsDrv.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/tffsDrv.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/tffsDrv.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/stdcomp.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/stdcomp.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/stdcomp.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/stdcomp.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_stdcomp.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/stdcomp.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/stdcomp.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/stdcomp.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/flbuffer.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/flbuffer.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flbuffer.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/flbuffer.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_flbuffer.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flbuffer.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/flbuffer.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/flbuffer.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/flsocket.h

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/flsocket.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flsocket.h
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/flsocket.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_flsocket.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/flsocket.h = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/flsocket.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/h/tffs/flsocket.h | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


 
# copying directory tffs_drv/h to $(VSB_DIR)/krnl/h/public




# copying directory tffs_drv/h/tffs to $(VSB_DIR)/krnl/h/public/tffs




PRENOBUILD : $(VSB_DIR)/krnl/h/public/tffs/tffsConfig.c

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/h/public/tffs/tffsConfig.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/tffsConfig.c
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/h/public/tffs/tffsConfig.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs_tffsConfig.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/tffs/tffsConfig.c = BDM_FLASH
endif





$(VSB_DIR)/krnl/h/public/tffs/tffsConfig.c : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs_drv/h/tffs/tffsConfig.c | $(VSB_DIR)/krnl/h/public/tffs
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



	


	
	
	
	
	
	
	
	
	

	

	
	
	
	
	
	
	


	


	


	

	
BUILD : BDM_FLASH_mtd/src_llvm__BUILD

.PHONY : BDM_FLASH_mtd/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_FLASH_mtd_src_llvm

BDM_FLASH_mtd/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_FLASH directory mtd/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_FLASH VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_FLASH_mtd_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : BDM_FLASH_nftl/src_llvm__BUILD

.PHONY : BDM_FLASH_nftl/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_FLASH_nftl_src_llvm

BDM_FLASH_nftl/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_FLASH directory nftl/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_FLASH VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_FLASH_nftl_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : BDM_FLASH_tffs/src_llvm__BUILD

.PHONY : BDM_FLASH_tffs/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_FLASH_tffs_src_llvm

BDM_FLASH_tffs/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_FLASH directory tffs/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_FLASH VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_FLASH_tffs_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : BDM_FLASH_tffs_drv/src_llvm__BUILD

.PHONY : BDM_FLASH_tffs_drv/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_FLASH_tffs_drv_src_llvm

BDM_FLASH_tffs_drv/src_llvm__BUILD : 
	@ echo building BUILD layer BDM_FLASH directory tffs_drv/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs_drv/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_FLASH VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_FLASH_tffs_drv_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD


	

	

	

	

	

	

	


	
# copying directory mtd/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbSp25SpiFlash.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbSp25SpiFlash.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSp25SpiFlash.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbSp25SpiFlash.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbSp25SpiFlash.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSp25SpiFlash.cdf = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/cdf/40vxbSp25SpiFlash.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbSp25SpiFlash.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbSpiFlash.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbSpiFlash.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSpiFlash.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbSpiFlash.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbSpiFlash.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbSpiFlash.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbSpiFlash.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbSpiFlash.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbEmif16.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbEmif16.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbEmif16.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbEmif16.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbEmif16.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbEmif16.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbEmif16.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbEmif16.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFcm.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbFcm.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFcm.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbFcm.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFcm.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFcm.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbFcm.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbFcm.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbNorFlash.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbNorFlash.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbNorFlash.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbNorFlash.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbNorFlash.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbNorFlash.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbNorFlash.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbNorFlash.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbGpmc.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbGpmc.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbGpmc.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbGpmc.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbGpmc.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbGpmc.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbGpmc.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbGpmc.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40mtd.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40mtd.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40mtd.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40mtd.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40mtd.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40mtd.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40mtd.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40mtd.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbNfc.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbNfc.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbNfc.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbNfc.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbNfc.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbNfc.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbNfc.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbNfc.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbGpmi.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbGpmi.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbGpmi.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbGpmi.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbGpmi.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbGpmi.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbGpmi.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbGpmi.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtAlt5QspiFlash.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbFdtAlt5QspiFlash.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtAlt5QspiFlash.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbFdtAlt5QspiFlash.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtAlt5QspiFlash.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtAlt5QspiFlash.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtAlt5QspiFlash.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbFdtAlt5QspiFlash.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbXspiFlash.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbXspiFlash.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbXspiFlash.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbXspiFlash.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbXspiFlash.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbXspiFlash.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbXspiFlash.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbXspiFlash.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbRzn1QspiFlash.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40vxbRzn1QspiFlash.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbRzn1QspiFlash.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40vxbRzn1QspiFlash.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbRzn1QspiFlash.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbRzn1QspiFlash.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40vxbRzn1QspiFlash.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cdf/40vxbRzn1QspiFlash.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory nftl/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40ftl.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/40ftl.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40ftl.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/40ftl.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40ftl.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40ftl.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/40ftl.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/cdf/40ftl.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory tffs/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/05tffs.cdf

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/cdf/05tffs.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/05tffs.cdf
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/cdf/05tffs.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_05tffs.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/05tffs.cdf = BDM_FLASH
endif





$(VSB_DIR)/krnl/cdf/05tffs.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/cdf/05tffs.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	# PRENOBUILD=(PRENOBUILD) BDM_FLASH=(layer) mtd_cdf=(dir)

PRENOBUILD_BDM_FLASH_mtd_cdf_FILES = mtd/cdf/40vxbSp25SpiFlash.cdf mtd/cdf/40vxbSpiFlash.cdf mtd/cdf/40vxbEmif16.cdf mtd/cdf/40vxbFcm.cdf mtd/cdf/40vxbNorFlash.cdf mtd/cdf/40vxbGpmc.cdf mtd/cdf/40mtd.cdf mtd/cdf/40vxbNfc.cdf mtd/cdf/40vxbGpmi.cdf mtd/cdf/40vxbFdtAlt5QspiFlash.cdf mtd/cdf/40vxbXspiFlash.cdf mtd/cdf/40vxbRzn1QspiFlash.cdf

PRENOBUILD_BDM_FLASH_mtd_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_FLASH_mtd_cdf_DIR)/,$(PRENOBUILD_BDM_FLASH_mtd_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_FLASH

PRENOBUILD_BDM_FLASH : mtd/cdf_PRENOBUILD_BDM_FLASH

mtd/cdf_PRENOBUILD_BDM_FLASH : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_mtd_cdf.cdf

__FILES_TO_GENERATE_BDM_FLASH += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_mtd_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_mtd_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_mtd_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_mtd_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_FLASH_mtd_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_FLASH_mtd_cdf_FILES))),BDM_FLASH))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_mtd_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_FLASH -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_mtd_cdf.tmp
 # PRENOBUILD=(PRENOBUILD) BDM_FLASH=(layer) nftl_cdf=(dir)

PRENOBUILD_BDM_FLASH_nftl_cdf_FILES = nftl/cdf/40ftl.cdf

PRENOBUILD_BDM_FLASH_nftl_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_FLASH_nftl_cdf_DIR)/,$(PRENOBUILD_BDM_FLASH_nftl_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_FLASH

PRENOBUILD_BDM_FLASH : nftl/cdf_PRENOBUILD_BDM_FLASH

nftl/cdf_PRENOBUILD_BDM_FLASH : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_nftl_cdf.cdf

__FILES_TO_GENERATE_BDM_FLASH += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_nftl_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_nftl_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_nftl_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_nftl_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_FLASH_nftl_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_FLASH_nftl_cdf_FILES))),BDM_FLASH))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_nftl_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_FLASH -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_nftl_cdf.tmp
 # PRENOBUILD=(PRENOBUILD) BDM_FLASH=(layer) tffs_cdf=(dir)

PRENOBUILD_BDM_FLASH_tffs_cdf_FILES = tffs/cdf/05tffs.cdf

PRENOBUILD_BDM_FLASH_tffs_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_FLASH_tffs_cdf_DIR)/,$(PRENOBUILD_BDM_FLASH_tffs_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM_FLASH

PRENOBUILD_BDM_FLASH : tffs/cdf_PRENOBUILD_BDM_FLASH

tffs/cdf_PRENOBUILD_BDM_FLASH : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_tffs_cdf.cdf

__FILES_TO_GENERATE_BDM_FLASH += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_tffs_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_tffs_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_tffs_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_tffs_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_FLASH_tffs_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_FLASH_tffs_cdf_FILES))),BDM_FLASH))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_tffs_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM_FLASH -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_FLASH_tffs_cdf.tmp

	
	
	
	

	
# copying directory mtd/cfg to $(VSB_DIR)/krnl/configlette




PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrMtd.c

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/configlette/usrMtd.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrMtd.c
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/configlette/usrMtd.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrMtd.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrMtd.c = BDM_FLASH
endif





 

$(VSB_DIR)/krnl/configlette/usrMtd.c : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/mtd/cfg/usrMtd.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory nftl/cfg to $(VSB_DIR)/krnl/configlette




PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrFtl.c

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/configlette/usrFtl.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrFtl.c
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/configlette/usrFtl.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrFtl.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrFtl.c = BDM_FLASH
endif





$(VSB_DIR)/krnl/configlette/usrFtl.c : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/nftl/cfg/usrFtl.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory tffs/cfg to $(VSB_DIR)/krnl/configlette




PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrTffs.c

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/configlette/usrTffs.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrTffs.c
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/configlette/usrTffs.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrTffs.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrTffs.c = BDM_FLASH
endif





$(VSB_DIR)/krnl/configlette/usrTffs.c : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/cfg/usrTffs.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/sysTffs.c

__FILES_TO_COPY_BDM_FLASH += $(VSB_DIR)/krnl/configlette/sysTffs.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/sysTffs.c
$(error "while processing layer= BDM_FLASH target $(VSB_DIR)/krnl/configlette/sysTffs.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_sysTffs.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/sysTffs.c = BDM_FLASH
endif





$(VSB_DIR)/krnl/configlette/sysTffs.c : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/tffs/cfg/sysTffs.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



	

	
__DIR_TARGETS += $(__DIR_TARGETS_BDM_FLASH)

__DIR_TARGETS_BDM_FLASH += $(VSB_DIR)/krnl/cdf $(VSB_DIR)/krnl/configlette $(VSB_DIR)/krnl/h/public $(VSB_DIR)/krnl/h/public/alt5qspiflash $(VSB_DIR)/krnl/h/public/fcm $(VSB_DIR)/krnl/h/public/gpmc $(VSB_DIR)/krnl/h/public/gpmi $(VSB_DIR)/krnl/h/public/nand $(VSB_DIR)/krnl/h/public/nfc $(VSB_DIR)/krnl/h/public/norflash $(VSB_DIR)/krnl/h/public/private $(VSB_DIR)/krnl/h/public/rzn1qspiflash $(VSB_DIR)/krnl/h/public/spiflash $(VSB_DIR)/krnl/h/public/tffs C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/cdf C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/configlette C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/share/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/usr/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/vsblCdf

