
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_BDM_SIM)
__FILES_GENERATED += $(__FILES_GENERATED_BDM_SIM)




	
	

	
# copying directory h to $(VSB_DIR)/krnl/h/public




PRENOBUILD : $(VSB_DIR)/krnl/h/public/fsimLib.h

__FILES_TO_COPY_BDM_SIM += $(VSB_DIR)/krnl/h/public/fsimLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/fsimLib.h
$(error "while processing layer= BDM_SIM target $(VSB_DIR)/krnl/h/public/fsimLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public_fsimLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/fsimLib.h = BDM_SIM
endif





 

$(VSB_DIR)/krnl/h/public/fsimLib.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/sim/h/fsimLib.h | $(VSB_DIR)/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory h/private to $(VSB_DIR)/krnl/h/public/private




PRENOBUILD : $(VSB_DIR)/krnl/h/public/private/fsimLibP.h

__FILES_TO_COPY_BDM_SIM += $(VSB_DIR)/krnl/h/public/private/fsimLibP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/fsimLibP.h
$(error "while processing layer= BDM_SIM target $(VSB_DIR)/krnl/h/public/private/fsimLibP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private_fsimLibP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/private/fsimLibP.h = BDM_SIM
endif





 

$(VSB_DIR)/krnl/h/public/private/fsimLibP.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/sim/h/private/fsimLibP.h | $(VSB_DIR)/krnl/h/public/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



	


	
	
	
	
	
	
	
	
	

	

	
	
	
	
	
	
	


	


	


	

	
BUILD : BDM_SIM_src_llvm__BUILD

.PHONY : BDM_SIM_src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_SIM_src_llvm

BDM_SIM_src_llvm__BUILD : 
	@ echo building BUILD layer BDM_SIM directory src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/flash/sim/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM_SIM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_SIM_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD


	

	

	

	

	

	

	


	
	
	
	
	
	

	

	

	
__DIR_TARGETS += $(__DIR_TARGETS_BDM_SIM)

__DIR_TARGETS_BDM_SIM += $(VSB_DIR)/krnl/h/public $(VSB_DIR)/krnl/h/public/private C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/cdf C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/configlette C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/share/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/usr/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/vsblCdf

