
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_ARM)
__FILES_GENERATED += $(__FILES_GENERATED_ARM)




	
	

	
# copying directory kernel/armbase/h to $(VSB_DIR)/krnl/h/public




# copying directory kernel/armbase/h/arch to $(VSB_DIR)/krnl/h/public/arch




# copying directory kernel/armbase/h/arch/arm to $(VSB_DIR)/krnl/h/public/arch/arm




PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/vxInlineArch.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/vxInlineArch.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxInlineArch.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/vxInlineArch.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_vxInlineArch.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxInlineArch.h = ARM
endif





 

$(VSB_DIR)/krnl/h/public/arch/arm/vxInlineArch.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/vxInlineArch.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/dsmArmLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/dsmArmLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/dsmArmLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/dsmArmLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_dsmArmLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/dsmArmLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/dsmArmLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/dsmArmLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/ivArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/ivArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/ivArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/ivArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_ivArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/ivArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/ivArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/ivArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/cacheArmLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/cacheArmLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/cacheArmLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/cacheArmLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_cacheArmLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/cacheArmLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/cacheArmLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/cacheArmLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_vxAtomicArchLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/vxAtomicArchLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/archArmCommon.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/archArmCommon.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/archArmCommon.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/archArmCommon.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_archArmCommon.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/archArmCommon.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/archArmCommon.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/archArmCommon.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLibCommon.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLibCommon.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLibCommon.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLibCommon.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_vxAtomicArchLibCommon.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLibCommon.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/vxAtomicArchLibCommon.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/vxAtomicArchLibCommon.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/_G_configArch.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/_G_configArch.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/_G_configArch.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/_G_configArch.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm__G_configArch.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/_G_configArch.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/_G_configArch.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/_G_configArch.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/fppArmLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/fppArmLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/fppArmLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/fppArmLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_fppArmLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/fppArmLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/fppArmLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/fppArmLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/archArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/archArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/archArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/archArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_archArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/archArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/archArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/archArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/coprocArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/coprocArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/coprocArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/coprocArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_coprocArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/coprocArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/coprocArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/coprocArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory kernel/armbase/h/arch/arm/private to $(VSB_DIR)/krnl/h/public/arch/arm/private




PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/private/adrSpaceArchLibP.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/private/adrSpaceArchLibP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/adrSpaceArchLibP.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/private/adrSpaceArchLibP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private_adrSpaceArchLibP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/adrSpaceArchLibP.h = ARM
endif





 

$(VSB_DIR)/krnl/h/public/arch/arm/private/adrSpaceArchLibP.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/private/adrSpaceArchLibP.h | $(VSB_DIR)/krnl/h/public/arch/arm/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/private/smpArmP.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/private/smpArmP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/smpArmP.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/private/smpArmP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private_smpArmP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/smpArmP.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/private/smpArmP.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/private/smpArmP.h | $(VSB_DIR)/krnl/h/public/arch/arm/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/syscallArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/syscallArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/syscallArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/syscallArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_syscallArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/syscallArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/syscallArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/syscallArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/elfArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/elfArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/elfArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/elfArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_elfArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/elfArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/elfArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/elfArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/vxbAccessArchLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/vxbAccessArchLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxbAccessArchLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/vxbAccessArchLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_vxbAccessArchLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxbAccessArchLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/vxbAccessArchLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/h/arch/arm/vxbAccessArchLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



 
# copying directory kernel/drv/h to $(VSB_DIR)/krnl/h/public




# copying directory kernel/drv/h/arch to $(VSB_DIR)/krnl/h/public/arch




# copying directory kernel/drv/h/arch/arm to $(VSB_DIR)/krnl/h/public/arch/arm




PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/vxbFdtArmGicv3.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/vxbFdtArmGicv3.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxbFdtArmGicv3.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/vxbFdtArmGicv3.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_vxbFdtArmGicv3.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vxbFdtArmGicv3.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/vxbFdtArmGicv3.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/h/arch/arm/vxbFdtArmGicv3.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



 
# copying directory kernel/armv7a/h to $(VSB_DIR)/krnl/h/public




# copying directory kernel/armv7a/h/arch to $(VSB_DIR)/krnl/h/public/arch




# copying directory kernel/armv7a/h/arch/arm to $(VSB_DIR)/krnl/h/public/arch/arm




PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/excArmLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/excArmLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/excArmLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/excArmLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_excArmLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/excArmLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/excArmLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/excArmLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_mmuArmLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/mmuArmLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/esfArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/esfArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/esfArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/esfArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_esfArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/esfArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/esfArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/esfArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/secArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/secArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/secArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/secArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_secArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/secArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/secArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/secArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/smcArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/smcArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/smcArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/smcArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_smcArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/smcArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/smcArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/smcArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/regsArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/regsArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/regsArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/regsArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_regsArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/regsArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/regsArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/regsArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/asmArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/asmArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/asmArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/asmArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_asmArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/asmArm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/asmArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/asmArm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/vfpArmLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/vfpArmLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vfpArmLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/vfpArmLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_vfpArmLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/vfpArmLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/vfpArmLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/vfpArmLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/intArmLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/intArmLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/intArmLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/intArmLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_intArmLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/intArmLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/intArmLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/intArmLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch7.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch7.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch7.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch7.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_cacheArmArch7.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch7.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch7.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/cacheArmArch7.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory kernel/armv7a/h/arch/arm/private to $(VSB_DIR)/krnl/h/public/arch/arm/private




PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/private/windArchLibP.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/private/windArchLibP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/windArchLibP.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/private/windArchLibP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private_windArchLibP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/windArchLibP.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/private/windArchLibP.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/private/windArchLibP.h | $(VSB_DIR)/krnl/h/public/arch/arm/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/private/taskArchLibP.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/private/taskArchLibP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/taskArchLibP.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/private/taskArchLibP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private_taskArchLibP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/taskArchLibP.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/private/taskArchLibP.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/private/taskArchLibP.h | $(VSB_DIR)/krnl/h/public/arch/arm/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/private/vxdbgArmLibP.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/private/vxdbgArmLibP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/vxdbgArmLibP.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/private/vxdbgArmLibP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private_vxdbgArmLibP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/vxdbgArmLibP.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/private/vxdbgArmLibP.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/private/vxdbgArmLibP.h | $(VSB_DIR)/krnl/h/public/arch/arm/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/private/vxPortableArchP.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/private/vxPortableArchP.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/vxPortableArchP.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/private/vxPortableArchP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private_vxPortableArchP.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/private/vxPortableArchP.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/private/vxPortableArchP.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/private/vxPortableArchP.h | $(VSB_DIR)/krnl/h/public/arch/arm/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLpaeLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLpaeLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLpaeLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLpaeLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_mmuArmLpaeLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLpaeLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/mmuArmLpaeLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/mmuArmLpaeLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/mpuArmLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/mpuArmLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/mpuArmLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/mpuArmLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_mpuArmLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/mpuArmLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/mpuArmLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/mpuArmLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/arm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/arm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/arm.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/arm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_arm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/arm.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/arm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/arm.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/dbgArmLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/dbgArmLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/dbgArmLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/dbgArmLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_dbgArmLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/dbgArmLib.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/dbgArmLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/dbgArmLib.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch.h
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm_cacheArmArch.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch.h = ARM
endif





$(VSB_DIR)/krnl/h/public/arch/arm/cacheArmArch.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/h/arch/arm/cacheArmArch.h | $(VSB_DIR)/krnl/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif




	


	
	
	
	
	
	
	
	
	

	
# copying directory user/h to $(VSB_DIR)/usr/h/public




# copying directory user/h/arch to $(VSB_DIR)/usr/h/public/arch




# copying directory user/h/arch/arm to $(VSB_DIR)/usr/h/public/arch/arm




PRENOBUILD : $(VSB_DIR)/usr/h/public/arch/arm/vxAtomicArchLib.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/usr/h/public/arch/arm/vxAtomicArchLib.h

ifdef __TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/vxAtomicArchLib.h
$(error "while processing layer= ARM target $(VSB_DIR)/usr/h/public/arch/arm/vxAtomicArchLib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm_vxAtomicArchLib.h)")
else
__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/vxAtomicArchLib.h = ARM
endif





 

$(VSB_DIR)/usr/h/public/arch/arm/vxAtomicArchLib.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/h/arch/arm/vxAtomicArchLib.h | $(VSB_DIR)/usr/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/usr/h/public/arch/arm/archArmCommon.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/usr/h/public/arch/arm/archArmCommon.h

ifdef __TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/archArmCommon.h
$(error "while processing layer= ARM target $(VSB_DIR)/usr/h/public/arch/arm/archArmCommon.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm_archArmCommon.h)")
else
__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/archArmCommon.h = ARM
endif





$(VSB_DIR)/usr/h/public/arch/arm/archArmCommon.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/h/arch/arm/archArmCommon.h | $(VSB_DIR)/usr/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/usr/h/public/arch/arm/regsArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/usr/h/public/arch/arm/regsArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/regsArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/usr/h/public/arch/arm/regsArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm_regsArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/regsArm.h = ARM
endif





$(VSB_DIR)/usr/h/public/arch/arm/regsArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/h/arch/arm/regsArm.h | $(VSB_DIR)/usr/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/usr/h/public/arch/arm/asmArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/usr/h/public/arch/arm/asmArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/asmArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/usr/h/public/arch/arm/asmArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm_asmArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/asmArm.h = ARM
endif





$(VSB_DIR)/usr/h/public/arch/arm/asmArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/h/arch/arm/asmArm.h | $(VSB_DIR)/usr/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/usr/h/public/arch/arm/archArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/usr/h/public/arch/arm/archArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/archArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/usr/h/public/arch/arm/archArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm_archArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/archArm.h = ARM
endif





$(VSB_DIR)/usr/h/public/arch/arm/archArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/h/arch/arm/archArm.h | $(VSB_DIR)/usr/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/usr/h/public/arch/arm/coprocArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/usr/h/public/arch/arm/coprocArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/coprocArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/usr/h/public/arch/arm/coprocArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm_coprocArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/coprocArm.h = ARM
endif





$(VSB_DIR)/usr/h/public/arch/arm/coprocArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/h/arch/arm/coprocArm.h | $(VSB_DIR)/usr/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory user/h/arch/arm/private to $(VSB_DIR)/usr/h/public/arch/arm/private




PRENOBUILD : $(VSB_DIR)/usr/h/public/arch/arm/private/vxPortableArchP.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/usr/h/public/arch/arm/private/vxPortableArchP.h

ifdef __TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/private/vxPortableArchP.h
$(error "while processing layer= ARM target $(VSB_DIR)/usr/h/public/arch/arm/private/vxPortableArchP.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/private_vxPortableArchP.h)")
else
__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/private/vxPortableArchP.h = ARM
endif





 

$(VSB_DIR)/usr/h/public/arch/arm/private/vxPortableArchP.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/h/arch/arm/private/vxPortableArchP.h | $(VSB_DIR)/usr/h/public/arch/arm/private
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : $(VSB_DIR)/usr/h/public/arch/arm/elfArm.h

__FILES_TO_COPY_ARM += $(VSB_DIR)/usr/h/public/arch/arm/elfArm.h

ifdef __TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/elfArm.h
$(error "while processing layer= ARM target $(VSB_DIR)/usr/h/public/arch/arm/elfArm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm_elfArm.h)")
else
__TARGET_RULE_$(VSB_DIR)/usr/h/public/arch/arm/elfArm.h = ARM
endif





$(VSB_DIR)/usr/h/public/arch/arm/elfArm.h : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/h/arch/arm/elfArm.h | $(VSB_DIR)/usr/h/public/arch/arm
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif





	
	
	
	
	
	
	


	


	


	

	
BUILD : ARM_kernel/armbase/src_llvm__BUILD

.PHONY : ARM_kernel/armbase/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_ARM_kernel_armbase_src_llvm

ARM_kernel/armbase/src_llvm__BUILD : 
	@ echo building BUILD layer ARM directory kernel/armbase/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH_SYS __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=ARM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_ARM_kernel_armbase_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : ARM_kernel/drv/src_llvm__BUILD

.PHONY : ARM_kernel/drv/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_ARM_kernel_drv_src_llvm

ARM_kernel/drv/src_llvm__BUILD : 
	@ echo building BUILD layer ARM directory kernel/drv/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH_SYS __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=ARM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_ARM_kernel_drv_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD
 
BUILD : ARM_kernel/armv7a/src_llvm__BUILD

.PHONY : ARM_kernel/armv7a/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_ARM_kernel_armv7a_src_llvm

ARM_kernel/armv7a/src_llvm__BUILD : 
	@ echo building BUILD layer ARM directory kernel/armv7a/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH_SYS __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=ARM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_ARM_kernel_armv7a_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD


	
BUILD_USR_STATIC : ARM_kernel/armbase/src_llvm__BUILD_USR_STATIC

.PHONY : ARM_kernel/armbase/src_llvm__BUILD_USR_STATIC

__BUILD_USR_STATIC_FB_IDS += user_static_top_ARM_kernel_armbase_src_llvm

ARM_kernel/armbase/src_llvm__BUILD_USR_STATIC : 
	@ echo building BUILD_USR_STATIC layer ARM directory kernel/armbase/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=user __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH_SYS __LAYER_C++_WARNINGS= LAYER_FORMAT=static _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=ARM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=user_static_top_ARM_kernel_armbase_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD_USR_STATIC
 
BUILD_USR_STATIC : ARM_user/src_llvm__BUILD_USR_STATIC

.PHONY : ARM_user/src_llvm__BUILD_USR_STATIC

__BUILD_USR_STATIC_FB_IDS += user_static_top_ARM_user_src_llvm

ARM_user/src_llvm__BUILD_USR_STATIC : 
	@ echo building BUILD_USR_STATIC layer ARM directory user/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=user __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH_SYS __LAYER_C++_WARNINGS= LAYER_FORMAT=static _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=ARM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=user_static_top_ARM_user_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD_USR_STATIC


	
BUILD_USR_SHARED : ARM_kernel/armbase/src_llvm__BUILD_USR_SHARED

.PHONY : ARM_kernel/armbase/src_llvm__BUILD_USR_SHARED

__BUILD_USR_SHARED_FB_IDS += user_shared_top_ARM_kernel_armbase_src_llvm

ARM_kernel/armbase/src_llvm__BUILD_USR_SHARED : 
	@ echo building BUILD_USR_SHARED layer ARM directory kernel/armbase/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=user __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH_SYS __LAYER_C++_WARNINGS= LAYER_FORMAT=shared _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=ARM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=user_shared_top_ARM_kernel_armbase_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD_USR_SHARED
 
BUILD_USR_SHARED : ARM_user/src_llvm__BUILD_USR_SHARED

.PHONY : ARM_user/src_llvm__BUILD_USR_SHARED

__BUILD_USR_SHARED_FB_IDS += user_shared_top_ARM_user_src_llvm

ARM_user/src_llvm__BUILD_USR_SHARED : 
	@ echo building BUILD_USR_SHARED layer ARM directory user/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/user/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=user __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH_SYS __LAYER_C++_WARNINGS= LAYER_FORMAT=shared _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=ARM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=user_shared_top_ARM_user_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD_USR_SHARED


	

	

	

	

	


	
# copying directory kernel/armbase/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/arch.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/arch.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/arch.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/arch.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_arch.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/arch.cdf = ARM
endif





 

$(VSB_DIR)/krnl/cdf/arch.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/cdf/arch.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/20vxWorks.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/20vxWorks.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/20vxWorks.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/20vxWorks.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_20vxWorks.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/20vxWorks.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/20vxWorks.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/cdf/20vxWorks.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/41fdt.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/41fdt.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/41fdt.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/41fdt.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_41fdt.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/41fdt.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/41fdt.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/cdf/41fdt.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/21shell.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/21shell.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/21shell.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/21shell.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_21shell.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/21shell.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/21shell.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/cdf/21shell.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/20bsp.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/20bsp.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/20bsp.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/20bsp.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_20bsp.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/20bsp.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/20bsp.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/cdf/20bsp.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory kernel/drv/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtPl310L2Cache.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtPl310L2Cache.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtPl310L2Cache.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtPl310L2Cache.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtPl310L2Cache.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtPl310L2Cache.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtPl310L2Cache.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtPl310L2Cache.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtArmGenIntCtlrv3.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtArmGenIntCtlrv3.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenTimer.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenTimer.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenTimer.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenTimer.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtArmGenTimer.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenTimer.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenTimer.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtArmGenTimer.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtPl330Dma.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtPl330Dma.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtPl330Dma.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtPl330Dma.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtPl330Dma.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtPl330Dma.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtPl330Dma.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtPl330Dma.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtArmGlobalTimer.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtArmGlobalTimer.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGlobalTimer.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtArmGlobalTimer.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtArmGlobalTimer.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGlobalTimer.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtArmGlobalTimer.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtArmGlobalTimer.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtKinetisCache.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtKinetisCache.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtKinetisCache.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtKinetisCache.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtKinetisCache.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtKinetisCache.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtKinetisCache.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtKinetisCache.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3Its.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3Its.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3Its.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3Its.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtArmGenIntCtlrv3Its.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3Its.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlrv3Its.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtArmGenIntCtlrv3Its.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtCortexMSysTick.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtCortexMSysTick.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtCortexMSysTick.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtCortexMSysTick.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtCortexMSysTick.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtCortexMSysTick.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtCortexMSysTick.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtCortexMSysTick.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlr.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlr.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlr.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlr.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtArmGenIntCtlr.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlr.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtArmGenIntCtlr.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtArmGenIntCtlr.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtCCN50xL3Cache.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtCCN50xL3Cache.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtCCN50xL3Cache.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtCCN50xL3Cache.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtCCN50xL3Cache.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtCCN50xL3Cache.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtCCN50xL3Cache.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtCCN50xL3Cache.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtArmNvic.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtArmNvic.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmNvic.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtArmNvic.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtArmNvic.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmNvic.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtArmNvic.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtArmNvic.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/40vxbFdtArmMpCoreTimer.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/40vxbFdtArmMpCoreTimer.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmMpCoreTimer.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/40vxbFdtArmMpCoreTimer.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_40vxbFdtArmMpCoreTimer.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/40vxbFdtArmMpCoreTimer.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/40vxbFdtArmMpCoreTimer.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/cdf/40vxbFdtArmMpCoreTimer.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory kernel/armv7a/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/30arch.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/30arch.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/30arch.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/30arch.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_30arch.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/30arch.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/30arch.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/cdf/30arch.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/30bsp.cdf

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/cdf/30bsp.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/30bsp.cdf
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/cdf/30bsp.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_30bsp.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/30bsp.cdf = ARM
endif





$(VSB_DIR)/krnl/cdf/30bsp.cdf : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/cdf/30bsp.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	# PRENOBUILD=(PRENOBUILD) ARM=(layer) kernel_armbase_cdf=(dir)

PRENOBUILD_ARM_kernel_armbase_cdf_FILES = kernel/armbase/cdf/arch.cdf kernel/armbase/cdf/20vxWorks.cdf kernel/armbase/cdf/41fdt.cdf kernel/armbase/cdf/21shell.cdf kernel/armbase/cdf/20bsp.cdf

PRENOBUILD_ARM_kernel_armbase_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/arch/arm

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_ARM_kernel_armbase_cdf_DIR)/,$(PRENOBUILD_ARM_kernel_armbase_cdf_FILES))

PRENOBUILD : PRENOBUILD_ARM

PRENOBUILD_ARM : kernel/armbase/cdf_PRENOBUILD_ARM

kernel/armbase/cdf_PRENOBUILD_ARM : $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armbase_cdf.cdf

__FILES_TO_GENERATE_ARM += $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armbase_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armbase_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armbase_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armbase_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_ARM_kernel_armbase_cdf_DIR)/,$(sort $(PRENOBUILD_ARM_kernel_armbase_cdf_FILES))),ARM))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armbase_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer ARM -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armbase_cdf.tmp
 # PRENOBUILD=(PRENOBUILD) ARM=(layer) kernel_drv_cdf=(dir)

PRENOBUILD_ARM_kernel_drv_cdf_FILES = kernel/drv/cdf/40vxbFdtPl310L2Cache.cdf kernel/drv/cdf/40vxbFdtArmGenIntCtlrv3.cdf kernel/drv/cdf/40vxbFdtArmGenTimer.cdf kernel/drv/cdf/40vxbFdtPl330Dma.cdf kernel/drv/cdf/40vxbFdtArmGlobalTimer.cdf kernel/drv/cdf/40vxbFdtKinetisCache.cdf kernel/drv/cdf/40vxbFdtArmGenIntCtlrv3Its.cdf kernel/drv/cdf/40vxbFdtCortexMSysTick.cdf kernel/drv/cdf/40vxbFdtArmGenIntCtlr.cdf kernel/drv/cdf/40vxbFdtCCN50xL3Cache.cdf kernel/drv/cdf/40vxbFdtArmNvic.cdf kernel/drv/cdf/40vxbFdtArmMpCoreTimer.cdf

PRENOBUILD_ARM_kernel_drv_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/arch/arm

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_ARM_kernel_drv_cdf_DIR)/,$(PRENOBUILD_ARM_kernel_drv_cdf_FILES))

PRENOBUILD : PRENOBUILD_ARM

PRENOBUILD_ARM : kernel/drv/cdf_PRENOBUILD_ARM

kernel/drv/cdf_PRENOBUILD_ARM : $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_drv_cdf.cdf

__FILES_TO_GENERATE_ARM += $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_drv_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_drv_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_drv_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_drv_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_ARM_kernel_drv_cdf_DIR)/,$(sort $(PRENOBUILD_ARM_kernel_drv_cdf_FILES))),ARM))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_drv_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer ARM -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_drv_cdf.tmp
 # PRENOBUILD=(PRENOBUILD) ARM=(layer) kernel_armv7a_cdf=(dir)

PRENOBUILD_ARM_kernel_armv7a_cdf_FILES = kernel/armv7a/cdf/30arch.cdf kernel/armv7a/cdf/30bsp.cdf

PRENOBUILD_ARM_kernel_armv7a_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/arch/arm

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_ARM_kernel_armv7a_cdf_DIR)/,$(PRENOBUILD_ARM_kernel_armv7a_cdf_FILES))

PRENOBUILD : PRENOBUILD_ARM

PRENOBUILD_ARM : kernel/armv7a/cdf_PRENOBUILD_ARM

kernel/armv7a/cdf_PRENOBUILD_ARM : $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armv7a_cdf.cdf

__FILES_TO_GENERATE_ARM += $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armv7a_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armv7a_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armv7a_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armv7a_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_ARM_kernel_armv7a_cdf_DIR)/,$(sort $(PRENOBUILD_ARM_kernel_armv7a_cdf_FILES))),ARM))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armv7a_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer ARM -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_ARM_kernel_armv7a_cdf.tmp

	
	
	
	

	
# copying directory kernel/armbase/configlette to $(VSB_DIR)/krnl/configlette




PRENOBUILD : $(VSB_DIR)/krnl/configlette/memLayoutCheck.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/memLayoutCheck.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/memLayoutCheck.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/memLayoutCheck.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_memLayoutCheck.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/memLayoutCheck.c = ARM
endif





 

$(VSB_DIR)/krnl/configlette/memLayoutCheck.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/configlette/memLayoutCheck.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrCpuArch.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/usrCpuArch.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrCpuArch.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/usrCpuArch.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrCpuArch.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrCpuArch.c = ARM
endif





$(VSB_DIR)/krnl/configlette/usrCpuArch.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/configlette/usrCpuArch.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrAdjustDtb.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/usrAdjustDtb.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrAdjustDtb.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/usrAdjustDtb.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrAdjustDtb.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrAdjustDtb.c = ARM
endif





$(VSB_DIR)/krnl/configlette/usrAdjustDtb.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/configlette/usrAdjustDtb.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/armMonitorStub.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/armMonitorStub.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/armMonitorStub.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/armMonitorStub.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_armMonitorStub.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/armMonitorStub.c = ARM
endif





$(VSB_DIR)/krnl/configlette/armMonitorStub.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/configlette/armMonitorStub.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrOsm.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/usrOsm.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrOsm.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/usrOsm.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrOsm.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrOsm.c = ARM
endif





$(VSB_DIR)/krnl/configlette/usrOsm.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armbase/configlette/usrOsm.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory kernel/drv/configlette to $(VSB_DIR)/krnl/configlette




PRENOBUILD : $(VSB_DIR)/krnl/configlette/armGenTimerCfg.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/armGenTimerCfg.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/armGenTimerCfg.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/armGenTimerCfg.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_armGenTimerCfg.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/armGenTimerCfg.c = ARM
endif





$(VSB_DIR)/krnl/configlette/armGenTimerCfg.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/configlette/armGenTimerCfg.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/pl310Access.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/pl310Access.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/pl310Access.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/pl310Access.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_pl310Access.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/pl310Access.c = ARM
endif





$(VSB_DIR)/krnl/configlette/pl310Access.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/configlette/pl310Access.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/armGicCfg.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/armGicCfg.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/armGicCfg.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/armGicCfg.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_armGicCfg.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/armGicCfg.c = ARM
endif





$(VSB_DIR)/krnl/configlette/armGicCfg.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/drv/configlette/armGicCfg.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory kernel/armv7a/configlette to $(VSB_DIR)/krnl/configlette




PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrCoprocArm.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/usrCoprocArm.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrCoprocArm.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/usrCoprocArm.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrCoprocArm.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrCoprocArm.c = ARM
endif





$(VSB_DIR)/krnl/configlette/usrCoprocArm.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/configlette/usrCoprocArm.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrSmcProtocol.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/usrSmcProtocol.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrSmcProtocol.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/usrSmcProtocol.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrSmcProtocol.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrSmcProtocol.c = ARM
endif





$(VSB_DIR)/krnl/configlette/usrSmcProtocol.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/configlette/usrSmcProtocol.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrMmuArchInit.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/usrMmuArchInit.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrMmuArchInit.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/usrMmuArchInit.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrMmuArchInit.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrMmuArchInit.c = ARM
endif





$(VSB_DIR)/krnl/configlette/usrMmuArchInit.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/configlette/usrMmuArchInit.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/configlette/usrSecureConfig.c

__FILES_TO_COPY_ARM += $(VSB_DIR)/krnl/configlette/usrSecureConfig.c

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrSecureConfig.c
$(error "while processing layer= ARM target $(VSB_DIR)/krnl/configlette/usrSecureConfig.c already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/configlette_usrSecureConfig.c)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/configlette/usrSecureConfig.c = ARM
endif





$(VSB_DIR)/krnl/configlette/usrSecureConfig.c : C:/WindRiver2021-07/vxworks/21.07/os/arch/arm/kernel/armv7a/configlette/usrSecureConfig.c | $(VSB_DIR)/krnl/configlette
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif



	

	
__DIR_TARGETS += $(__DIR_TARGETS_ARM)

__DIR_TARGETS_ARM += $(VSB_DIR)/krnl/cdf $(VSB_DIR)/krnl/configlette $(VSB_DIR)/krnl/h/public/arch/arm $(VSB_DIR)/krnl/h/public/arch/arm/private $(VSB_DIR)/usr/h/public/arch/arm $(VSB_DIR)/usr/h/public/arch/arm/private C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/cdf C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/configlette C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/share/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/usr/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/vsblCdf

