
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_ACPI)
__FILES_GENERATED += $(__FILES_GENERATED_ACPI)




	
	

	
# copying directory src/acpica-unix-20170303/source/acpi to $(VSB_DIR)/krnl/h/public/acpi




PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acutils.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acutils.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acutils.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acutils.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acutils.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acutils.h = ACPI
endif





 

$(VSB_DIR)/krnl/h/public/acpi/acutils.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acutils.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acapps.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acapps.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acapps.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acapps.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acapps.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acapps.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acapps.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acapps.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/accommon.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/accommon.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/accommon.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/accommon.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_accommon.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/accommon.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/accommon.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/accommon.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acconfig.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acconfig.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acconfig.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acconfig.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acconfig.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acconfig.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acconfig.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acconfig.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acopcode.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acopcode.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acopcode.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acopcode.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acopcode.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acopcode.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acopcode.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acopcode.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acrestyp.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acrestyp.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acrestyp.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acrestyp.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acrestyp.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acrestyp.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acrestyp.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acrestyp.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/actbl3.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/actbl3.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actbl3.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/actbl3.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_actbl3.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actbl3.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/actbl3.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/actbl3.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/actbl2.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/actbl2.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actbl2.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/actbl2.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_actbl2.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actbl2.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/actbl2.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/actbl2.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
# copying directory src/acpica-unix-20170303/source/acpi/platform to $(VSB_DIR)/krnl/h/public/acpi/platform




PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/accygwin.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/accygwin.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/accygwin.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/accygwin.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_accygwin.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/accygwin.h = ACPI
endif





 

$(VSB_DIR)/krnl/h/public/acpi/platform/accygwin.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/accygwin.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acnetbsd.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acnetbsd.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acnetbsd.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acnetbsd.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acnetbsd.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acnetbsd.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acnetbsd.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acnetbsd.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acefi.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acefi.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acefi.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acefi.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acefi.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acefi.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acefi.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acefi.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acdragonfly.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acdragonfly.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acdragonfly.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acdragonfly.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acdragonfly.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acdragonfly.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acdragonfly.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acdragonfly.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acos2.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acos2.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acos2.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acos2.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acos2.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acos2.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acos2.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acos2.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/achaiku.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/achaiku.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/achaiku.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/achaiku.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_achaiku.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/achaiku.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/achaiku.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/achaiku.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acgccex.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acgccex.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acgccex.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acgccex.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acgccex.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acgccex.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acgccex.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acgccex.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acintel.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acintel.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acintel.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acintel.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acintel.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acintel.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acintel.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acintel.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acmsvcex.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acmsvcex.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acmsvcex.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acmsvcex.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acmsvcex.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acmsvcex.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acmsvcex.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acmsvcex.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acefiex.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acefiex.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acefiex.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acefiex.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acefiex.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acefiex.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acefiex.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acefiex.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/aclinuxex.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/aclinuxex.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/aclinuxex.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/aclinuxex.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_aclinuxex.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/aclinuxex.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/aclinuxex.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/aclinuxex.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acdragonflyex.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acdragonflyex.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acdragonflyex.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acdragonflyex.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acdragonflyex.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acdragonflyex.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acdragonflyex.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acdragonflyex.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acqnx.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acqnx.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acqnx.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acqnx.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acqnx.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acqnx.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acqnx.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acqnx.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acgcc.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acgcc.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acgcc.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acgcc.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acgcc.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acgcc.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acgcc.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acgcc.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acmsvc.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acmsvc.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acmsvc.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acmsvc.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acmsvc.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acmsvc.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acmsvc.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acmsvc.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acmacosx.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acmacosx.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acmacosx.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acmacosx.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acmacosx.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acmacosx.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acmacosx.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acmacosx.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/aclinux.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/aclinux.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/aclinux.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/aclinux.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_aclinux.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/aclinux.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/aclinux.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/aclinux.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acenv.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acenv.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acenv.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acenv.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acenv.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acenv.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acenv.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acenv.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acwin.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acwin.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acwin.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acwin.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acwin.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acwin.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acwin.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acwin.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acenvex.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acenvex.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acenvex.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acenvex.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acenvex.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acenvex.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acenvex.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acenvex.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acfreebsd.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acfreebsd.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acfreebsd.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acfreebsd.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acfreebsd.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acfreebsd.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acfreebsd.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acfreebsd.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/platform/acwin64.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/platform/acwin64.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acwin64.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/platform/acwin64.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform_acwin64.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/platform/acwin64.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/platform/acwin64.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/platform/acwin64.h | $(VSB_DIR)/krnl/h/public/acpi/platform
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acnames.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acnames.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acnames.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acnames.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acnames.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acnames.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acnames.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acnames.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acpiosxf.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acpiosxf.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acpiosxf.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acpiosxf.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acpiosxf.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acpiosxf.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acpiosxf.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acpiosxf.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acuuid.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acuuid.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acuuid.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acuuid.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acuuid.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acuuid.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acuuid.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acuuid.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acnamesp.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acnamesp.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acnamesp.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acnamesp.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acnamesp.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acnamesp.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acnamesp.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acnamesp.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acpixf.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acpixf.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acpixf.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acpixf.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acpixf.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acpixf.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acpixf.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acpixf.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acstruct.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acstruct.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acstruct.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acstruct.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acstruct.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acstruct.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acstruct.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acstruct.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/achware.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/achware.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/achware.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/achware.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_achware.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/achware.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/achware.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/achware.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acclib.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acclib.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acclib.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acclib.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acclib.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acclib.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acclib.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acclib.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/actbl.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/actbl.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actbl.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/actbl.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_actbl.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actbl.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/actbl.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/actbl.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/actables.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/actables.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actables.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/actables.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_actables.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actables.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/actables.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/actables.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/amlcode.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/amlcode.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/amlcode.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/amlcode.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_amlcode.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/amlcode.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/amlcode.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/amlcode.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acparser.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acparser.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acparser.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acparser.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acparser.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acparser.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acparser.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acparser.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acresrc.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acresrc.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acresrc.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acresrc.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acresrc.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acresrc.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acresrc.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acresrc.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/actypes.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/actypes.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actypes.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/actypes.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_actypes.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actypes.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/actypes.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/actypes.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acobject.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acobject.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acobject.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acobject.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acobject.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acobject.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acobject.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acobject.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/actbl1.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/actbl1.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actbl1.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/actbl1.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_actbl1.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/actbl1.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/actbl1.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/actbl1.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acdispat.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acdispat.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acdispat.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acdispat.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acdispat.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acdispat.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acdispat.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acdispat.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acevents.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acevents.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acevents.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acevents.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acevents.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acevents.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acevents.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acevents.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acbuffer.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acbuffer.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acbuffer.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acbuffer.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acbuffer.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acbuffer.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acbuffer.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acbuffer.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acpi.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acpi.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acpi.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acpi.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acpi.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acpi.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acpi.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acpi.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acexcep.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acexcep.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acexcep.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acexcep.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acexcep.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acexcep.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acexcep.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acexcep.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acdisasm.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acdisasm.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acdisasm.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acdisasm.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acdisasm.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acdisasm.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acdisasm.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acdisasm.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/amlresrc.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/amlresrc.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/amlresrc.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/amlresrc.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_amlresrc.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/amlresrc.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/amlresrc.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/amlresrc.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acinterp.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acinterp.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acinterp.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acinterp.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acinterp.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acinterp.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acinterp.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acinterp.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acpredef.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acpredef.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acpredef.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acpredef.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acpredef.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acpredef.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acpredef.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acpredef.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acoutput.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acoutput.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acoutput.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acoutput.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acoutput.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acoutput.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acoutput.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acoutput.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/aclocal.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/aclocal.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/aclocal.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/aclocal.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_aclocal.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/aclocal.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/aclocal.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/aclocal.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acglobal.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acglobal.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acglobal.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acglobal.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acglobal.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acglobal.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acglobal.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acglobal.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acdebug.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acdebug.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acdebug.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acdebug.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acdebug.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acdebug.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acdebug.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acdebug.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acmacros.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acmacros.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acmacros.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acmacros.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acmacros.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acmacros.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acmacros.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acmacros.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/acpi/acconvert.h

__FILES_TO_COPY_ACPI += $(VSB_DIR)/krnl/h/public/acpi/acconvert.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acconvert.h
$(error "while processing layer= ACPI target $(VSB_DIR)/krnl/h/public/acpi/acconvert.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi_acconvert.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/acpi/acconvert.h = ACPI
endif





$(VSB_DIR)/krnl/h/public/acpi/acconvert.h : C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src/acpica-unix-20170303/source/acpi/acconvert.h | $(VSB_DIR)/krnl/h/public/acpi
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	


	
	
	
	
	
	
	
	
	

	

	
	
	
	
	
	
	


	


	


	

	
BUILD : ACPI_src_llvm__BUILD

.PHONY : ACPI_src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_ACPI_src_llvm

ACPI_src_llvm__BUILD : 
	@ echo building BUILD layer ACPI directory src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/firmware/acpi/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS= __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=ACPI VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_ACPI_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD


	

	

	

	

	

	

	


	
	
	
	
	
	

	

	

	
__DIR_TARGETS += $(__DIR_TARGETS_ACPI)

__DIR_TARGETS_ACPI += $(VSB_DIR)/krnl/h/public/acpi $(VSB_DIR)/krnl/h/public/acpi/platform C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/cdf C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/configlette C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/share/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/usr/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/vsblCdf

