
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_BDM)
__FILES_GENERATED += $(__FILES_GENERATED_BDM)




	
	

	
# copying directory xbd/h to $(VSB_DIR)/krnl/h/public




# copying directory xbd/h/drv to $(VSB_DIR)/krnl/h/public/drv




# copying directory xbd/h/drv/manager to $(VSB_DIR)/krnl/h/public/drv/manager




PRENOBUILD : $(VSB_DIR)/krnl/h/public/drv/manager/device.h

__FILES_TO_COPY_BDM += $(VSB_DIR)/krnl/h/public/drv/manager/device.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/manager/device.h
$(error "while processing layer= BDM target $(VSB_DIR)/krnl/h/public/drv/manager/device.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/manager_device.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/manager/device.h = BDM
endif





 

$(VSB_DIR)/krnl/h/public/drv/manager/device.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/xbd/h/drv/manager/device.h | $(VSB_DIR)/krnl/h/public/drv/manager
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif

 
# copying directory xbd/h/drv/xbd to $(VSB_DIR)/krnl/h/public/drv/xbd




PRENOBUILD : $(VSB_DIR)/krnl/h/public/drv/xbd/xbdRequestCache.h

__FILES_TO_COPY_BDM += $(VSB_DIR)/krnl/h/public/drv/xbd/xbdRequestCache.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/xbd/xbdRequestCache.h
$(error "while processing layer= BDM target $(VSB_DIR)/krnl/h/public/drv/xbd/xbdRequestCache.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/xbd_xbdRequestCache.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/xbd/xbdRequestCache.h = BDM
endif





 

$(VSB_DIR)/krnl/h/public/drv/xbd/xbdRequestCache.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/xbd/h/drv/xbd/xbdRequestCache.h | $(VSB_DIR)/krnl/h/public/drv/xbd
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/drv/xbd/bio.h

__FILES_TO_COPY_BDM += $(VSB_DIR)/krnl/h/public/drv/xbd/bio.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/xbd/bio.h
$(error "while processing layer= BDM target $(VSB_DIR)/krnl/h/public/drv/xbd/bio.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/xbd_bio.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/xbd/bio.h = BDM
endif





$(VSB_DIR)/krnl/h/public/drv/xbd/bio.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/xbd/h/drv/xbd/bio.h | $(VSB_DIR)/krnl/h/public/drv/xbd
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/h/public/drv/xbd/xbd.h

__FILES_TO_COPY_BDM += $(VSB_DIR)/krnl/h/public/drv/xbd/xbd.h

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/xbd/xbd.h
$(error "while processing layer= BDM target $(VSB_DIR)/krnl/h/public/drv/xbd/xbd.h already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/xbd_xbd.h)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/h/public/drv/xbd/xbd.h = BDM
endif





$(VSB_DIR)/krnl/h/public/drv/xbd/xbd.h : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/xbd/h/drv/xbd/xbd.h | $(VSB_DIR)/krnl/h/public/drv/xbd
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif




	


	
	
	
	
	
	
	
	
	

	

	
	
	
	
	
	
	


	


	


	

	
BUILD : BDM_xbd/src_llvm__BUILD

.PHONY : BDM_xbd/src_llvm__BUILD

__BUILD_FB_IDS += kernel_top_BDM_xbd_src_llvm

BDM_xbd/src_llvm__BUILD : 
	@ echo building BUILD layer BDM directory xbd/src
	+ @ cd C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/xbd/src && C:/WindRiver2021-07/vxworks/21.07/host/x86-win64/bin/make _mk CPU=ARMARCH7 TOOL=llvm TOOL_VERSION=llvm_2016_04 _CC_VERSION=llvm_11_1_0_1 SPACE=kernel __LAYER_CC_WARNINGS=CC_WARNINGS_HIGH __LAYER_C++_WARNINGS= _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=llvm VSBL_NAME=BDM VSB_DIR=$(VSB_DIR) _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_BDM_xbd_src_llvm BSPNAME=ti_sitara_ctxa15_branson_2_1_0_0 BUILDSTAGE=BUILD


	

	

	

	

	

	

	


	
# copying directory xbd/cdf to $(VSB_DIR)/krnl/cdf




PRENOBUILD : $(VSB_DIR)/krnl/cdf/01comp_device_manager.cdf

__FILES_TO_COPY_BDM += $(VSB_DIR)/krnl/cdf/01comp_device_manager.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/01comp_device_manager.cdf
$(error "while processing layer= BDM target $(VSB_DIR)/krnl/cdf/01comp_device_manager.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_01comp_device_manager.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/01comp_device_manager.cdf = BDM
endif





 

$(VSB_DIR)/krnl/cdf/01comp_device_manager.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/xbd/cdf/01comp_device_manager.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif
 
PRENOBUILD : $(VSB_DIR)/krnl/cdf/01comp_xbd.cdf

__FILES_TO_COPY_BDM += $(VSB_DIR)/krnl/cdf/01comp_xbd.cdf

ifdef __TARGET_RULE_$(VSB_DIR)/krnl/cdf/01comp_xbd.cdf
$(error "while processing layer= BDM target $(VSB_DIR)/krnl/cdf/01comp_xbd.cdf already defined by layer $(__TARGET_RULE_$(VSB_DIR)/krnl/cdf_01comp_xbd.cdf)")
else
__TARGET_RULE_$(VSB_DIR)/krnl/cdf/01comp_xbd.cdf = BDM
endif





$(VSB_DIR)/krnl/cdf/01comp_xbd.cdf : C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm/xbd/cdf/01comp_xbd.cdf | $(VSB_DIR)/krnl/cdf
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif


	# PRENOBUILD=(PRENOBUILD) BDM=(layer) xbd_cdf=(dir)

PRENOBUILD_BDM_xbd_cdf_FILES = xbd/cdf/01comp_device_manager.cdf xbd/cdf/01comp_xbd.cdf

PRENOBUILD_BDM_xbd_cdf_DIR = C:/WindRiver2021-07/vxworks/21.07/os/storage/bdm

PRENOBUILD_FILES += $(addprefix $(PRENOBUILD_BDM_xbd_cdf_DIR)/,$(PRENOBUILD_BDM_xbd_cdf_FILES))

PRENOBUILD : PRENOBUILD_BDM

PRENOBUILD_BDM : xbd/cdf_PRENOBUILD_BDM

xbd/cdf_PRENOBUILD_BDM : $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_xbd_cdf.cdf

__FILES_TO_GENERATE_BDM += $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_xbd_cdf.cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_xbd_cdf.cdf : | $(VSB_DIR)/krnl/cdf

$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_xbd_cdf.cdf : $(VSB_DIR)/h/config/auto.conf
	$(file >$(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_xbd_cdf.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(PRENOBUILD_BDM_xbd_cdf_DIR)/,$(sort $(PRENOBUILD_BDM_xbd_cdf_FILES))),BDM))
	$(CDFCOMP) -i $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_xbd_cdf.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu ARMARCH7 -layer BDM -vsb $(VSB_DIR)
	rm -f $(VSB_DIR)/krnl/cdf/PRENOBUILD_BDM_xbd_cdf.tmp

	
	
	
	

	

	

	
__DIR_TARGETS += $(__DIR_TARGETS_BDM)

__DIR_TARGETS_BDM += $(VSB_DIR)/krnl/cdf $(VSB_DIR)/krnl/h/public/drv/manager $(VSB_DIR)/krnl/h/public/drv/xbd C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/cdf C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/configlette C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/krnl/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/share/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/usr/h C:/Stream_ACEPRO_Test/ACEPRO_Test/AM5728_P1_VSB/vsblCdf

