

__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_CPU = ARMARCH7
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_VSB_DATAMODEL = ILP32
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_SMP = y
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_FP = hard
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_ENDIAN = little
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_CORE_3_2_2_0_RTP_3_2_2_0 = y
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_FS_2_1_4_0 = y
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_GPUDEV_2_0_0_0_RCAR_DU_1_0_0_4 = 
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_GUEST_SUPPORT_VX7_1_0_1_3 = 
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_1_0_3_6 = 
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_ITLI915_4_8_0_16 = 
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_OPENSSL_1_1_1k_0 = y
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_OPENSSL_FIPS_2_0_13_6 = 
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_SECURE_LOADER_2_0_2_6 = 
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_USER_MANAGEMENT_2_0_1_7 = 

