
ifndef __HEADER_ACCESS_BDM_LOOPFS_INCLUDED
__HEADER_ACCESS_BDM_LOOPFS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BDM_LOOPFS = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_LOOPFS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BDM_LOOPFS))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_LOOPFS
endif
endif

endif

endif

