
ifndef __HEADER_ACCESS_BDM_SDMMC_INCLUDED
__HEADER_ACCESS_BDM_SDMMC_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BDM_SDMMC = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BDM_SDMMC),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BDM_SDMMC))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BDM_SDMMC
endif
endif

endif

endif

