# Automatically generated file by prj_vsb.tcl : do not edit

VSB_LAYERS = 

ifdef _WRS_CONFIG_ACPI
VSB_LAYERS += ACPI
endif

ifdef _WRS_CONFIG_ARM
VSB_LAYERS += ARM
endif

ifdef _WRS_CONFIG_AUDIO
VSB_LAYERS += AUDIO
endif

ifdef _WRS_CONFIG_BCM2711
VSB_LAYERS += BCM2711
endif

ifdef _WRS_CONFIG_BCM2837
VSB_LAYERS += BCM2837
endif

ifdef _WRS_CONFIG_BDM
VSB_LAYERS += BDM
endif

ifdef _WRS_CONFIG_BOOST
VSB_LAYERS += BOOST
endif

ifdef _WRS_CONFIG_BRANSON_DRV_SR2107
VSB_LAYERS += BRANSON_DRV_SR2107
endif

ifdef _WRS_CONFIG_BRANSON_HTTP
VSB_LAYERS += BRANSON_HTTP
endif

ifdef _WRS_CONFIG_BRANSON_TIDSSFB
VSB_LAYERS += BRANSON_TIDSSFB
endif

ifdef _WRS_CONFIG_BRANSON_WEBSERVICES
VSB_LAYERS += BRANSON_WEBSERVICES
endif

ifdef _WRS_CONFIG_BZIP2
VSB_LAYERS += BZIP2
endif

ifdef _WRS_CONFIG_CAN
VSB_LAYERS += CAN
endif

ifdef _WRS_CONFIG_CIVETWEB
VSB_LAYERS += CIVETWEB
endif

ifdef _WRS_CONFIG_CJSON
VSB_LAYERS += CJSON
endif

ifdef _WRS_CONFIG_CONTAINER
VSB_LAYERS += CONTAINER
endif

ifdef _WRS_CONFIG_CORE
VSB_LAYERS += CORE
endif

ifdef _WRS_CONFIG_CPLUS_KERNEL
VSB_LAYERS += CPLUS_KERNEL
endif

ifdef _WRS_CONFIG_CRYPTOMISC
VSB_LAYERS += CRYPTOMISC
endif

ifdef _WRS_CONFIG_DEBUG
VSB_LAYERS += DEBUG
endif

ifdef _WRS_CONFIG_DISK_ENCRYPTION
VSB_LAYERS += DISK_ENCRYPTION
endif

ifdef _WRS_CONFIG_DRM
VSB_LAYERS += DRM
endif

ifdef _WRS_CONFIG_END
VSB_LAYERS += END
endif

ifdef _WRS_CONFIG_EVDEV
VSB_LAYERS += EVDEV
endif

ifdef _WRS_CONFIG_EXPAT
VSB_LAYERS += EXPAT
endif

ifdef _WRS_CONFIG_FBDEV
VSB_LAYERS += FBDEV
endif

ifdef _WRS_CONFIG_FDT
VSB_LAYERS += FDT
endif

ifdef _WRS_CONFIG_FREETYPE2
VSB_LAYERS += FREETYPE2
endif

ifdef _WRS_CONFIG_FS
VSB_LAYERS += FS
endif

ifdef _WRS_CONFIG_FSL_IMX
VSB_LAYERS += FSL_IMX
endif

ifdef _WRS_CONFIG_FSL_KINETIS
VSB_LAYERS += FSL_KINETIS
endif

ifdef _WRS_CONFIG_FSL_PQ2
VSB_LAYERS += FSL_PQ2
endif

ifdef _WRS_CONFIG_FSL_QORIQ
VSB_LAYERS += FSL_QORIQ
endif

ifdef _WRS_CONFIG_FSL_S32
VSB_LAYERS += FSL_S32
endif

ifdef _WRS_CONFIG_FSL_VYBRID
VSB_LAYERS += FSL_VYBRID
endif

ifdef _WRS_CONFIG_GPTP
VSB_LAYERS += GPTP
endif

ifdef _WRS_CONFIG_GPUDEV
VSB_LAYERS += GPUDEV
endif

ifdef _WRS_CONFIG_GSOAP
VSB_LAYERS += GSOAP
endif

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7
VSB_LAYERS += GUEST_SUPPORT_VX7
endif

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_BENCHMARKS
VSB_LAYERS += GUEST_SUPPORT_VX7_BENCHMARKS
endif

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE
VSB_LAYERS += GUEST_SUPPORT_VX7_SAFE
endif

ifdef _WRS_CONFIG_IA
VSB_LAYERS += IA
endif

ifdef _WRS_CONFIG_ICU
VSB_LAYERS += ICU
endif

ifdef _WRS_CONFIG_IEEE1394
VSB_LAYERS += IEEE1394
endif

ifdef _WRS_CONFIG_INTEL_IPP
VSB_LAYERS += INTEL_IPP
endif

ifdef _WRS_CONFIG_INTEL_MKL
VSB_LAYERS += INTEL_MKL
endif

ifdef _WRS_CONFIG_INTRINSICS_COMMON
VSB_LAYERS += INTRINSICS_COMMON
endif

ifdef _WRS_CONFIG_INTRINSICS_GNU
VSB_LAYERS += INTRINSICS_GNU
endif

ifdef _WRS_CONFIG_INTRINSICS_LLVM
VSB_LAYERS += INTRINSICS_LLVM
endif

ifdef _WRS_CONFIG_IPNET_8021X
VSB_LAYERS += IPNET_8021X
endif

ifdef _WRS_CONFIG_IPNET_AAA
VSB_LAYERS += IPNET_AAA
endif

ifdef _WRS_CONFIG_IPNET_COREIP
VSB_LAYERS += IPNET_COREIP
endif

ifdef _WRS_CONFIG_IPNET_DHCP
VSB_LAYERS += IPNET_DHCP
endif

ifdef _WRS_CONFIG_IPNET_DNSC
VSB_LAYERS += IPNET_DNSC
endif

ifdef _WRS_CONFIG_IPNET_EAP
VSB_LAYERS += IPNET_EAP
endif

ifdef _WRS_CONFIG_IPNET_FIREWALL
VSB_LAYERS += IPNET_FIREWALL
endif

ifdef _WRS_CONFIG_IPNET_FTP
VSB_LAYERS += IPNET_FTP
endif

ifdef _WRS_CONFIG_IPNET_IPSECIKE
VSB_LAYERS += IPNET_IPSECIKE
endif

ifdef _WRS_CONFIG_IPNET_LINKPROTO
VSB_LAYERS += IPNET_LINKPROTO
endif

ifdef _WRS_CONFIG_IPNET_QOS
VSB_LAYERS += IPNET_QOS
endif

ifdef _WRS_CONFIG_IPNET_ROUTEPROTO
VSB_LAYERS += IPNET_ROUTEPROTO
endif

ifdef _WRS_CONFIG_IPNET_SNTP
VSB_LAYERS += IPNET_SNTP
endif

ifdef _WRS_CONFIG_IPNET_SSH
VSB_LAYERS += IPNET_SSH
endif

ifdef _WRS_CONFIG_IPNET_TFTP
VSB_LAYERS += IPNET_TFTP
endif

ifdef _WRS_CONFIG_IPNET_USRSPACE
VSB_LAYERS += IPNET_USRSPACE
endif

ifdef _WRS_CONFIG_IPNET_VRRP
VSB_LAYERS += IPNET_VRRP
endif

ifdef _WRS_CONFIG_ITL_SOC_ARRIA10
VSB_LAYERS += ITL_SOC_ARRIA10
endif

ifdef _WRS_CONFIG_ITL_SOC_COMMON
VSB_LAYERS += ITL_SOC_COMMON
endif

ifdef _WRS_CONFIG_ITL_SOC_CYCLONE5
VSB_LAYERS += ITL_SOC_CYCLONE5
endif

ifdef _WRS_CONFIG_ITL_X86_COMMON
VSB_LAYERS += ITL_X86_COMMON
endif

ifdef _WRS_CONFIG_ITLI915
VSB_LAYERS += ITLI915
endif

ifdef _WRS_CONFIG_JANSSON
VSB_LAYERS += JANSSON
endif

ifdef _WRS_CONFIG_KHRONOS
VSB_LAYERS += KHRONOS
endif

ifdef _WRS_CONFIG_LDAPC
VSB_LAYERS += LDAPC
endif

ifdef _WRS_CONFIG_LIBARCHIVE
VSB_LAYERS += LIBARCHIVE
endif

ifdef _WRS_CONFIG_LIBC_BOOT
VSB_LAYERS += LIBC_BOOT
endif

ifdef _WRS_CONFIG_LIBC_STD
VSB_LAYERS += LIBC_STD
endif

ifdef _WRS_CONFIG_LIBCPLUS_STD
VSB_LAYERS += LIBCPLUS_STD
endif

ifdef _WRS_CONFIG_LIBCURL
VSB_LAYERS += LIBCURL
endif

ifdef _WRS_CONFIG_LIBDRM
VSB_LAYERS += LIBDRM
endif

ifdef _WRS_CONFIG_LIBFFI
VSB_LAYERS += LIBFFI
endif

ifdef _WRS_CONFIG_LIBJPEG
VSB_LAYERS += LIBJPEG
endif

ifdef _WRS_CONFIG_LIBPNG
VSB_LAYERS += LIBPNG
endif

ifdef _WRS_CONFIG_LZMA
VSB_LAYERS += LZMA
endif

ifdef _WRS_CONFIG_MCHP_PFSOC
VSB_LAYERS += MCHP_PFSOC
endif

ifdef _WRS_CONFIG_MESA
VSB_LAYERS += MESA
endif

ifdef _WRS_CONFIG_MIB2
VSB_LAYERS += MIB2
endif

ifdef _WRS_CONFIG_MIMALLOC
VSB_LAYERS += MIMALLOC
endif

ifdef _WRS_CONFIG_MOSQUITTO
VSB_LAYERS += MOSQUITTO
endif

ifdef _WRS_CONFIG_MV_64360
VSB_LAYERS += MV_64360
endif

ifdef _WRS_CONFIG_NET_BASE
VSB_LAYERS += NET_BASE
endif

ifdef _WRS_CONFIG_NTP
VSB_LAYERS += NTP
endif

ifdef _WRS_CONFIG_ONETBB
VSB_LAYERS += ONETBB
endif

ifdef _WRS_CONFIG_OP_TEE
VSB_LAYERS += OP_TEE
endif

ifdef _WRS_CONFIG_OPEN62541
VSB_LAYERS += OPEN62541
endif

ifdef _WRS_CONFIG_OPENCV
VSB_LAYERS += OPENCV
endif

ifdef _WRS_CONFIG_OPENMP
VSB_LAYERS += OPENMP
endif

ifdef _WRS_CONFIG_OPENSSL
VSB_LAYERS += OPENSSL
endif

ifdef _WRS_CONFIG_OPENSSL_FIPS
VSB_LAYERS += OPENSSL_FIPS
endif

ifdef _WRS_CONFIG_PARG
VSB_LAYERS += PARG
endif

ifdef _WRS_CONFIG_PPC
VSB_LAYERS += PPC
endif

ifdef _WRS_CONFIG_PROFILES
VSB_LAYERS += PROFILES
endif

ifdef _WRS_CONFIG_PSCI
VSB_LAYERS += PSCI
endif

ifdef _WRS_CONFIG_PSL_XLNX_VERSAL
VSB_LAYERS += PSL_XLNX_VERSAL
endif

ifdef _WRS_CONFIG_PTP
VSB_LAYERS += PTP
endif

ifdef _WRS_CONFIG_PYTHON
VSB_LAYERS += PYTHON
endif

ifdef _WRS_CONFIG_QSP
VSB_LAYERS += QSP
endif

ifdef _WRS_CONFIG_RASTER
VSB_LAYERS += RASTER
endif

ifdef _WRS_CONFIG_RENESAS_COMMON
VSB_LAYERS += RENESAS_COMMON
endif

ifdef _WRS_CONFIG_RENESAS_RCAR
VSB_LAYERS += RENESAS_RCAR
endif

ifdef _WRS_CONFIG_RENESAS_RZ
VSB_LAYERS += RENESAS_RZ
endif

ifdef _WRS_CONFIG_RENESAS_RZ_G2
VSB_LAYERS += RENESAS_RZ_G2
endif

ifdef _WRS_CONFIG_RISCV
VSB_LAYERS += RISCV
endif

ifdef _WRS_CONFIG_RTNET
VSB_LAYERS += RTNET
endif

ifdef _WRS_CONFIG_RTTOOLS
VSB_LAYERS += RTTOOLS
endif

ifdef _WRS_CONFIG_SDL
VSB_LAYERS += SDL
endif

ifdef _WRS_CONFIG_SECURE_LOADER
VSB_LAYERS += SECURE_LOADER
endif

ifdef _WRS_CONFIG_SECURITY_EVENT
VSB_LAYERS += SECURITY_EVENT
endif

ifdef _WRS_CONFIG_SECURITY_MISC
VSB_LAYERS += SECURITY_MISC
endif

ifdef _WRS_CONFIG_SERVICE
VSB_LAYERS += SERVICE
endif

ifdef _WRS_CONFIG_SIFIVE_RISCV
VSB_LAYERS += SIFIVE_RISCV
endif

ifdef _WRS_CONFIG_SNMP
VSB_LAYERS += SNMP
endif

ifdef _WRS_CONFIG_SQLITE
VSB_LAYERS += SQLITE
endif

ifdef _WRS_CONFIG_TCPLAY
VSB_LAYERS += TCPLAY
endif

ifdef _WRS_CONFIG_TENSORFLOW_LITE
VSB_LAYERS += TENSORFLOW_LITE
endif

ifdef _WRS_CONFIG_TI_FIRMWARE
VSB_LAYERS += TI_FIRMWARE
endif

ifdef _WRS_CONFIG_TI_KEYSTONE
VSB_LAYERS += TI_KEYSTONE
endif

ifdef _WRS_CONFIG_TI_SITARA
VSB_LAYERS += TI_SITARA
endif

ifdef _WRS_CONFIG_TILCON
VSB_LAYERS += TILCON
endif

ifdef _WRS_CONFIG_TPM2_TSS
VSB_LAYERS += TPM2_TSS
endif

ifdef _WRS_CONFIG_TSN
VSB_LAYERS += TSN
endif

ifdef _WRS_CONFIG_USB
VSB_LAYERS += USB
endif

ifdef _WRS_CONFIG_USER_MANAGEMENT
VSB_LAYERS += USER_MANAGEMENT
endif

ifdef _WRS_CONFIG_UTILS
VSB_LAYERS += UTILS
endif

ifdef _WRS_CONFIG_UZLIB
VSB_LAYERS += UZLIB
endif

ifdef _WRS_CONFIG_VI_EDITOR
VSB_LAYERS += VI_EDITOR
endif

ifdef _WRS_CONFIG_VIP_PROFILES
VSB_LAYERS += VIP_PROFILES
endif

ifdef _WRS_CONFIG_VXBUS
VSB_LAYERS += VXBUS
endif

ifdef _WRS_CONFIG_VXSIM
VSB_LAYERS += VXSIM
endif

ifdef _WRS_CONFIG_WEBCLI
VSB_LAYERS += WEBCLI
endif

ifdef _WRS_CONFIG_XEN
VSB_LAYERS += XEN
endif

ifdef _WRS_CONFIG_XLNX_COMMON
VSB_LAYERS += XLNX_COMMON
endif

ifdef _WRS_CONFIG_XLNX_ZYNQ
VSB_LAYERS += XLNX_ZYNQ
endif

ifdef _WRS_CONFIG_XRT
VSB_LAYERS += XRT
endif

ifdef _WRS_CONFIG_ZLIB
VSB_LAYERS += ZLIB
endif

