# Automatically generated file: do not edit

##########################
# CONTAINER_MANAGER Section
##########################


ifdef _WRS_CONFIG_CONTAINER_MANAGER
VSBL_CONTAINER_MANAGER_SRC = 
VSBL_CONTAINER_MANAGER_DEPEND = 

ifdef _WRS_CONFIG_CONTAINER_1_0_1_0_MANAGER_1_0_0_1
VSBL_CONTAINER_MANAGER_SRC += CONTAINER_MANAGER
VSBL_CONTAINER_MANAGER_DEPEND += JANSSON
VSBL_CONTAINER_MANAGER_DEPEND += LIBCURL
CONTAINER_MANAGER_FASTBUILD = YES
VSBL_CONTAINER_MANAGER_PATH = $(WIND_BASE)/os/container/manager
VSBL_CONTAINER_MANAGER_VERSION = CONTAINER_1_0_1_0_MANAGER_1_0_0_1
endif
endif

