# Automatically generated file: do not edit

##########################
# OPENSSL_FIPS Section
##########################


ifdef _WRS_CONFIG_OPENSSL_FIPS
VSBL_OPENSSL_FIPS_SRC = 
VSBL_OPENSSL_FIPS_DEPEND = 

ifdef _WRS_CONFIG_OPENSSL_FIPS_2_0_13_6
VSBL_OPENSSL_FIPS_SRC += OPENSSL_FIPS
VSBL_OPENSSL_FIPS_DEPEND += SECURITY_MISC_SEC_CRYPTO
VSBL_OPENSSL_FIPS_DEPEND += UTILS_SHELL
OPENSSL_FIPS_FASTBUILD = YES
VSBL_OPENSSL_FIPS_PATH = $(WIND_BASE)/os/security/openssl_fips
VSBL_OPENSSL_FIPS_VERSION = OPENSSL_FIPS_2_0_13_6
endif
endif

