# Automatically generated file: do not edit

##########################
# PYTHON_DATEUTIL Section
##########################


ifdef _WRS_CONFIG_PYTHON_DATEUTIL
VSBL_PYTHON_DATEUTIL_SRC = 
VSBL_PYTHON_DATEUTIL_DEPEND = 

ifdef _WRS_CONFIG_PYTHON_3_8_0_6_DATEUTIL_2_8_1_0
VSBL_PYTHON_DATEUTIL_SRC += PYTHON_DATEUTIL
VSBL_PYTHON_DATEUTIL_DEPEND += CORE_RTP
VSBL_PYTHON_DATEUTIL_DEPEND += PYTHON_SIX
PYTHON_DATEUTIL_FASTBUILD = YES
VSBL_PYTHON_DATEUTIL_PATH = $(WIND_BASE)/contrib/python-3.8.0/dateutil
VSBL_PYTHON_DATEUTIL_VERSION = PYTHON_3_8_0_6_DATEUTIL_2_8_1_0
endif
endif

