# Automatically generated file: do not edit

##########################
# CRYPTOMISC_IPHWCRYPTO Section
##########################


ifdef _WRS_CONFIG_CRYPTOMISC_IPHWCRYPTO
VSBL_CRYPTOMISC_IPHWCRYPTO_SRC = 
VSBL_CRYPTOMISC_IPHWCRYPTO_DEPEND = 

ifdef _WRS_CONFIG_CRYPTOMISC_2_0_2_6_IPHWCRYPTO_2_0_2_6
VSBL_CRYPTOMISC_IPHWCRYPTO_SRC += CRYPTOMISC_IPHWCRYPTO
VSBL_CRYPTOMISC_IPHWCRYPTO_DEPEND += IPNET_IPSECIKE
VSBL_CRYPTOMISC_IPHWCRYPTO_DEPEND += SECURITY_MISC_SEC_CRYPTO
CRYPTOMISC_IPHWCRYPTO_FASTBUILD = YES
VSBL_CRYPTOMISC_IPHWCRYPTO_PATH = $(WIND_BASE)/os/security/crypto_misc/iphwcrypto
VSBL_CRYPTOMISC_IPHWCRYPTO_VERSION = CRYPTOMISC_2_0_2_6_IPHWCRYPTO_2_0_2_6
endif
endif

