# Automatically generated file: do not edit

##########################
# CORE_CUSTOM Section
##########################


ifdef _WRS_CONFIG_CORE_CUSTOM
VSBL_CORE_CUSTOM_SRC = 
VSBL_CORE_CUSTOM_DEPEND = 

ifdef _WRS_CONFIG_CORE_3_2_2_0_SYSCALLS_2_0_4_0_CUSTOM_2_0_0_0
VSBL_CORE_CUSTOM_SRC += CORE_CUSTOM
CORE_CUSTOM_FASTBUILD = YES
VSBL_CORE_CUSTOM_PATH = $(WIND_BASE)/os/core/syscalls/custom
VSBL_CORE_CUSTOM_VERSION = CORE_3_2_2_0_SYSCALLS_2_0_4_0_CUSTOM_2_0_0_0
endif

ifdef _WRS_CONFIG_CORE_3_2_2_0_SYSCALLS_2_0_4_0_CUSTOM_2_0_0_0_BRANSON
VSBL_CORE_CUSTOM_SRC += CORE_CUSTOM
CORE_CUSTOM_FASTBUILD = YES
VSBL_CORE_CUSTOM_PATH = $(WIND_BASE)/os/core/syscalls/branson
VSBL_CORE_CUSTOM_VERSION = CORE_3_2_2_0_SYSCALLS_2_0_4_0_CUSTOM_2_0_0_0_BRANSON
endif
endif

