# Automatically generated file: do not edit

##########################
# TI_SITARA Section
##########################


ifdef _WRS_CONFIG_TI_SITARA
VSBL_TI_SITARA_SRC = 
VSBL_TI_SITARA_DEPEND = 

ifdef _WRS_CONFIG_TI_SITARA_2_1_4_3
VSBL_TI_SITARA_SRC += TI_SITARA
ifndef _WRS_CONFIG_ARM_ARMV7M
VSBL_TI_SITARA_DEPEND += PSCI
endif
ifndef _WRS_CONFIG_CERT
VSBL_TI_SITARA_DEPEND += TI_FIRMWARE
endif
VSBL_TI_SITARA_DEPEND += UTILS
ifdef _WRS_CONFIG_TI_FIRMWARE
VSBL_TI_SITARA_DEPEND += TI_FIRMWARE
endif
ifdef _WRS_CONFIG_TI_FIRMWARE*
VSBL_TI_SITARA_DEPEND += TI_FIRMWARE
endif
VSBL_TI_SITARA_DEPEND += VXBUS
VSBL_TI_SITARA_DEPEND += CORE
VSBL_TI_SITARA_DEPEND += ARM
VSBL_TI_SITARA_DEPEND += VXBUS
VSBL_TI_SITARA_DEPEND += FDT
VSBL_TI_SITARA_DEPEND += FDT
VSBL_TI_SITARA_DEPEND += CORE
VSBL_TI_SITARA_DEPEND += VXBUS
TI_SITARA_FASTBUILD = YES
VSBL_TI_SITARA_PATH = $(WIND_BASE)/os/psl/ti/ti_sitara
VSBL_TI_SITARA_VERSION = TI_SITARA_2_1_4_3
endif
endif

