# Automatically generated file: do not edit

##########################
# IPNET_IPSECIKE_IKE Section
##########################


ifdef _WRS_CONFIG_IPNET_IPSECIKE_IKE
VSBL_IPNET_IPSECIKE_IKE_SRC = 
VSBL_IPNET_IPSECIKE_IKE_DEPEND = 

ifdef _WRS_CONFIG_IPNET_IPSECIKE_2_0_0_8_IKE_2_0_0_8
VSBL_IPNET_IPSECIKE_IKE_SRC += IPNET_IPSECIKE_IKE
VSBL_IPNET_IPSECIKE_IKE_DEPEND += IPNET_COREIP
VSBL_IPNET_IPSECIKE_IKE_DEPEND += SECURITY_MISC_SEC_CRYPTO
VSBL_IPNET_IPSECIKE_IKE_DEPEND += SECURITY_MISC_SEC_HASH
IPNET_IPSECIKE_IKE_FASTBUILD = YES
IPNET_IPSECIKE_IKE_FRIEND = IPNET_IPSECIKE_GDOI
VSBL_IPNET_IPSECIKE_IKE_PATH = $(WIND_BASE)/os/net/ipnet/ipsecike/ike
VSBL_IPNET_IPSECIKE_IKE_VERSION = IPNET_IPSECIKE_2_0_0_8_IKE_2_0_0_8
endif
endif

