# Automatically generated file: do not edit

##########################
# TI_KEYSTONE Section
##########################


ifdef _WRS_CONFIG_TI_KEYSTONE
VSBL_TI_KEYSTONE_SRC = 
VSBL_TI_KEYSTONE_DEPEND = 

ifdef _WRS_CONFIG_TI_KEYSTONE_2_0_3_3
VSBL_TI_KEYSTONE_SRC += TI_KEYSTONE
VSBL_TI_KEYSTONE_DEPEND += FDT
VSBL_TI_KEYSTONE_DEPEND += SERVICE_JOBQUEUE
VSBL_TI_KEYSTONE_DEPEND += UTILS
VSBL_TI_KEYSTONE_DEPEND += VXBUS
VSBL_TI_KEYSTONE_DEPEND += CORE
VSBL_TI_KEYSTONE_DEPEND += ARM
TI_KEYSTONE_FASTBUILD = YES
VSBL_TI_KEYSTONE_PATH = $(WIND_BASE)/os/psl/ti/ti_keystone
VSBL_TI_KEYSTONE_VERSION = TI_KEYSTONE_2_0_3_3
endif
endif

