# Automatically generated file: do not edit

##########################
# IPNET_IPSECIKE Section
##########################


ifdef _WRS_CONFIG_IPNET_IPSECIKE
VSBL_IPNET_IPSECIKE_SRC = 
VSBL_IPNET_IPSECIKE_DEPEND = 

ifdef _WRS_CONFIG_IPNET_IPSECIKE_2_0_0_8
ifdef _WRS_CONFIG_IPNET_IPSECIKE_GDOI
VSBL_IPNET_IPSECIKE_SRC += IPNET_IPSECIKE_GDOI
endif
ifdef _WRS_CONFIG_IPNET_IPSECIKE_IKE
VSBL_IPNET_IPSECIKE_SRC += IPNET_IPSECIKE_IKE
endif
VSBL_IPNET_IPSECIKE_SRC += IPNET_IPSECIKE
VSBL_IPNET_IPSECIKE_DEPEND += IPNET_COREIP
VSBL_IPNET_IPSECIKE_DEPEND += SECURITY_MISC_SEC_CRYPTO
VSBL_IPNET_IPSECIKE_DEPEND += SECURITY_MISC_SEC_HASH
VSBL_IPNET_IPSECIKE_DEPEND += OPENSSL
IPNET_IPSECIKE_FASTBUILD = YES
IPNET_IPSECIKE_FRIEND = IPNET_COREIP CRYPTOMISC_IPHWCRYPTO IPNET_IPSECIKE_GDOI
VSBL_IPNET_IPSECIKE_PATH = $(WIND_BASE)/os/net/ipnet/ipsecike
VSBL_IPNET_IPSECIKE_VERSION = IPNET_IPSECIKE_2_0_0_8
endif
endif

