# Automatically generated file: do not edit

##########################
# SQLITE Section
##########################


ifdef _WRS_CONFIG_SQLITE
VSBL_SQLITE_SRC = 
VSBL_SQLITE_DEPEND = 

ifdef _WRS_CONFIG_SQLITE_3_32_3_2
VSBL_SQLITE_SRC += SQLITE
VSBL_SQLITE_DEPEND += CORE_RTP
VSBL_SQLITE_DEPEND += FS_UTIL
VSBL_SQLITE_DEPEND += FS_VRFS
VSBL_SQLITE_DEPEND += UTILS_DEPLOY
VSBL_SQLITE_DEPEND += UTILS_UNIX
VSBL_SQLITE_DEPEND += UTILS_WRCC
SQLITE_FASTBUILD = YES
VSBL_SQLITE_PATH = $(WIND_BASE)/contrib/sqlite-3.32.3
VSBL_SQLITE_VERSION = SQLITE_3_32_3_2
endif
endif

