# Automatically generated file: do not edit

##########################
# SERVICE_JOBQUEUE Section
##########################


ifdef _WRS_CONFIG_SERVICE_JOBQUEUE
VSBL_SERVICE_JOBQUEUE_SRC = 
VSBL_SERVICE_JOBQUEUE_DEPEND = 

ifdef _WRS_CONFIG_SERVICE_4_0_1_1_JOBQUEUE_4_0_1_1
VSBL_SERVICE_JOBQUEUE_SRC += SERVICE_JOBQUEUE
SERVICE_JOBQUEUE_FASTBUILD = YES
VSBL_SERVICE_JOBQUEUE_PATH = $(WIND_BASE)/os/service/jobqueue
VSBL_SERVICE_JOBQUEUE_VERSION = SERVICE_4_0_1_1_JOBQUEUE_4_0_1_1
endif
endif

