# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7 Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7
VSBL_GUEST_SUPPORT_VX7_SRC = 
VSBL_GUEST_SUPPORT_VX7_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_1_0_1_3
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_DSS
VSBL_GUEST_SUPPORT_VX7_SRC += GUEST_SUPPORT_VX7_DSS
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_HVIF
VSBL_GUEST_SUPPORT_VX7_SRC += GUEST_SUPPORT_VX7_HVIF
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SHMEM
VSBL_GUEST_SUPPORT_VX7_SRC += GUEST_SUPPORT_VX7_SHMEM
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SYSTEMVIEWER
VSBL_GUEST_SUPPORT_VX7_SRC += GUEST_SUPPORT_VX7_SYSTEMVIEWER
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_THROTTLE
VSBL_GUEST_SUPPORT_VX7_SRC += GUEST_SUPPORT_VX7_THROTTLE
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_VIRTIO
VSBL_GUEST_SUPPORT_VX7_SRC += GUEST_SUPPORT_VX7_VIRTIO
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_VNIC
VSBL_GUEST_SUPPORT_VX7_SRC += GUEST_SUPPORT_VX7_VNIC
endif
VSBL_GUEST_SUPPORT_VX7_SRC += GUEST_SUPPORT_VX7
VSBL_GUEST_SUPPORT_VX7_DEPEND += BDM
ifndef _WRS_CONFIG_CERT
VSBL_GUEST_SUPPORT_VX7_DEPEND += BDM_LOOPFS
endif
VSBL_GUEST_SUPPORT_VX7_DEPEND += UTILS_OSTOOLS
VSBL_GUEST_SUPPORT_VX7_DEPEND += CORE
GUEST_SUPPORT_VX7_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_PATH = $(WIND_BASE)/os/hv/guest_support_vx7
VSBL_GUEST_SUPPORT_VX7_VERSION = GUEST_SUPPORT_VX7_1_0_1_3
endif
endif

