# Automatically generated file: do not edit

##########################
# UTILS_BOOTAPP Section
##########################


ifdef _WRS_CONFIG_UTILS_BOOTAPP
VSBL_UTILS_BOOTAPP_SRC = 
VSBL_UTILS_BOOTAPP_DEPEND = 

ifdef _WRS_CONFIG_UTILS_2_0_8_0_BOOTAPP_2_0_8_0
VSBL_UTILS_BOOTAPP_SRC += UTILS_BOOTAPP
VSBL_UTILS_BOOTAPP_DEPEND += END
VSBL_UTILS_BOOTAPP_DEPEND += FS_UTIL
VSBL_UTILS_BOOTAPP_DEPEND += IPNET_COREIP
VSBL_UTILS_BOOTAPP_DEPEND += IPNET_DHCP_CLIENT
VSBL_UTILS_BOOTAPP_DEPEND += UTILS_LOADER
VSBL_UTILS_BOOTAPP_DEPEND += CORE
VSBL_UTILS_BOOTAPP_DEPEND += CORE
UTILS_BOOTAPP_FASTBUILD = YES
VSBL_UTILS_BOOTAPP_PATH = $(WIND_BASE)/os/utils/bootapp
VSBL_UTILS_BOOTAPP_VERSION = UTILS_2_0_8_0_BOOTAPP_2_0_8_0
endif
endif

