# Automatically generated file: do not edit

##########################
# UTILS_LOADER Section
##########################


ifdef _WRS_CONFIG_UTILS_LOADER
VSBL_UTILS_LOADER_SRC = 
VSBL_UTILS_LOADER_DEPEND = 

ifdef _WRS_CONFIG_UTILS_2_0_8_0_LOADER_2_0_8_0
VSBL_UTILS_LOADER_SRC += UTILS_LOADER
VSBL_UTILS_LOADER_DEPEND += UTILS_OSTOOLS
UTILS_LOADER_FASTBUILD = YES
VSBL_UTILS_LOADER_PATH = $(WIND_BASE)/os/utils/loader
VSBL_UTILS_LOADER_VERSION = UTILS_2_0_8_0_LOADER_2_0_8_0
endif
endif

