# Automatically generated file: do not edit

##########################
# INTRINSICS_GNU Section
##########################


ifdef _WRS_CONFIG_INTRINSICS_GNU
VSBL_INTRINSICS_GNU_SRC = 
VSBL_INTRINSICS_GNU_DEPEND = 

ifdef _WRS_CONFIG_INTRINSICS_GNU_1_0_2_3
VSBL_INTRINSICS_GNU_SRC += INTRINSICS_GNU
VSBL_INTRINSICS_GNU_DEPEND += UTILS
VSBL_INTRINSICS_GNU_DEPEND += LIBCPLUS_STD
VSBL_INTRINSICS_GNU_DEPEND += LIBC_STD
INTRINSICS_GNU_FASTBUILD = YES
VSBL_INTRINSICS_GNU_PATH = $(WIND_BASE)/os/lang_lib/tool/intrinsics_gnu
VSBL_INTRINSICS_GNU_VERSION = INTRINSICS_GNU_1_0_2_3
endif
endif

