# Automatically generated file: do not edit

##########################
# BRANSON_WEBSERVICES Section
##########################


ifdef _WRS_CONFIG_BRANSON_WEBSERVICES
VSBL_BRANSON_WEBSERVICES_SRC = 
VSBL_BRANSON_WEBSERVICES_DEPEND = 

ifdef _WRS_CONFIG_BRANSON_WEBSERVICES_1_1_1_1
VSBL_BRANSON_WEBSERVICES_SRC += BRANSON_WEBSERVICES
VSBL_BRANSON_WEBSERVICES_DEPEND += BRANSON_HTTP
VSBL_BRANSON_WEBSERVICES_DEPEND += WEBCLI_MIBWAY
BRANSON_WEBSERVICES_FASTBUILD = YES
VSBL_BRANSON_WEBSERVICES_PATH = D:/JerryW/SoftwareRelease/Vxworks_2021.07_Test_Stream/_Branson_Driver_Layer_SR2107/BRANSON_DRV_2_0_0_0/webservices
VSBL_BRANSON_WEBSERVICES_VERSION = BRANSON_WEBSERVICES_1_1_1_1
endif
endif

