# Automatically generated file: do not edit

##########################
# RENESAS_RZ Section
##########################


ifdef _WRS_CONFIG_RENESAS_RZ
VSBL_RENESAS_RZ_SRC = 
VSBL_RENESAS_RZ_DEPEND = 

ifdef _WRS_CONFIG_RENESAS_RZ_1_1_1_2
VSBL_RENESAS_RZ_SRC += RENESAS_RZ
VSBL_RENESAS_RZ_DEPEND += FDT
VSBL_RENESAS_RZ_DEPEND += SERVICE_JOBQUEUE
VSBL_RENESAS_RZ_DEPEND += UTILS
VSBL_RENESAS_RZ_DEPEND += VXBUS
VSBL_RENESAS_RZ_DEPEND += CORE
VSBL_RENESAS_RZ_DEPEND += ARM
RENESAS_RZ_FASTBUILD = YES
VSBL_RENESAS_RZ_PATH = $(WIND_BASE)/os/psl/renesas/renesas_rz
VSBL_RENESAS_RZ_VERSION = RENESAS_RZ_1_1_1_2
endif
endif

