# Automatically generated file: do not edit

##########################
# FSL_VYBRID Section
##########################


ifdef _WRS_CONFIG_FSL_VYBRID
VSBL_FSL_VYBRID_SRC = 
VSBL_FSL_VYBRID_DEPEND = 

ifdef _WRS_CONFIG_FSL_VYBRID_2_0_3_1
VSBL_FSL_VYBRID_SRC += FSL_VYBRID
VSBL_FSL_VYBRID_DEPEND += FDT
VSBL_FSL_VYBRID_DEPEND += UTILS
VSBL_FSL_VYBRID_DEPEND += VXBUS
ifdef _WRS_CONFIG_CORE
VSBL_FSL_VYBRID_DEPEND += CORE
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_FSL_VYBRID_DEPEND += CORE
endif
ifdef _WRS_CONFIG_ARM
VSBL_FSL_VYBRID_DEPEND += ARM
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_FSL_VYBRID_DEPEND += ARM
endif
FSL_VYBRID_FASTBUILD = YES
VSBL_FSL_VYBRID_PATH = $(WIND_BASE)/os/psl/freescale/fsl_vybrid
VSBL_FSL_VYBRID_VERSION = FSL_VYBRID_2_0_3_1
endif
endif

