# Automatically generated file: do not edit

##########################
# RTTOOLS_DEBUG_AGENT Section
##########################


ifdef _WRS_CONFIG_RTTOOLS_DEBUG_AGENT
VSBL_RTTOOLS_DEBUG_AGENT_SRC = 
VSBL_RTTOOLS_DEBUG_AGENT_DEPEND = 

ifdef _WRS_CONFIG_RTTOOLS_2_0_1_7_DEBUG_AGENT_2_0_1_7
VSBL_RTTOOLS_DEBUG_AGENT_SRC += RTTOOLS_DEBUG_AGENT
VSBL_RTTOOLS_DEBUG_AGENT_DEPEND += DEBUG
VSBL_RTTOOLS_DEBUG_AGENT_DEPEND += FS_UTIL
VSBL_RTTOOLS_DEBUG_AGENT_DEPEND += IPNET_COREIP
VSBL_RTTOOLS_DEBUG_AGENT_DEPEND += UTILS_LOADER
RTTOOLS_DEBUG_AGENT_FASTBUILD = YES
VSBL_RTTOOLS_DEBUG_AGENT_PATH = $(WIND_BASE)/os/debug_analysis/rttools/agent
VSBL_RTTOOLS_DEBUG_AGENT_VERSION = RTTOOLS_2_0_1_7_DEBUG_AGENT_2_0_1_7
endif
endif

