# Automatically generated file: do not edit

##########################
# ITL_SOC_CYCLONE5 Section
##########################


ifdef _WRS_CONFIG_ITL_SOC_CYCLONE5
VSBL_ITL_SOC_CYCLONE5_SRC = 
VSBL_ITL_SOC_CYCLONE5_DEPEND = 

ifdef _WRS_CONFIG_ITL_SOC_CYCLONE5_1_1_1_3
VSBL_ITL_SOC_CYCLONE5_SRC += ITL_SOC_CYCLONE5
VSBL_ITL_SOC_CYCLONE5_DEPEND += FDT
VSBL_ITL_SOC_CYCLONE5_DEPEND += UTILS
VSBL_ITL_SOC_CYCLONE5_DEPEND += CORE
VSBL_ITL_SOC_CYCLONE5_DEPEND += ARM
ITL_SOC_CYCLONE5_FASTBUILD = YES
VSBL_ITL_SOC_CYCLONE5_PATH = $(WIND_BASE)/os/psl/intel/itl_soc_cyclone5
VSBL_ITL_SOC_CYCLONE5_VERSION = ITL_SOC_CYCLONE5_1_1_1_3
endif
endif

