# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_SAFE Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE
VSBL_GUEST_SUPPORT_VX7_SAFE_SRC = 
VSBL_GUEST_SUPPORT_VX7_SAFE_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_1_0_3_6
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_APEX
VSBL_GUEST_SUPPORT_VX7_SAFE_SRC += GUEST_SUPPORT_VX7_SAFE_APEX
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_HM
VSBL_GUEST_SUPPORT_VX7_SAFE_SRC += GUEST_SUPPORT_VX7_SAFE_HM
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_HVIF
VSBL_GUEST_SUPPORT_VX7_SAFE_SRC += GUEST_SUPPORT_VX7_SAFE_HVIF
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_MPFS
VSBL_GUEST_SUPPORT_VX7_SAFE_SRC += GUEST_SUPPORT_VX7_SAFE_MPFS
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_SAFEIPC
VSBL_GUEST_SUPPORT_VX7_SAFE_SRC += GUEST_SUPPORT_VX7_SAFE_SAFEIPC
endif
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_SOCKET
VSBL_GUEST_SUPPORT_VX7_SAFE_SRC += GUEST_SUPPORT_VX7_SAFE_SOCKET
endif
VSBL_GUEST_SUPPORT_VX7_SAFE_SRC += GUEST_SUPPORT_VX7_SAFE
VSBL_GUEST_SUPPORT_VX7_SAFE_DEPEND += FDT
VSBL_GUEST_SUPPORT_VX7_SAFE_DEPEND += GUEST_SUPPORT_VX7
VSBL_GUEST_SUPPORT_VX7_SAFE_DEPEND += VXBUS
GUEST_SUPPORT_VX7_SAFE_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_SAFE_PATH = $(WIND_BASE)/os/hv/guest_support_vx7_safe
VSBL_GUEST_SUPPORT_VX7_SAFE_VERSION = GUEST_SUPPORT_VX7_SAFE_1_0_3_6
endif
endif

