# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_SYSTEMVIEWER Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SYSTEMVIEWER
VSBL_GUEST_SUPPORT_VX7_SYSTEMVIEWER_SRC = 
VSBL_GUEST_SUPPORT_VX7_SYSTEMVIEWER_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_1_0_1_3_SYSTEMVIEWER_1_0_1_3
VSBL_GUEST_SUPPORT_VX7_SYSTEMVIEWER_SRC += GUEST_SUPPORT_VX7_SYSTEMVIEWER
GUEST_SUPPORT_VX7_SYSTEMVIEWER_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_SYSTEMVIEWER_PATH = $(WIND_BASE)/os/hv/guest_support_vx7/systemviewer
VSBL_GUEST_SUPPORT_VX7_SYSTEMVIEWER_VERSION = GUEST_SUPPORT_VX7_1_0_1_3_SYSTEMVIEWER_1_0_1_3
endif
endif

