# Automatically generated file: do not edit

##########################
# SECURITY_MISC_SEC_HASH Section
##########################


ifdef _WRS_CONFIG_SECURITY_MISC_SEC_HASH
VSBL_SECURITY_MISC_SEC_HASH_SRC = 
VSBL_SECURITY_MISC_SEC_HASH_DEPEND = 

ifdef _WRS_CONFIG_SECURITY_MISC_2_0_2_5_SEC_HASH_2_0_2_5
VSBL_SECURITY_MISC_SEC_HASH_SRC += SECURITY_MISC_SEC_HASH
SECURITY_MISC_SEC_HASH_FASTBUILD = YES
VSBL_SECURITY_MISC_SEC_HASH_PATH = $(WIND_BASE)/os/security/security_misc/secHash
VSBL_SECURITY_MISC_SEC_HASH_VERSION = SECURITY_MISC_2_0_2_5_SEC_HASH_2_0_2_5
endif
endif

