# Automatically generated file: do not edit

##########################
# USER_MANAGEMENT_LDAP Section
##########################


ifdef _WRS_CONFIG_USER_MANAGEMENT_LDAP
VSBL_USER_MANAGEMENT_LDAP_SRC = 
VSBL_USER_MANAGEMENT_LDAP_DEPEND = 

ifdef _WRS_CONFIG_USER_MANAGEMENT_2_0_1_7_LDAP_2_0_1_7
VSBL_USER_MANAGEMENT_LDAP_SRC += USER_MANAGEMENT_LDAP
VSBL_USER_MANAGEMENT_LDAP_DEPEND += LDAPC
VSBL_USER_MANAGEMENT_LDAP_DEPEND += SECURITY_MISC_SEC_CRYPTO
VSBL_USER_MANAGEMENT_LDAP_DEPEND += UTILS_SHELL
USER_MANAGEMENT_LDAP_FASTBUILD = YES
VSBL_USER_MANAGEMENT_LDAP_PATH = $(WIND_BASE)/os/security/user_management/user_management_ldap
VSBL_USER_MANAGEMENT_LDAP_VERSION = USER_MANAGEMENT_2_0_1_7_LDAP_2_0_1_7
endif
endif

