# Automatically generated file: do not edit

##########################
# WEBCLI_WEBCLIDEMO Section
##########################


ifdef _WRS_CONFIG_WEBCLI_WEBCLIDEMO
VSBL_WEBCLI_WEBCLIDEMO_SRC = 
VSBL_WEBCLI_WEBCLIDEMO_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_2_0_1_1_WEBCLIDEMO_2_0_1_1
VSBL_WEBCLI_WEBCLIDEMO_SRC += WEBCLI_WEBCLIDEMO
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += FS_DOSFS
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += SECURITY_MISC_SEC_CRYPTO
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += WEBCLI_HTTP
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += WEBCLI_MIBWAY
WEBCLI_WEBCLIDEMO_FASTBUILD = YES
VSBL_WEBCLI_WEBCLIDEMO_PATH = $(WIND_BASE)/os/manage/webcli/webclidemo
VSBL_WEBCLI_WEBCLIDEMO_VERSION = WEBCLI_2_0_1_1_WEBCLIDEMO_2_0_1_1
endif
endif

