# Automatically generated file: do not edit

##########################
# IPNET_DHCP_CLIENT6 Section
##########################


ifdef _WRS_CONFIG_IPNET_DHCP_CLIENT6
VSBL_IPNET_DHCP_CLIENT6_SRC = 
VSBL_IPNET_DHCP_CLIENT6_DEPEND = 

ifdef _WRS_CONFIG_IPNET_DHCP_2_0_0_8_CLIENT6_2_0_0_8
VSBL_IPNET_DHCP_CLIENT6_SRC += IPNET_DHCP_CLIENT6
VSBL_IPNET_DHCP_CLIENT6_DEPEND += IPNET_COREIP
VSBL_IPNET_DHCP_CLIENT6_DEPEND += IPNET_DNSC
VSBL_IPNET_DHCP_CLIENT6_DEPEND += SECURITY_MISC_SEC_HASH
IPNET_DHCP_CLIENT6_FASTBUILD = YES
VSBL_IPNET_DHCP_CLIENT6_PATH = $(WIND_BASE)/os/net/ipnet/app/dhcp/dhcpc6
VSBL_IPNET_DHCP_CLIENT6_VERSION = IPNET_DHCP_2_0_0_8_CLIENT6_2_0_0_8
endif
endif

