# Automatically generated file: do not edit

##########################
# UTILS_OSTOOLS Section
##########################


ifdef _WRS_CONFIG_UTILS_OSTOOLS
VSBL_UTILS_OSTOOLS_SRC = 
VSBL_UTILS_OSTOOLS_DEPEND = 

ifdef _WRS_CONFIG_UTILS_2_0_8_0_OSTOOLS_2_0_8_0
VSBL_UTILS_OSTOOLS_SRC += UTILS_OSTOOLS
VSBL_UTILS_OSTOOLS_DEPEND += CORE
VSBL_UTILS_OSTOOLS_DEPEND += CORE
UTILS_OSTOOLS_FASTBUILD = YES
VSBL_UTILS_OSTOOLS_PATH = $(WIND_BASE)/os/utils/ostools
VSBL_UTILS_OSTOOLS_VERSION = UTILS_2_0_8_0_OSTOOLS_2_0_8_0
endif
endif

