# Automatically generated file: do not edit

##########################
# IPNET_LINKPROTO Section
##########################


ifdef _WRS_CONFIG_IPNET_LINKPROTO
VSBL_IPNET_LINKPROTO_SRC = 
VSBL_IPNET_LINKPROTO_DEPEND = 

ifdef _WRS_CONFIG_IPNET_LINKPROTO_2_0_0_8
VSBL_IPNET_LINKPROTO_SRC += IPNET_LINKPROTO
VSBL_IPNET_LINKPROTO_DEPEND += IPNET_COREIP
VSBL_IPNET_LINKPROTO_DEPEND += NET_BASE
IPNET_LINKPROTO_FASTBUILD = YES
VSBL_IPNET_LINKPROTO_PATH = $(WIND_BASE)/os/net/ipnet/linkproto
VSBL_IPNET_LINKPROTO_VERSION = IPNET_LINKPROTO_2_0_0_8
endif
endif

