# Automatically generated file: do not edit

##########################
# IPNET_COREIP Section
##########################


ifdef _WRS_CONFIG_IPNET_COREIP
VSBL_IPNET_COREIP_SRC = 
VSBL_IPNET_COREIP_DEPEND = 

ifdef _WRS_CONFIG_IPNET_COREIP_2_1_4_0
VSBL_IPNET_COREIP_SRC += IPNET_COREIP
VSBL_IPNET_COREIP_DEPEND += END
VSBL_IPNET_COREIP_DEPEND += SECURITY_MISC
VSBL_IPNET_COREIP_DEPEND += LIBC_STD
VSBL_IPNET_COREIP_DEPEND += NET_BASE
VSBL_IPNET_COREIP_DEPEND += SERVICE_SOCKET
VSBL_IPNET_COREIP_DEPEND += NET_BASE
VSBL_IPNET_COREIP_DEPEND += NET_BASE
VSBL_IPNET_COREIP_DEPEND += OPENSSL
VSBL_IPNET_COREIP_DEPEND += NET_BASE
VSBL_IPNET_COREIP_DEPEND += CORE
VSBL_IPNET_COREIP_DEPEND += SERVICE_SOCKET
VSBL_IPNET_COREIP_DEPEND += NET_BASE
VSBL_IPNET_COREIP_DEPEND += SERVICE_SOCKET
IPNET_COREIP_FASTBUILD = YES
VSBL_IPNET_COREIP_PATH = $(WIND_BASE)/os/net/ipnet/coreip
VSBL_IPNET_COREIP_VERSION = IPNET_COREIP_2_1_4_0
endif
endif

