# Automatically generated file: do not edit

##########################
# RENESAS_RCAR Section
##########################


ifdef _WRS_CONFIG_RENESAS_RCAR
VSBL_RENESAS_RCAR_SRC = 
VSBL_RENESAS_RCAR_DEPEND = 

ifdef _WRS_CONFIG_RENESAS_RCAR_2_0_3_2
VSBL_RENESAS_RCAR_SRC += RENESAS_RCAR
VSBL_RENESAS_RCAR_DEPEND += FDT
VSBL_RENESAS_RCAR_DEPEND += RENESAS_COMMON
VSBL_RENESAS_RCAR_DEPEND += UTILS
VSBL_RENESAS_RCAR_DEPEND += VXBUS
VSBL_RENESAS_RCAR_DEPEND += CORE
VSBL_RENESAS_RCAR_DEPEND += ARM
RENESAS_RCAR_FASTBUILD = YES
VSBL_RENESAS_RCAR_PATH = $(WIND_BASE)/os/psl/renesas/renesas_rcar
VSBL_RENESAS_RCAR_VERSION = RENESAS_RCAR_2_0_3_2
endif
endif

