# Automatically generated file: do not edit

##########################
# IPNET_DHCP_RELAY Section
##########################


ifdef _WRS_CONFIG_IPNET_DHCP_RELAY
VSBL_IPNET_DHCP_RELAY_SRC = 
VSBL_IPNET_DHCP_RELAY_DEPEND = 

ifdef _WRS_CONFIG_IPNET_DHCP_2_0_0_8_RELAY_2_0_0_8
VSBL_IPNET_DHCP_RELAY_SRC += IPNET_DHCP_RELAY
VSBL_IPNET_DHCP_RELAY_DEPEND += IPNET_COREIP
VSBL_IPNET_DHCP_RELAY_DEPEND += SECURITY_MISC_SEC_HASH
IPNET_DHCP_RELAY_FASTBUILD = YES
VSBL_IPNET_DHCP_RELAY_PATH = $(WIND_BASE)/os/net/ipnet/app/dhcp/dhcpr
VSBL_IPNET_DHCP_RELAY_VERSION = IPNET_DHCP_2_0_0_8_RELAY_2_0_0_8
endif
endif

