# Automatically generated file: do not edit

##########################
# GPUDEV_FSLVIVGPU Section
##########################


ifdef _WRS_CONFIG_GPUDEV_FSLVIVGPU
VSBL_GPUDEV_FSLVIVGPU_SRC = 
VSBL_GPUDEV_FSLVIVGPU_DEPEND = 

ifdef _WRS_CONFIG_GPUDEV_2_0_0_0_FSLVIVGPU_5_0_11_8_17
VSBL_GPUDEV_FSLVIVGPU_SRC += GPUDEV_FSLVIVGPU
VSBL_GPUDEV_FSLVIVGPU_DEPEND += FBDEV
VSBL_GPUDEV_FSLVIVGPU_DEPEND += KHRONOS
VSBL_GPUDEV_FSLVIVGPU_DEPEND += CORE
GPUDEV_FSLVIVGPU_FASTBUILD = YES
VSBL_GPUDEV_FSLVIVGPU_PATH = $(WIND_BASE)/os/multimedia/gpudev/fslviv
VSBL_GPUDEV_FSLVIVGPU_VERSION = GPUDEV_2_0_0_0_FSLVIVGPU_5_0_11_8_17
endif
endif

