# Automatically generated file: do not edit

##########################
# GPUDEV_NXPVIVGPU Section
##########################


ifdef _WRS_CONFIG_GPUDEV_NXPVIVGPU
VSBL_GPUDEV_NXPVIVGPU_SRC = 
VSBL_GPUDEV_NXPVIVGPU_DEPEND = 

ifdef _WRS_CONFIG_GPUDEV_2_0_0_0_NXPVIVGPU_6_2_4_4_2
VSBL_GPUDEV_NXPVIVGPU_SRC += GPUDEV_NXPVIVGPU
VSBL_GPUDEV_NXPVIVGPU_DEPEND += FBDEV
VSBL_GPUDEV_NXPVIVGPU_DEPEND += CORE
VSBL_GPUDEV_NXPVIVGPU_DEPEND += KHRONOS
GPUDEV_NXPVIVGPU_FASTBUILD = YES
VSBL_GPUDEV_NXPVIVGPU_PATH = $(WIND_BASE)/os/multimedia/gpudev/nxpviv
VSBL_GPUDEV_NXPVIVGPU_VERSION = GPUDEV_2_0_0_0_NXPVIVGPU_6_2_4_4_2
endif
endif

