# Automatically generated file: do not edit

##########################
# FSL_KINETIS Section
##########################


ifdef _WRS_CONFIG_FSL_KINETIS
VSBL_FSL_KINETIS_SRC = 
VSBL_FSL_KINETIS_DEPEND = 

ifdef _WRS_CONFIG_FSL_KINETIS_2_1_1_2
VSBL_FSL_KINETIS_SRC += FSL_KINETIS
VSBL_FSL_KINETIS_DEPEND += FDT
VSBL_FSL_KINETIS_DEPEND += UTILS
VSBL_FSL_KINETIS_DEPEND += VXBUS
VSBL_FSL_KINETIS_DEPEND += VXBUS
FSL_KINETIS_FASTBUILD = YES
VSBL_FSL_KINETIS_PATH = $(WIND_BASE)/os/psl/freescale/fsl_kinetis
VSBL_FSL_KINETIS_VERSION = FSL_KINETIS_2_1_1_2
endif
endif

