# Automatically generated file: do not edit

##########################
# IPNET_ROUTEPROTO Section
##########################


ifdef _WRS_CONFIG_IPNET_ROUTEPROTO
VSBL_IPNET_ROUTEPROTO_SRC = 
VSBL_IPNET_ROUTEPROTO_DEPEND = 

ifdef _WRS_CONFIG_IPNET_ROUTEPROTO_2_0_0_5
VSBL_IPNET_ROUTEPROTO_SRC += IPNET_ROUTEPROTO
VSBL_IPNET_ROUTEPROTO_DEPEND += IPNET_COREIP
IPNET_ROUTEPROTO_FASTBUILD = YES
VSBL_IPNET_ROUTEPROTO_PATH = $(WIND_BASE)/os/net/ipnet/routeproto
VSBL_IPNET_ROUTEPROTO_VERSION = IPNET_ROUTEPROTO_2_0_0_5
endif
endif

