# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_THROTTLE Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_THROTTLE
VSBL_GUEST_SUPPORT_VX7_THROTTLE_SRC = 
VSBL_GUEST_SUPPORT_VX7_THROTTLE_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_1_0_1_3_THROTTLE_1_0_1_3
VSBL_GUEST_SUPPORT_VX7_THROTTLE_SRC += GUEST_SUPPORT_VX7_THROTTLE
VSBL_GUEST_SUPPORT_VX7_THROTTLE_DEPEND += GUEST_SUPPORT_VX7_HVIF
GUEST_SUPPORT_VX7_THROTTLE_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_THROTTLE_PATH = $(WIND_BASE)/os/hv/guest_support_vx7/throttle
VSBL_GUEST_SUPPORT_VX7_THROTTLE_VERSION = GUEST_SUPPORT_VX7_1_0_1_3_THROTTLE_1_0_1_3
endif
endif

