# Automatically generated file: do not edit

##########################
# FSL_S32 Section
##########################


ifdef _WRS_CONFIG_FSL_S32
VSBL_FSL_S32_SRC = 
VSBL_FSL_S32_DEPEND = 

ifdef _WRS_CONFIG_FSL_S32_1_0_4_2
VSBL_FSL_S32_SRC += FSL_S32
VSBL_FSL_S32_DEPEND += FDT
VSBL_FSL_S32_DEPEND += SERVICE_JOBQUEUE
VSBL_FSL_S32_DEPEND += UTILS
VSBL_FSL_S32_DEPEND += VXBUS
VSBL_FSL_S32_DEPEND += CORE
VSBL_FSL_S32_DEPEND += ARM
FSL_S32_FASTBUILD = YES
VSBL_FSL_S32_PATH = $(WIND_BASE)/os/psl/freescale/fsl_s32
VSBL_FSL_S32_VERSION = FSL_S32_1_0_4_2
endif
endif

