# Automatically generated file: do not edit

##########################
# SERVICE_REMOTEPROC Section
##########################


ifdef _WRS_CONFIG_SERVICE_REMOTEPROC
VSBL_SERVICE_REMOTEPROC_SRC = 
VSBL_SERVICE_REMOTEPROC_DEPEND = 

ifdef _WRS_CONFIG_SERVICE_4_0_1_1_REMOTEPROC_4_0_1_1
VSBL_SERVICE_REMOTEPROC_SRC += SERVICE_REMOTEPROC
SERVICE_REMOTEPROC_FASTBUILD = YES
VSBL_SERVICE_REMOTEPROC_PATH = $(WIND_BASE)/os/service/remoteproc
VSBL_SERVICE_REMOTEPROC_VERSION = SERVICE_4_0_1_1_REMOTEPROC_4_0_1_1
endif
endif

