# Automatically generated file: do not edit

##########################
# SERVICE Section
##########################


ifdef _WRS_CONFIG_SERVICE
VSBL_SERVICE_SRC = 
VSBL_SERVICE_DEPEND = 

ifdef _WRS_CONFIG_SERVICE_4_0_1_1
ifdef _WRS_CONFIG_SERVICE_EPOLL
VSBL_SERVICE_SRC += SERVICE_EPOLL
endif
ifdef _WRS_CONFIG_SERVICE_ERF
VSBL_SERVICE_SRC += SERVICE_ERF
endif
ifdef _WRS_CONFIG_SERVICE_JOBQUEUE
VSBL_SERVICE_SRC += SERVICE_JOBQUEUE
endif
ifdef _WRS_CONFIG_SERVICE_REMOTEPROC
VSBL_SERVICE_SRC += SERVICE_REMOTEPROC
endif
ifdef _WRS_CONFIG_SERVICE_RPC
VSBL_SERVICE_SRC += SERVICE_RPC
endif
ifdef _WRS_CONFIG_SERVICE_RPMSG
VSBL_SERVICE_SRC += SERVICE_RPMSG
endif
ifdef _WRS_CONFIG_SERVICE_SOCKET
VSBL_SERVICE_SRC += SERVICE_SOCKET
endif
ifdef _WRS_CONFIG_SERVICE_UN
VSBL_SERVICE_SRC += SERVICE_UN
endif
VSBL_SERVICE_SRC += SERVICE
VSBL_SERVICE_DEPEND += CORE
SERVICE_FASTBUILD = YES
VSBL_SERVICE_PATH = $(WIND_BASE)/os/service
VSBL_SERVICE_VERSION = SERVICE_4_0_1_1
endif
endif

