# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_VIRTIO Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_VIRTIO
VSBL_GUEST_SUPPORT_VX7_VIRTIO_SRC = 
VSBL_GUEST_SUPPORT_VX7_VIRTIO_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_1_0_1_3_VIRTIO_1_0_1_3
VSBL_GUEST_SUPPORT_VX7_VIRTIO_SRC += GUEST_SUPPORT_VX7_VIRTIO
VSBL_GUEST_SUPPORT_VX7_VIRTIO_DEPEND += GUEST_SUPPORT_VX7_HVIF
VSBL_GUEST_SUPPORT_VX7_VIRTIO_DEPEND += IPNET_COREIP
GUEST_SUPPORT_VX7_VIRTIO_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_VIRTIO_PATH = $(WIND_BASE)/os/hv/guest_support_vx7/virtio
VSBL_GUEST_SUPPORT_VX7_VIRTIO_VERSION = GUEST_SUPPORT_VX7_1_0_1_3_VIRTIO_1_0_1_3
endif
endif

