# Automatically generated file: do not edit

##########################
# TILCON Section
##########################


ifdef _WRS_CONFIG_TILCON
VSBL_TILCON_SRC = 
VSBL_TILCON_DEPEND = 

ifdef _WRS_CONFIG_TILCON_7_0_0_24
VSBL_TILCON_SRC += TILCON
VSBL_TILCON_DEPEND += EVDEV
VSBL_TILCON_DEPEND += FBDEV
VSBL_TILCON_DEPEND += FREETYPE2
VSBL_TILCON_DEPEND += KHRONOS
VSBL_TILCON_DEPEND += LIBJPEG
VSBL_TILCON_DEPEND += LIBPNG
TILCON_FASTBUILD = YES
VSBL_TILCON_PATH = $(WIND_BASE)/os/multimedia/tilcon
VSBL_TILCON_VERSION = TILCON_7_0_0_24
endif
endif

