# Automatically generated file: do not edit

##########################
# ITL_SOC_ARRIA10 Section
##########################


ifdef _WRS_CONFIG_ITL_SOC_ARRIA10
VSBL_ITL_SOC_ARRIA10_SRC = 
VSBL_ITL_SOC_ARRIA10_DEPEND = 

ifdef _WRS_CONFIG_ITL_SOC_ARRIA10_1_0_3_2
VSBL_ITL_SOC_ARRIA10_SRC += ITL_SOC_ARRIA10
VSBL_ITL_SOC_ARRIA10_DEPEND += FDT
VSBL_ITL_SOC_ARRIA10_DEPEND += VXBUS
VSBL_ITL_SOC_ARRIA10_DEPEND += CORE
VSBL_ITL_SOC_ARRIA10_DEPEND += ARM
ITL_SOC_ARRIA10_FASTBUILD = YES
VSBL_ITL_SOC_ARRIA10_PATH = $(WIND_BASE)/os/psl/intel/itl_soc_arria10
VSBL_ITL_SOC_ARRIA10_VERSION = ITL_SOC_ARRIA10_1_0_3_2
endif
endif

