# Automatically generated file: do not edit

##########################
# IPNET_DHCP_CLIENT Section
##########################


ifdef _WRS_CONFIG_IPNET_DHCP_CLIENT
VSBL_IPNET_DHCP_CLIENT_SRC = 
VSBL_IPNET_DHCP_CLIENT_DEPEND = 

ifdef _WRS_CONFIG_IPNET_DHCP_2_0_0_8_CLIENT_2_0_0_8
VSBL_IPNET_DHCP_CLIENT_SRC += IPNET_DHCP_CLIENT
VSBL_IPNET_DHCP_CLIENT_DEPEND += IPNET_COREIP
IPNET_DHCP_CLIENT_FASTBUILD = YES
VSBL_IPNET_DHCP_CLIENT_PATH = $(WIND_BASE)/os/net/ipnet/app/dhcp/dhcpc
VSBL_IPNET_DHCP_CLIENT_VERSION = IPNET_DHCP_2_0_0_8_CLIENT_2_0_0_8
endif
endif

