# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_SAFE_APEX Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_APEX
VSBL_GUEST_SUPPORT_VX7_SAFE_APEX_SRC = 
VSBL_GUEST_SUPPORT_VX7_SAFE_APEX_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_1_0_3_6_APEX_1_0_3_6
VSBL_GUEST_SUPPORT_VX7_SAFE_APEX_SRC += GUEST_SUPPORT_VX7_SAFE_APEX
GUEST_SUPPORT_VX7_SAFE_APEX_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_SAFE_APEX_PATH = $(WIND_BASE)/os/hv/guest_support_vx7_safe/apex
VSBL_GUEST_SUPPORT_VX7_SAFE_APEX_VERSION = GUEST_SUPPORT_VX7_SAFE_1_0_3_6_APEX_1_0_3_6
endif
endif

