# Automatically generated file: do not edit

##########################
# RTTOOLS_RUNTIME_ANALYSIS Section
##########################


ifdef _WRS_CONFIG_RTTOOLS_RUNTIME_ANALYSIS
VSBL_RTTOOLS_RUNTIME_ANALYSIS_SRC = 
VSBL_RTTOOLS_RUNTIME_ANALYSIS_DEPEND = 

ifdef _WRS_CONFIG_RTTOOLS_2_0_1_7_RUNTIME_ANALYSIS_2_0_1_7
VSBL_RTTOOLS_RUNTIME_ANALYSIS_SRC += RTTOOLS_RUNTIME_ANALYSIS
VSBL_RTTOOLS_RUNTIME_ANALYSIS_DEPEND += DEBUG_SYSTEMVIEWER
VSBL_RTTOOLS_RUNTIME_ANALYSIS_DEPEND += RTTOOLS_DEBUG_AGENT
RTTOOLS_RUNTIME_ANALYSIS_FASTBUILD = YES
VSBL_RTTOOLS_RUNTIME_ANALYSIS_PATH = $(WIND_BASE)/os/debug_analysis/rttools/cafe
VSBL_RTTOOLS_RUNTIME_ANALYSIS_VERSION = RTTOOLS_2_0_1_7_RUNTIME_ANALYSIS_2_0_1_7
endif
endif

