# Automatically generated file: do not edit

##########################
# INTRINSICS_COMMON Section
##########################


ifdef _WRS_CONFIG_INTRINSICS_COMMON
VSBL_INTRINSICS_COMMON_SRC = 
VSBL_INTRINSICS_COMMON_DEPEND = 

ifdef _WRS_CONFIG_INTRINSICS_COMMON_1_0_1_5
VSBL_INTRINSICS_COMMON_SRC += INTRINSICS_COMMON
VSBL_INTRINSICS_COMMON_DEPEND += LIBC_STD
VSBL_INTRINSICS_COMMON_DEPEND += CORE
INTRINSICS_COMMON_FASTBUILD = YES
VSBL_INTRINSICS_COMMON_PATH = $(WIND_BASE)/os/lang_lib/tool/intrinsics_common
VSBL_INTRINSICS_COMMON_VERSION = INTRINSICS_COMMON_1_0_1_5
endif
endif

