# Automatically generated file: do not edit

##########################
# XLNX_COMMON Section
##########################


ifdef _WRS_CONFIG_XLNX_COMMON
VSBL_XLNX_COMMON_SRC = 
VSBL_XLNX_COMMON_DEPEND = 

ifdef _WRS_CONFIG_XLNX_COMMON_1_0_1_1
VSBL_XLNX_COMMON_SRC += XLNX_COMMON
VSBL_XLNX_COMMON_DEPEND += FDT
VSBL_XLNX_COMMON_DEPEND += UTILS
VSBL_XLNX_COMMON_DEPEND += VXBUS
VSBL_XLNX_COMMON_DEPEND += CORE
VSBL_XLNX_COMMON_DEPEND += ARM
XLNX_COMMON_FASTBUILD = YES
VSBL_XLNX_COMMON_PATH = $(WIND_BASE)/os/psl/xilinx/xlnx_common
VSBL_XLNX_COMMON_VERSION = XLNX_COMMON_1_0_1_1
endif
endif

