# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_DSS Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_DSS
VSBL_GUEST_SUPPORT_VX7_DSS_SRC = 
VSBL_GUEST_SUPPORT_VX7_DSS_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_1_0_1_3_DSS_1_0_1_3
VSBL_GUEST_SUPPORT_VX7_DSS_SRC += GUEST_SUPPORT_VX7_DSS
GUEST_SUPPORT_VX7_DSS_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_DSS_PATH = $(WIND_BASE)/os/hv/guest_support_vx7/debugsocket
VSBL_GUEST_SUPPORT_VX7_DSS_VERSION = GUEST_SUPPORT_VX7_1_0_1_3_DSS_1_0_1_3
endif
endif

