# Automatically generated file: do not edit

##########################
# CRYPTOMISC Section
##########################


ifdef _WRS_CONFIG_CRYPTOMISC
VSBL_CRYPTOMISC_SRC = 
VSBL_CRYPTOMISC_DEPEND = 

ifdef _WRS_CONFIG_CRYPTOMISC_2_0_2_6
ifdef _WRS_CONFIG_CRYPTOMISC_IAF
VSBL_CRYPTOMISC_SRC += CRYPTOMISC_IAF
endif
ifdef _WRS_CONFIG_CRYPTOMISC_IPFREESCALE
VSBL_CRYPTOMISC_SRC += CRYPTOMISC_IPFREESCALE
endif
ifdef _WRS_CONFIG_CRYPTOMISC_IPHWCRYPTO
VSBL_CRYPTOMISC_SRC += CRYPTOMISC_IPHWCRYPTO
endif
ifdef _WRS_CONFIG_CRYPTOMISC_TPM
VSBL_CRYPTOMISC_SRC += CRYPTOMISC_TPM
endif
VSBL_CRYPTOMISC_SRC += CRYPTOMISC
VSBL_CRYPTOMISC_DEPEND += SECURITY_MISC_SEC_CRYPTO
VSBL_CRYPTOMISC_DEPEND += SERVICE_SOCKET
VSBL_CRYPTOMISC_DEPEND += OPENSSL
CRYPTOMISC_FASTBUILD = YES
VSBL_CRYPTOMISC_PATH = $(WIND_BASE)/os/security/crypto_misc
VSBL_CRYPTOMISC_VERSION = CRYPTOMISC_2_0_2_6
endif
endif

