# Automatically generated file: do not edit

##########################
# TCPLAY Section
##########################


ifdef _WRS_CONFIG_TCPLAY
VSBL_TCPLAY_SRC = 
VSBL_TCPLAY_DEPEND = 

ifdef _WRS_CONFIG_TCPLAY_2_0_3_5
VSBL_TCPLAY_SRC += TCPLAY
VSBL_TCPLAY_DEPEND += BDM
VSBL_TCPLAY_DEPEND += FS
VSBL_TCPLAY_DEPEND += SECURITY_MISC_SEC_CRYPTO
VSBL_TCPLAY_DEPEND += SECURITY_MISC_SEC_HASH
VSBL_TCPLAY_DEPEND += SERVICE_ERF
TCPLAY_FASTBUILD = YES
VSBL_TCPLAY_PATH = $(WIND_BASE)/contrib/tcplay-2.0.3
VSBL_TCPLAY_VERSION = TCPLAY_2_0_3_5
endif
endif

