# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_SAFE_HM Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_HM
VSBL_GUEST_SUPPORT_VX7_SAFE_HM_SRC = 
VSBL_GUEST_SUPPORT_VX7_SAFE_HM_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_1_0_3_6_HM_1_0_3_6
VSBL_GUEST_SUPPORT_VX7_SAFE_HM_SRC += GUEST_SUPPORT_VX7_SAFE_HM
GUEST_SUPPORT_VX7_SAFE_HM_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_SAFE_HM_PATH = $(WIND_BASE)/os/hv/guest_support_vx7_safe/hm
VSBL_GUEST_SUPPORT_VX7_SAFE_HM_VERSION = GUEST_SUPPORT_VX7_SAFE_1_0_3_6_HM_1_0_3_6
endif
endif

