# Automatically generated file: do not edit

##########################
# RENESAS_RZ_G2 Section
##########################


ifdef _WRS_CONFIG_RENESAS_RZ_G2
VSBL_RENESAS_RZ_G2_SRC = 
VSBL_RENESAS_RZ_G2_DEPEND = 

ifdef _WRS_CONFIG_RENESAS_RZ_G2_0_1_0_0
VSBL_RENESAS_RZ_G2_SRC += RENESAS_RZ_G2
VSBL_RENESAS_RZ_G2_DEPEND += FDT
VSBL_RENESAS_RZ_G2_DEPEND += PSCI
VSBL_RENESAS_RZ_G2_DEPEND += UTILS
VSBL_RENESAS_RZ_G2_DEPEND += VXBUS
VSBL_RENESAS_RZ_G2_DEPEND += CORE
VSBL_RENESAS_RZ_G2_DEPEND += ARM
RENESAS_RZ_G2_FASTBUILD = YES
VSBL_RENESAS_RZ_G2_PATH = $(WIND_BASE)/os/unsupported/renesas_rz_g2/renesas_rz_g2
VSBL_RENESAS_RZ_G2_VERSION = RENESAS_RZ_G2_0_1_0_0
endif
endif

