# Automatically generated file: do not edit

##########################
# IPNET_DHCP_SERVER6 Section
##########################


ifdef _WRS_CONFIG_IPNET_DHCP_SERVER6
VSBL_IPNET_DHCP_SERVER6_SRC = 
VSBL_IPNET_DHCP_SERVER6_DEPEND = 

ifdef _WRS_CONFIG_IPNET_DHCP_2_0_0_8_SERVER6_2_0_0_8
VSBL_IPNET_DHCP_SERVER6_SRC += IPNET_DHCP_SERVER6
VSBL_IPNET_DHCP_SERVER6_DEPEND += IPNET_COREIP
VSBL_IPNET_DHCP_SERVER6_DEPEND += IPNET_DNSC
VSBL_IPNET_DHCP_SERVER6_DEPEND += SECURITY_MISC_SEC_HASH
IPNET_DHCP_SERVER6_FASTBUILD = YES
VSBL_IPNET_DHCP_SERVER6_PATH = $(WIND_BASE)/os/net/ipnet/app/dhcp/dhcps6
VSBL_IPNET_DHCP_SERVER6_VERSION = IPNET_DHCP_2_0_0_8_SERVER6_2_0_0_8
endif
endif

