# Automatically generated file: do not edit

##########################
# SECURITY_MISC_SEC_CRYPTO Section
##########################


ifdef _WRS_CONFIG_SECURITY_MISC_SEC_CRYPTO
VSBL_SECURITY_MISC_SEC_CRYPTO_SRC = 
VSBL_SECURITY_MISC_SEC_CRYPTO_DEPEND = 

ifdef _WRS_CONFIG_SECURITY_MISC_2_0_2_5_SEC_CRYPTO_2_0_2_5
VSBL_SECURITY_MISC_SEC_CRYPTO_SRC += SECURITY_MISC_SEC_CRYPTO
VSBL_SECURITY_MISC_SEC_CRYPTO_DEPEND += FS
VSBL_SECURITY_MISC_SEC_CRYPTO_DEPEND += OPENSSL
VSBL_SECURITY_MISC_SEC_CRYPTO_DEPEND += SERVICE_SOCKET
SECURITY_MISC_SEC_CRYPTO_FASTBUILD = YES
SECURITY_MISC_SEC_CRYPTO_FRIEND = DISK_ENCRYPTION SECURE_LOADER
VSBL_SECURITY_MISC_SEC_CRYPTO_PATH = $(WIND_BASE)/os/security/security_misc/secCrypto
VSBL_SECURITY_MISC_SEC_CRYPTO_VERSION = SECURITY_MISC_2_0_2_5_SEC_CRYPTO_2_0_2_5
endif
endif

