# Automatically generated file: do not edit

##########################
# IPNET_DHCP_SERVER Section
##########################


ifdef _WRS_CONFIG_IPNET_DHCP_SERVER
VSBL_IPNET_DHCP_SERVER_SRC = 
VSBL_IPNET_DHCP_SERVER_DEPEND = 

ifdef _WRS_CONFIG_IPNET_DHCP_2_0_0_8_SERVER_2_0_0_8
VSBL_IPNET_DHCP_SERVER_SRC += IPNET_DHCP_SERVER
VSBL_IPNET_DHCP_SERVER_DEPEND += IPNET_COREIP
VSBL_IPNET_DHCP_SERVER_DEPEND += SECURITY_MISC_SEC_HASH
IPNET_DHCP_SERVER_FASTBUILD = YES
VSBL_IPNET_DHCP_SERVER_PATH = $(WIND_BASE)/os/net/ipnet/app/dhcp/dhcps
VSBL_IPNET_DHCP_SERVER_VERSION = IPNET_DHCP_2_0_0_8_SERVER_2_0_0_8
endif
endif

