# Automatically generated file: do not edit

##########################
# USB Section
##########################


ifdef _WRS_CONFIG_USB
VSBL_USB_SRC = 
VSBL_USB_DEPEND = 

ifdef _WRS_CONFIG_USB_2_0_8_0
ifdef _WRS_CONFIG_USB_CTLR
VSBL_USB_SRC += USB_CTLR
endif
ifdef _WRS_CONFIG_USB_CDNSUSB3
VSBL_USB_SRC += USB_CDNSUSB3
endif
ifdef _WRS_CONFIG_USB_DWC2DR
VSBL_USB_SRC += USB_DWC2DR
endif
ifdef _WRS_CONFIG_USB_USBDWC3
VSBL_USB_SRC += USB_USBDWC3
endif
ifdef _WRS_CONFIG_USB_EHCI
VSBL_USB_SRC += USB_EHCI
endif
ifdef _WRS_CONFIG_USB_FSLDR
VSBL_USB_SRC += USB_FSLDR
endif
ifdef _WRS_CONFIG_USB_MHDRC
VSBL_USB_SRC += USB_MHDRC
endif
ifdef _WRS_CONFIG_USB_OHCI
VSBL_USB_SRC += USB_OHCI
endif
ifdef _WRS_CONFIG_USB_PCHUDC
VSBL_USB_SRC += USB_PCHUDC
endif
ifdef _WRS_CONFIG_USB_PLX
VSBL_USB_SRC += USB_PLX
endif
ifdef _WRS_CONFIG_USB_RZN1
VSBL_USB_SRC += USB_RZN1
endif
ifdef _WRS_CONFIG_USB_UHCI
VSBL_USB_SRC += USB_UHCI
endif
ifdef _WRS_CONFIG_USB_XHCI
VSBL_USB_SRC += USB_XHCI
endif
ifdef _WRS_CONFIG_USB_HOST
VSBL_USB_SRC += USB_HOST
endif
ifdef _WRS_CONFIG_USB_NETWORK
VSBL_USB_SRC += USB_NETWORK
endif
ifdef _WRS_CONFIG_USB_STORAGE
VSBL_USB_SRC += USB_STORAGE
endif
ifdef _WRS_CONFIG_USB_TOUCHSCREEN
VSBL_USB_SRC += USB_TOUCHSCREEN
endif
ifdef _WRS_CONFIG_USB_OTG
VSBL_USB_SRC += USB_OTG
endif
ifdef _WRS_CONFIG_USB_PHY
VSBL_USB_SRC += USB_PHY
endif
ifdef _WRS_CONFIG_USB_TARGET
VSBL_USB_SRC += USB_TARGET
endif
ifdef _WRS_CONFIG_USB_MSC
VSBL_USB_SRC += USB_MSC
endif
ifdef _WRS_CONFIG_USB_NET
VSBL_USB_SRC += USB_NET
endif
ifdef _WRS_CONFIG_USB_TYPEC
VSBL_USB_SRC += USB_TYPEC
endif
VSBL_USB_SRC += USB
VSBL_USB_DEPEND += LIBC_STD
USB_FASTBUILD = YES
VSBL_USB_PATH = $(WIND_BASE)/os/connectivity/usb
VSBL_USB_VERSION = USB_2_0_8_0
endif
endif

