# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_SAFE_MPFS Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_MPFS
VSBL_GUEST_SUPPORT_VX7_SAFE_MPFS_SRC = 
VSBL_GUEST_SUPPORT_VX7_SAFE_MPFS_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_1_0_3_6_MPFS_1_0_3_6
VSBL_GUEST_SUPPORT_VX7_SAFE_MPFS_SRC += GUEST_SUPPORT_VX7_SAFE_MPFS
VSBL_GUEST_SUPPORT_VX7_SAFE_MPFS_DEPEND += GUEST_SUPPORT_VX7_SAFE_SAFEIPC
GUEST_SUPPORT_VX7_SAFE_MPFS_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_SAFE_MPFS_PATH = $(WIND_BASE)/os/hv/guest_support_vx7_safe/mpfs
VSBL_GUEST_SUPPORT_VX7_SAFE_MPFS_VERSION = GUEST_SUPPORT_VX7_SAFE_1_0_3_6_MPFS_1_0_3_6
endif
endif

