# Automatically generated file: do not edit

##########################
# INTRINSICS_LLVM Section
##########################


ifdef _WRS_CONFIG_INTRINSICS_LLVM
VSBL_INTRINSICS_LLVM_SRC = 
VSBL_INTRINSICS_LLVM_DEPEND = 

ifdef _WRS_CONFIG_INTRINSICS_LLVM_1_0_6_0
VSBL_INTRINSICS_LLVM_SRC += INTRINSICS_LLVM
VSBL_INTRINSICS_LLVM_DEPEND += CORE
VSBL_INTRINSICS_LLVM_DEPEND += LIBCPLUS_STD
VSBL_INTRINSICS_LLVM_DEPEND += LIBC_STD
VSBL_INTRINSICS_LLVM_DEPEND += LIBC_STD
INTRINSICS_LLVM_FASTBUILD = YES
VSBL_INTRINSICS_LLVM_PATH = $(WIND_BASE)/os/lang_lib/tool/intrinsics_llvm
VSBL_INTRINSICS_LLVM_VERSION = INTRINSICS_LLVM_1_0_6_0
endif
endif

