# Automatically generated file: do not edit

##########################
# RTTOOLS_SYSTEMVIEWER_AGENT Section
##########################


ifdef _WRS_CONFIG_RTTOOLS_SYSTEMVIEWER_AGENT
VSBL_RTTOOLS_SYSTEMVIEWER_AGENT_SRC = 
VSBL_RTTOOLS_SYSTEMVIEWER_AGENT_DEPEND = 

ifdef _WRS_CONFIG_RTTOOLS_2_0_1_7_SYSTEMVIEWER_AGENT_2_0_1_7
VSBL_RTTOOLS_SYSTEMVIEWER_AGENT_SRC += RTTOOLS_SYSTEMVIEWER_AGENT
VSBL_RTTOOLS_SYSTEMVIEWER_AGENT_DEPEND += DEBUG_SYSTEMVIEWER
VSBL_RTTOOLS_SYSTEMVIEWER_AGENT_DEPEND += RTTOOLS_DEBUG_AGENT
RTTOOLS_SYSTEMVIEWER_AGENT_FASTBUILD = YES
VSBL_RTTOOLS_SYSTEMVIEWER_AGENT_PATH = $(WIND_BASE)/os/debug_analysis/rttools/systemviewer
VSBL_RTTOOLS_SYSTEMVIEWER_AGENT_VERSION = RTTOOLS_2_0_1_7_SYSTEMVIEWER_AGENT_2_0_1_7
endif
endif

