# Automatically generated file: do not edit

##########################
# PSL_XLNX_VERSAL Section
##########################


ifdef _WRS_CONFIG_PSL_XLNX_VERSAL
VSBL_PSL_XLNX_VERSAL_SRC = 
VSBL_PSL_XLNX_VERSAL_DEPEND = 

ifdef _WRS_CONFIG_PSL_XLNX_VERSAL_1_0_1_0
VSBL_PSL_XLNX_VERSAL_SRC += PSL_XLNX_VERSAL
VSBL_PSL_XLNX_VERSAL_DEPEND += FDT
VSBL_PSL_XLNX_VERSAL_DEPEND += PSCI
VSBL_PSL_XLNX_VERSAL_DEPEND += UTILS
VSBL_PSL_XLNX_VERSAL_DEPEND += VXBUS
VSBL_PSL_XLNX_VERSAL_DEPEND += XLNX_COMMON
VSBL_PSL_XLNX_VERSAL_DEPEND += CORE
VSBL_PSL_XLNX_VERSAL_DEPEND += ARM
PSL_XLNX_VERSAL_FASTBUILD = YES
VSBL_PSL_XLNX_VERSAL_PATH = $(WIND_BASE)/os/psl/xilinx/xlnx_versal
VSBL_PSL_XLNX_VERSAL_VERSION = PSL_XLNX_VERSAL_1_0_1_0
endif
endif

