# Automatically generated file: do not edit

##########################
# IPNET_USRSPACE Section
##########################


ifdef _WRS_CONFIG_IPNET_USRSPACE
VSBL_IPNET_USRSPACE_SRC = 
VSBL_IPNET_USRSPACE_DEPEND = 

ifdef _WRS_CONFIG_IPNET_USRSPACE_3_1_3_1
VSBL_IPNET_USRSPACE_SRC += IPNET_USRSPACE
VSBL_IPNET_USRSPACE_DEPEND += CORE_RTP
VSBL_IPNET_USRSPACE_DEPEND += IPNET_COREIP
VSBL_IPNET_USRSPACE_DEPEND += NET_BASE
VSBL_IPNET_USRSPACE_DEPEND += NET_BASE
VSBL_IPNET_USRSPACE_DEPEND += SERVICE_SOCKET
VSBL_IPNET_USRSPACE_DEPEND += NET_BASE
VSBL_IPNET_USRSPACE_DEPEND += NET_BASE
VSBL_IPNET_USRSPACE_DEPEND += NET_BASE
VSBL_IPNET_USRSPACE_DEPEND += NET_BASE
VSBL_IPNET_USRSPACE_DEPEND += SERVICE_SOCKET
IPNET_USRSPACE_FASTBUILD = YES
VSBL_IPNET_USRSPACE_PATH = $(WIND_BASE)/os/net/ipnet/usrspace
VSBL_IPNET_USRSPACE_VERSION = IPNET_USRSPACE_3_1_3_1
endif
endif

