# Automatically generated file: do not edit

##########################
# UTILS Section
##########################


ifdef _WRS_CONFIG_UTILS
VSBL_UTILS_SRC = 
VSBL_UTILS_DEPEND = 

ifdef _WRS_CONFIG_UTILS_2_0_8_0
ifdef _WRS_CONFIG_UTILS_BOOTAPP
VSBL_UTILS_SRC += UTILS_BOOTAPP
endif
ifdef _WRS_CONFIG_UTILS_DEPLOY
VSBL_UTILS_SRC += UTILS_DEPLOY
endif
ifdef _WRS_CONFIG_UTILS_LOADER
VSBL_UTILS_SRC += UTILS_LOADER
endif
ifdef _WRS_CONFIG_UTILS_OSTOOLS
VSBL_UTILS_SRC += UTILS_OSTOOLS
endif
ifdef _WRS_CONFIG_UTILS_RBUFF
VSBL_UTILS_SRC += UTILS_RBUFF
endif
ifdef _WRS_CONFIG_UTILS_RUST
VSBL_UTILS_SRC += UTILS_RUST
endif
ifdef _WRS_CONFIG_UTILS_SHELL
VSBL_UTILS_SRC += UTILS_SHELL
endif
ifdef _WRS_CONFIG_UTILS_UNIX
VSBL_UTILS_SRC += UTILS_UNIX
endif
ifdef _WRS_CONFIG_UTILS_UTF
VSBL_UTILS_SRC += UTILS_UTF
endif
ifdef _WRS_CONFIG_UTILS_UUID
VSBL_UTILS_SRC += UTILS_UUID
endif
ifdef _WRS_CONFIG_UTILS_WRCC
VSBL_UTILS_SRC += UTILS_WRCC
endif
VSBL_UTILS_SRC += UTILS
VSBL_UTILS_DEPEND += CORE
VSBL_UTILS_DEPEND += CORE
VSBL_UTILS_DEPEND += CORE
VSBL_UTILS_DEPEND += CORE
UTILS_FASTBUILD = YES
VSBL_UTILS_PATH = $(WIND_BASE)/os/utils
VSBL_UTILS_VERSION = UTILS_2_0_8_0
endif
endif

