# Automatically generated file: do not edit

##########################
# BRANSON_TIDSSFB Section
##########################


ifdef _WRS_CONFIG_BRANSON_TIDSSFB
VSBL_BRANSON_TIDSSFB_SRC = 
VSBL_BRANSON_TIDSSFB_DEPEND = 

ifdef _WRS_CONFIG_BRANSON_TIDSSFB_10_0_0_1
VSBL_BRANSON_TIDSSFB_SRC += BRANSON_TIDSSFB
VSBL_BRANSON_TIDSSFB_DEPEND += FBDEV
BRANSON_TIDSSFB_FASTBUILD = YES
VSBL_BRANSON_TIDSSFB_PATH = D:/JerryW/SoftwareRelease/Vxworks_2021.07_Test_Stream/_Branson_Driver_Layer_SR2107/BRANSON_DRV_2_0_0_0/tidss
VSBL_BRANSON_TIDSSFB_VERSION = BRANSON_TIDSSFB_10_0_0_1
endif
endif

