# Automatically generated file: do not edit

##########################
# UTILS_SHELL Section
##########################


ifdef _WRS_CONFIG_UTILS_SHELL
VSBL_UTILS_SHELL_SRC = 
VSBL_UTILS_SHELL_DEPEND = 

ifdef _WRS_CONFIG_UTILS_2_0_8_0_SHELL_2_0_8_0
VSBL_UTILS_SHELL_SRC += UTILS_SHELL
VSBL_UTILS_SHELL_DEPEND += UTILS_OSTOOLS
VSBL_UTILS_SHELL_DEPEND += CORE
VSBL_UTILS_SHELL_DEPEND += CORE
VSBL_UTILS_SHELL_DEPEND += CORE
ifdef _WRS_CONFIG_DEBUG
VSBL_UTILS_SHELL_DEPEND += DEBUG
endif
ifdef _WRS_CONFIG_VXDBG*
VSBL_UTILS_SHELL_DEPEND += DEBUG
endif
UTILS_SHELL_FASTBUILD = YES
VSBL_UTILS_SHELL_PATH = $(WIND_BASE)/os/utils/shell
VSBL_UTILS_SHELL_VERSION = UTILS_2_0_8_0_SHELL_2_0_8_0
endif
endif

