# Automatically generated file: do not edit

##########################
# TENSORFLOW_LITE Section
##########################


ifdef _WRS_CONFIG_TENSORFLOW_LITE
VSBL_TENSORFLOW_LITE_SRC = 
VSBL_TENSORFLOW_LITE_DEPEND = 

ifdef _WRS_CONFIG_TENSORFLOW_LITE_2_4_0_0
VSBL_TENSORFLOW_LITE_SRC += TENSORFLOW_LITE
VSBL_TENSORFLOW_LITE_DEPEND += CORE_RTP
VSBL_TENSORFLOW_LITE_DEPEND += UTILS_DEPLOY
VSBL_TENSORFLOW_LITE_DEPEND += UTILS_WRCC
VSBL_TENSORFLOW_LITE_DEPEND += ZLIB
TENSORFLOW_LITE_FASTBUILD = YES
VSBL_TENSORFLOW_LITE_PATH = $(WIND_BASE)/contrib/tensorflow_lite-2.4.0.0
VSBL_TENSORFLOW_LITE_VERSION = TENSORFLOW_LITE_2_4_0_0
endif
endif

