# Automatically generated file: do not edit

##########################
# IPNET_IPSECIKE_GDOI Section
##########################


ifdef _WRS_CONFIG_IPNET_IPSECIKE_GDOI
VSBL_IPNET_IPSECIKE_GDOI_SRC = 
VSBL_IPNET_IPSECIKE_GDOI_DEPEND = 

ifdef _WRS_CONFIG_IPNET_IPSECIKE_2_0_0_8_GDOI_2_0_0_8
VSBL_IPNET_IPSECIKE_GDOI_SRC += IPNET_IPSECIKE_GDOI
VSBL_IPNET_IPSECIKE_GDOI_DEPEND += IPNET_IPSECIKE_IKE
VSBL_IPNET_IPSECIKE_GDOI_DEPEND += SECURITY_MISC_SEC_CRYPTO
IPNET_IPSECIKE_GDOI_FASTBUILD = YES
IPNET_IPSECIKE_GDOI_FRIEND = IPNET_IPSECIKE_IKE IPNET_IPSECIKE
VSBL_IPNET_IPSECIKE_GDOI_PATH = $(WIND_BASE)/os/net/ipnet/ipsecike/gdoi
VSBL_IPNET_IPSECIKE_GDOI_VERSION = IPNET_IPSECIKE_2_0_0_8_GDOI_2_0_0_8
endif
endif

