# Automatically generated file: do not edit

##########################
# CRYPTOMISC_IPFREESCALE Section
##########################


ifdef _WRS_CONFIG_CRYPTOMISC_IPFREESCALE
VSBL_CRYPTOMISC_IPFREESCALE_SRC = 
VSBL_CRYPTOMISC_IPFREESCALE_DEPEND = 

ifdef _WRS_CONFIG_CRYPTOMISC_2_0_2_6_IPFREESCALE_2_0_2_6
VSBL_CRYPTOMISC_IPFREESCALE_SRC += CRYPTOMISC_IPFREESCALE
VSBL_CRYPTOMISC_IPFREESCALE_DEPEND += CRYPTOMISC_IPHWCRYPTO
CRYPTOMISC_IPFREESCALE_FASTBUILD = YES
VSBL_CRYPTOMISC_IPFREESCALE_PATH = $(WIND_BASE)/os/security/crypto_misc/ipfreescale
VSBL_CRYPTOMISC_IPFREESCALE_VERSION = CRYPTOMISC_2_0_2_6_IPFREESCALE_2_0_2_6
endif
endif

