# Automatically generated file: do not edit

##########################
# UTILS_UNIX Section
##########################


ifdef _WRS_CONFIG_UTILS_UNIX
VSBL_UTILS_UNIX_SRC = 
VSBL_UTILS_UNIX_DEPEND = 

ifdef _WRS_CONFIG_UTILS_2_0_8_0_UNIX_2_0_8_0
VSBL_UTILS_UNIX_SRC += UTILS_UNIX
VSBL_UTILS_UNIX_DEPEND += LIBC_STD
VSBL_UTILS_UNIX_DEPEND += SERVICE_SOCKET
VSBL_UTILS_UNIX_DEPEND += UTILS_SHELL
VSBL_UTILS_UNIX_DEPEND += CORE
VSBL_UTILS_UNIX_DEPEND += CORE
VSBL_UTILS_UNIX_DEPEND += CORE
UTILS_UNIX_FASTBUILD = YES
VSBL_UTILS_UNIX_PATH = $(WIND_BASE)/os/utils/unix
VSBL_UTILS_UNIX_VERSION = UTILS_2_0_8_0_UNIX_2_0_8_0
endif
endif

