# Automatically generated file: do not edit

##########################
# PYTHON Section
##########################


ifdef _WRS_CONFIG_PYTHON
VSBL_PYTHON_SRC = 
VSBL_PYTHON_DEPEND = 

ifdef _WRS_CONFIG_PYTHON_3_8_0_6
ifdef _WRS_CONFIG_PYTHON_CYTHON
VSBL_PYTHON_SRC += PYTHON_CYTHON
endif
ifdef _WRS_CONFIG_PYTHON_DATEUTIL
VSBL_PYTHON_SRC += PYTHON_DATEUTIL
endif
ifdef _WRS_CONFIG_PYTHON_NUMPY
VSBL_PYTHON_SRC += PYTHON_NUMPY
endif
ifdef _WRS_CONFIG_PYTHON_PANDAS
VSBL_PYTHON_SRC += PYTHON_PANDAS
endif
ifdef _WRS_CONFIG_PYTHON_PYTZ
VSBL_PYTHON_SRC += PYTHON_PYTZ
endif
ifdef _WRS_CONFIG_PYTHON_SIX
VSBL_PYTHON_SRC += PYTHON_SIX
endif
VSBL_PYTHON_SRC += PYTHON
VSBL_PYTHON_DEPEND += CORE_RTP
VSBL_PYTHON_DEPEND += EXPAT
VSBL_PYTHON_DEPEND += FS_UTIL
VSBL_PYTHON_DEPEND += FS_VRFS
VSBL_PYTHON_DEPEND += IPNET_USRSPACE
VSBL_PYTHON_DEPEND += USER_MANAGEMENT
VSBL_PYTHON_DEPEND += UTILS_DEPLOY
VSBL_PYTHON_DEPEND += UTILS_WRCC
PYTHON_FASTBUILD = YES
VSBL_PYTHON_PATH = $(WIND_BASE)/contrib/python-3.8.0
VSBL_PYTHON_VERSION = PYTHON_3_8_0_6
endif
endif

