# Automatically generated file: do not edit

##########################
# SECURITY_MISC Section
##########################


ifdef _WRS_CONFIG_SECURITY_MISC
VSBL_SECURITY_MISC_SRC = 
VSBL_SECURITY_MISC_DEPEND = 

ifdef _WRS_CONFIG_SECURITY_MISC_2_0_2_5
ifdef _WRS_CONFIG_SECURITY_MISC_SCEP
VSBL_SECURITY_MISC_SRC += SECURITY_MISC_SCEP
endif
ifdef _WRS_CONFIG_SECURITY_MISC_SEC_CRYPTO
VSBL_SECURITY_MISC_SRC += SECURITY_MISC_SEC_CRYPTO
endif
ifdef _WRS_CONFIG_SECURITY_MISC_SEC_HASH
VSBL_SECURITY_MISC_SRC += SECURITY_MISC_SEC_HASH
endif
VSBL_SECURITY_MISC_SRC += SECURITY_MISC
VSBL_SECURITY_MISC_DEPEND += CORE
VSBL_SECURITY_MISC_DEPEND += OPENSSL
SECURITY_MISC_FASTBUILD = YES
VSBL_SECURITY_MISC_PATH = $(WIND_BASE)/os/security/security_misc
VSBL_SECURITY_MISC_VERSION = SECURITY_MISC_2_0_2_5
endif
endif

