# Automatically generated file: do not edit

##########################
# WEBCLI_CLIDEMO Section
##########################


ifdef _WRS_CONFIG_WEBCLI_CLIDEMO
VSBL_WEBCLI_CLIDEMO_SRC = 
VSBL_WEBCLI_CLIDEMO_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_2_0_1_1_CLIDEMO_2_0_1_1
VSBL_WEBCLI_CLIDEMO_SRC += WEBCLI_CLIDEMO
VSBL_WEBCLI_CLIDEMO_DEPEND += UTILS_SHELL
VSBL_WEBCLI_CLIDEMO_DEPEND += WEBCLI_MIBWAY
WEBCLI_CLIDEMO_FASTBUILD = YES
VSBL_WEBCLI_CLIDEMO_PATH = $(WIND_BASE)/os/manage/webcli/clidemo
VSBL_WEBCLI_CLIDEMO_VERSION = WEBCLI_2_0_1_1_CLIDEMO_2_0_1_1
endif
endif

