# Automatically generated file: do not edit

##########################
# DISK_ENCRYPTION Section
##########################


ifdef _WRS_CONFIG_DISK_ENCRYPTION
VSBL_DISK_ENCRYPTION_SRC = 
VSBL_DISK_ENCRYPTION_DEPEND = 

ifdef _WRS_CONFIG_DISK_ENCRYPTION_2_0_1_2
VSBL_DISK_ENCRYPTION_SRC += DISK_ENCRYPTION
VSBL_DISK_ENCRYPTION_DEPEND += BDM
VSBL_DISK_ENCRYPTION_DEPEND += FS
VSBL_DISK_ENCRYPTION_DEPEND += SECURITY_MISC_SEC_CRYPTO
DISK_ENCRYPTION_FASTBUILD = YES
DISK_ENCRYPTION_FRIEND = FS
VSBL_DISK_ENCRYPTION_PATH = $(WIND_BASE)/os/security/disk_encryption
VSBL_DISK_ENCRYPTION_VERSION = DISK_ENCRYPTION_2_0_1_2
endif
endif

