# Automatically generated file: do not edit

##########################
# USER_MANAGEMENT Section
##########################


ifdef _WRS_CONFIG_USER_MANAGEMENT
VSBL_USER_MANAGEMENT_SRC = 
VSBL_USER_MANAGEMENT_DEPEND = 

ifdef _WRS_CONFIG_USER_MANAGEMENT_2_0_1_7
ifdef _WRS_CONFIG_USER_MANAGEMENT_LDAP
VSBL_USER_MANAGEMENT_SRC += USER_MANAGEMENT_LDAP
endif
ifdef _WRS_CONFIG_USER_MANAGEMENT_POLICY
VSBL_USER_MANAGEMENT_SRC += USER_MANAGEMENT_POLICY
endif
ifdef _WRS_CONFIG_USER_MANAGEMENT_USER_PRIVILEGES
VSBL_USER_MANAGEMENT_SRC += USER_MANAGEMENT_USER_PRIVILEGES
endif
VSBL_USER_MANAGEMENT_SRC += USER_MANAGEMENT
VSBL_USER_MANAGEMENT_DEPEND += SECURITY_MISC_SEC_HASH
VSBL_USER_MANAGEMENT_DEPEND += UTILS_SHELL
VSBL_USER_MANAGEMENT_DEPEND += OPENSSL
USER_MANAGEMENT_FASTBUILD = YES
VSBL_USER_MANAGEMENT_PATH = $(WIND_BASE)/os/security/user_management
VSBL_USER_MANAGEMENT_VERSION = USER_MANAGEMENT_2_0_1_7
endif
endif

