# Automatically generated file: do not edit

##########################
# RTTOOLS Section
##########################


ifdef _WRS_CONFIG_RTTOOLS
VSBL_RTTOOLS_SRC = 
VSBL_RTTOOLS_DEPEND = 

ifdef _WRS_CONFIG_RTTOOLS_2_0_1_7
ifdef _WRS_CONFIG_RTTOOLS_DEBUG_AGENT
VSBL_RTTOOLS_SRC += RTTOOLS_DEBUG_AGENT
endif
ifdef _WRS_CONFIG_RTTOOLS_RUNTIME_ANALYSIS
VSBL_RTTOOLS_SRC += RTTOOLS_RUNTIME_ANALYSIS
endif
ifdef _WRS_CONFIG_RTTOOLS_STOP_MODE_DEBUG_AGENT
VSBL_RTTOOLS_SRC += RTTOOLS_STOP_MODE_DEBUG_AGENT
endif
ifdef _WRS_CONFIG_RTTOOLS_SYSTEMVIEWER_AGENT
VSBL_RTTOOLS_SRC += RTTOOLS_SYSTEMVIEWER_AGENT
endif
VSBL_RTTOOLS_SRC += RTTOOLS
RTTOOLS_FASTBUILD = YES
VSBL_RTTOOLS_PATH = $(WIND_BASE)/os/debug_analysis/rttools
VSBL_RTTOOLS_VERSION = RTTOOLS_2_0_1_7
endif
endif

