# Automatically generated file: do not edit

##########################
# PYTHON_PANDAS Section
##########################


ifdef _WRS_CONFIG_PYTHON_PANDAS
VSBL_PYTHON_PANDAS_SRC = 
VSBL_PYTHON_PANDAS_DEPEND = 

ifdef _WRS_CONFIG_PYTHON_3_8_0_6_PANDAS_1_0_3_0
VSBL_PYTHON_PANDAS_SRC += PYTHON_PANDAS
VSBL_PYTHON_PANDAS_DEPEND += BZIP2
VSBL_PYTHON_PANDAS_DEPEND += CORE_RTP
VSBL_PYTHON_PANDAS_DEPEND += LZMA
VSBL_PYTHON_PANDAS_DEPEND += PYTHON_CYTHON
VSBL_PYTHON_PANDAS_DEPEND += PYTHON_DATEUTIL
VSBL_PYTHON_PANDAS_DEPEND += PYTHON_NUMPY
VSBL_PYTHON_PANDAS_DEPEND += PYTHON_PYTZ
VSBL_PYTHON_PANDAS_DEPEND += SQLITE
PYTHON_PANDAS_FASTBUILD = YES
VSBL_PYTHON_PANDAS_PATH = $(WIND_BASE)/contrib/python-3.8.0/pandas
VSBL_PYTHON_PANDAS_VERSION = PYTHON_3_8_0_6_PANDAS_1_0_3_0
endif
endif

