# Automatically generated file: do not edit

##########################
# CONTAINER_EXAMPLES Section
##########################


ifdef _WRS_CONFIG_CONTAINER_EXAMPLES
VSBL_CONTAINER_EXAMPLES_SRC = 
VSBL_CONTAINER_EXAMPLES_DEPEND = 

ifdef _WRS_CONFIG_CONTAINER_1_0_1_0_EXAMPLES_1_0_0_0
VSBL_CONTAINER_EXAMPLES_SRC += CONTAINER_EXAMPLES
VSBL_CONTAINER_EXAMPLES_DEPEND += CONTAINER_RUNTIME
CONTAINER_EXAMPLES_FASTBUILD = YES
VSBL_CONTAINER_EXAMPLES_PATH = $(WIND_BASE)/os/container/examples
VSBL_CONTAINER_EXAMPLES_VERSION = CONTAINER_1_0_1_0_EXAMPLES_1_0_0_0
endif
endif

