# Automatically generated file: do not edit

##########################
# PYTHON_NUMPY Section
##########################


ifdef _WRS_CONFIG_PYTHON_NUMPY
VSBL_PYTHON_NUMPY_SRC = 
VSBL_PYTHON_NUMPY_DEPEND = 

ifdef _WRS_CONFIG_PYTHON_3_8_0_6_NUMPY_1_18_1_1
VSBL_PYTHON_NUMPY_SRC += PYTHON_NUMPY
VSBL_PYTHON_NUMPY_DEPEND += CORE_RTP
VSBL_PYTHON_NUMPY_DEPEND += LIBFFI
VSBL_PYTHON_NUMPY_DEPEND += PYTHON
PYTHON_NUMPY_FASTBUILD = YES
VSBL_PYTHON_NUMPY_PATH = $(WIND_BASE)/contrib/python-3.8.0/numpy
VSBL_PYTHON_NUMPY_VERSION = PYTHON_3_8_0_6_NUMPY_1_18_1_1
endif
endif

