# Automatically generated file: do not edit

##########################
# RTNET Section
##########################


ifdef _WRS_CONFIG_RTNET
VSBL_RTNET_SRC = 
VSBL_RTNET_DEPEND = 

ifdef _WRS_CONFIG_RTNET_2_0_2_6
VSBL_RTNET_SRC += RTNET
VSBL_RTNET_DEPEND += END
VSBL_RTNET_DEPEND += JANSSON
VSBL_RTNET_DEPEND += SERVICE_JOBQUEUE
VSBL_RTNET_DEPEND += VXBUS
VSBL_RTNET_DEPEND += NET_BASE
VSBL_RTNET_DEPEND += SERVICE_SOCKET
VSBL_RTNET_DEPEND += SERVICE_SOCKET
VSBL_RTNET_DEPEND += CORE
RTNET_FASTBUILD = YES
VSBL_RTNET_PATH = $(WIND_BASE)/os/net/rtnet
VSBL_RTNET_VERSION = RTNET_2_0_2_6
endif
endif

