# Automatically generated file: do not edit

##########################
# WEBCLI Section
##########################


ifdef _WRS_CONFIG_WEBCLI
VSBL_WEBCLI_SRC = 
VSBL_WEBCLI_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_2_0_1_1
ifdef _WRS_CONFIG_WEBCLI_CLIDEMO
VSBL_WEBCLI_SRC += WEBCLI_CLIDEMO
endif
ifdef _WRS_CONFIG_WEBCLI_HTTP
VSBL_WEBCLI_SRC += WEBCLI_HTTP
endif
ifdef _WRS_CONFIG_WEBCLI_MIBWAY
VSBL_WEBCLI_SRC += WEBCLI_MIBWAY
endif
ifdef _WRS_CONFIG_WEBCLI_WEBCLIDEMO
VSBL_WEBCLI_SRC += WEBCLI_WEBCLIDEMO
endif
ifdef _WRS_CONFIG_WEBCLI_WEBDEMO
VSBL_WEBCLI_SRC += WEBCLI_WEBDEMO
endif
VSBL_WEBCLI_SRC += WEBCLI
VSBL_WEBCLI_DEPEND += IPNET_COREIP
VSBL_WEBCLI_DEPEND += LIBCURL
VSBL_WEBCLI_DEPEND += LIBC_STD
VSBL_WEBCLI_DEPEND += OPENSSL
WEBCLI_FASTBUILD = YES
VSBL_WEBCLI_PATH = $(WIND_BASE)/os/manage/webcli
VSBL_WEBCLI_VERSION = WEBCLI_2_0_1_1
endif
endif

