# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_SAFE_SOCKET Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_SOCKET
VSBL_GUEST_SUPPORT_VX7_SAFE_SOCKET_SRC = 
VSBL_GUEST_SUPPORT_VX7_SAFE_SOCKET_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_1_0_3_6_SAFEIPC_1_0_3_6_SOCKET_1_0_3_6
VSBL_GUEST_SUPPORT_VX7_SAFE_SOCKET_SRC += GUEST_SUPPORT_VX7_SAFE_SOCKET
VSBL_GUEST_SUPPORT_VX7_SAFE_SOCKET_DEPEND += SERVICE_JOBQUEUE
GUEST_SUPPORT_VX7_SAFE_SOCKET_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_SAFE_SOCKET_PATH = $(WIND_BASE)/os/hv/guest_support_vx7_safe/safeipc/socket
VSBL_GUEST_SUPPORT_VX7_SAFE_SOCKET_VERSION = GUEST_SUPPORT_VX7_SAFE_1_0_3_6_SAFEIPC_1_0_3_6_SOCKET_1_0_3_6
endif
endif

