# Automatically generated file: do not edit

##########################
# GSOAP Section
##########################


ifdef _WRS_CONFIG_GSOAP
VSBL_GSOAP_SRC = 
VSBL_GSOAP_DEPEND = 

ifdef _WRS_CONFIG_GSOAP_2_8_82_4
VSBL_GSOAP_SRC += GSOAP
VSBL_GSOAP_DEPEND += IPNET_COREIP
VSBL_GSOAP_DEPEND += SECURITY_MISC_SEC_CRYPTO
VSBL_GSOAP_DEPEND += ZLIB
VSBL_GSOAP_DEPEND += SERVICE_SOCKET
VSBL_GSOAP_DEPEND += OPENSSL
GSOAP_FASTBUILD = YES
VSBL_GSOAP_PATH = $(WIND_BASE)/contrib/gsoap-2.8.82
VSBL_GSOAP_VERSION = GSOAP_2_8_82_4
endif
endif

