# Automatically generated file: do not edit

##########################
# USER_MANAGEMENT_USER_PRIVILEGES Section
##########################


ifdef _WRS_CONFIG_USER_MANAGEMENT_USER_PRIVILEGES
VSBL_USER_MANAGEMENT_USER_PRIVILEGES_SRC = 
VSBL_USER_MANAGEMENT_USER_PRIVILEGES_DEPEND = 

ifdef _WRS_CONFIG_USER_MANAGEMENT_2_0_1_7_USER_PRIVILEGES_2_0_1_7
VSBL_USER_MANAGEMENT_USER_PRIVILEGES_SRC += USER_MANAGEMENT_USER_PRIVILEGES
VSBL_USER_MANAGEMENT_USER_PRIVILEGES_DEPEND += UTILS_SHELL
USER_MANAGEMENT_USER_PRIVILEGES_FASTBUILD = YES
VSBL_USER_MANAGEMENT_USER_PRIVILEGES_PATH = $(WIND_BASE)/os/security/user_management/user_privileges
VSBL_USER_MANAGEMENT_USER_PRIVILEGES_VERSION = USER_MANAGEMENT_2_0_1_7_USER_PRIVILEGES_2_0_1_7
endif
endif

