# Automatically generated file: do not edit

##########################
# DEBUG_SYSTEMVIEWER Section
##########################


ifdef _WRS_CONFIG_DEBUG_SYSTEMVIEWER
VSBL_DEBUG_SYSTEMVIEWER_SRC = 
VSBL_DEBUG_SYSTEMVIEWER_DEPEND = 

ifdef _WRS_CONFIG_DEBUG_2_0_3_3_SYSTEMVIEWER_2_0_3_3
VSBL_DEBUG_SYSTEMVIEWER_SRC += DEBUG_SYSTEMVIEWER
VSBL_DEBUG_SYSTEMVIEWER_DEPEND += UTILS_RBUFF
DEBUG_SYSTEMVIEWER_FASTBUILD = YES
VSBL_DEBUG_SYSTEMVIEWER_PATH = $(WIND_BASE)/os/debug_analysis/debug/event
VSBL_DEBUG_SYSTEMVIEWER_VERSION = DEBUG_2_0_3_3_SYSTEMVIEWER_2_0_3_3
endif
endif

