# Automatically generated file: do not edit

##########################
# WEBCLI_WEBDEMO Section
##########################


ifdef _WRS_CONFIG_WEBCLI_WEBDEMO
VSBL_WEBCLI_WEBDEMO_SRC = 
VSBL_WEBCLI_WEBDEMO_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_2_0_1_1_WEBDEMO_2_0_1_1
VSBL_WEBCLI_WEBDEMO_SRC += WEBCLI_WEBDEMO
VSBL_WEBCLI_WEBDEMO_DEPEND += FS_DOSFS
VSBL_WEBCLI_WEBDEMO_DEPEND += LIBCURL
VSBL_WEBCLI_WEBDEMO_DEPEND += SECURITY_MISC_SEC_CRYPTO
VSBL_WEBCLI_WEBDEMO_DEPEND += WEBCLI_HTTP
VSBL_WEBCLI_WEBDEMO_DEPEND += WEBCLI_MIBWAY
WEBCLI_WEBDEMO_FASTBUILD = YES
VSBL_WEBCLI_WEBDEMO_PATH = $(WIND_BASE)/os/manage/webcli/webdemo
VSBL_WEBCLI_WEBDEMO_VERSION = WEBCLI_2_0_1_1_WEBDEMO_2_0_1_1
endif
endif

