# Automatically generated file: do not edit

##########################
# RTTOOLS_STOP_MODE_DEBUG_AGENT Section
##########################


ifdef _WRS_CONFIG_RTTOOLS_STOP_MODE_DEBUG_AGENT
VSBL_RTTOOLS_STOP_MODE_DEBUG_AGENT_SRC = 
VSBL_RTTOOLS_STOP_MODE_DEBUG_AGENT_DEPEND = 

ifdef _WRS_CONFIG_RTTOOLS_2_0_1_7_STOP_MODE_DEBUG_AGENT_2_0_1_7
VSBL_RTTOOLS_STOP_MODE_DEBUG_AGENT_SRC += RTTOOLS_STOP_MODE_DEBUG_AGENT
VSBL_RTTOOLS_STOP_MODE_DEBUG_AGENT_DEPEND += DEBUG
RTTOOLS_STOP_MODE_DEBUG_AGENT_FASTBUILD = YES
VSBL_RTTOOLS_STOP_MODE_DEBUG_AGENT_PATH = $(WIND_BASE)/os/debug_analysis/rttools/stopmode
VSBL_RTTOOLS_STOP_MODE_DEBUG_AGENT_VERSION = RTTOOLS_2_0_1_7_STOP_MODE_DEBUG_AGENT_2_0_1_7
endif
endif

