# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_HVIF Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_HVIF
VSBL_GUEST_SUPPORT_VX7_HVIF_SRC = 
VSBL_GUEST_SUPPORT_VX7_HVIF_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_1_0_1_3_HVIF_1_0_1_3
VSBL_GUEST_SUPPORT_VX7_HVIF_SRC += GUEST_SUPPORT_VX7_HVIF
GUEST_SUPPORT_VX7_HVIF_FASTBUILD = YES
GUEST_SUPPORT_VX7_HVIF_FRIEND = GUEST_SUPPORT_VX7_SAFE_HVIF
VSBL_GUEST_SUPPORT_VX7_HVIF_PATH = $(WIND_BASE)/os/hv/guest_support_vx7/hvif
VSBL_GUEST_SUPPORT_VX7_HVIF_VERSION = GUEST_SUPPORT_VX7_1_0_1_3_HVIF_1_0_1_3
endif
endif

