# Automatically generated file: do not edit

##########################
# SERVICE_EPOLL Section
##########################


ifdef _WRS_CONFIG_SERVICE_EPOLL
VSBL_SERVICE_EPOLL_SRC = 
VSBL_SERVICE_EPOLL_DEPEND = 

ifdef _WRS_CONFIG_SERVICE_4_0_1_1_EPOLL_4_0_1_1
VSBL_SERVICE_EPOLL_SRC += SERVICE_EPOLL
SERVICE_EPOLL_FASTBUILD = YES
VSBL_SERVICE_EPOLL_PATH = $(WIND_BASE)/os/service/epoll
VSBL_SERVICE_EPOLL_VERSION = SERVICE_4_0_1_1_EPOLL_4_0_1_1
endif
endif

