# Automatically generated file: do not edit

##########################
# CRYPTOMISC_IAF Section
##########################


ifdef _WRS_CONFIG_CRYPTOMISC_IAF
VSBL_CRYPTOMISC_IAF_SRC = 
VSBL_CRYPTOMISC_IAF_DEPEND = 

ifdef _WRS_CONFIG_CRYPTOMISC_2_0_2_6_IAF_2_0_2_6
VSBL_CRYPTOMISC_IAF_SRC += CRYPTOMISC_IAF
VSBL_CRYPTOMISC_IAF_DEPEND += SECURITY_MISC_SEC_CRYPTO
CRYPTOMISC_IAF_FASTBUILD = YES
VSBL_CRYPTOMISC_IAF_PATH = $(WIND_BASE)/os/security/crypto_misc/iaf
VSBL_CRYPTOMISC_IAF_VERSION = CRYPTOMISC_2_0_2_6_IAF_2_0_2_6
endif
endif

