# Automatically generated file: do not edit

##########################
# SECURITY_EVENT Section
##########################


ifdef _WRS_CONFIG_SECURITY_EVENT
VSBL_SECURITY_EVENT_SRC = 
VSBL_SECURITY_EVENT_DEPEND = 

ifdef _WRS_CONFIG_SECURITY_EVENT_3_0_0_0
VSBL_SECURITY_EVENT_SRC += SECURITY_EVENT
VSBL_SECURITY_EVENT_DEPEND += CORE
SECURITY_EVENT_FASTBUILD = YES
VSBL_SECURITY_EVENT_PATH = $(WIND_BASE)/os/security/security_event
VSBL_SECURITY_EVENT_VERSION = SECURITY_EVENT_3_0_0_0
endif
endif

