# Automatically generated file: do not edit

##########################
# SERVICE_RPC Section
##########################


ifdef _WRS_CONFIG_SERVICE_RPC
VSBL_SERVICE_RPC_SRC = 
VSBL_SERVICE_RPC_DEPEND = 

ifdef _WRS_CONFIG_SERVICE_4_0_1_1_RPC_4_0_1_1
VSBL_SERVICE_RPC_SRC += SERVICE_RPC
VSBL_SERVICE_RPC_DEPEND += IPNET_COREIP
VSBL_SERVICE_RPC_DEPEND += SERVICE_SOCKET
SERVICE_RPC_FASTBUILD = YES
VSBL_SERVICE_RPC_PATH = $(WIND_BASE)/os/service/rpc
VSBL_SERVICE_RPC_VERSION = SERVICE_4_0_1_1_RPC_4_0_1_1
endif
endif

