# Automatically generated file: do not edit

##########################
# LIBARCHIVE Section
##########################


ifdef _WRS_CONFIG_LIBARCHIVE
VSBL_LIBARCHIVE_SRC = 
VSBL_LIBARCHIVE_DEPEND = 

ifdef _WRS_CONFIG_LIBARCHIVE_3_4_2_3
VSBL_LIBARCHIVE_SRC += LIBARCHIVE
VSBL_LIBARCHIVE_DEPEND += UTILS_UNIX
VSBL_LIBARCHIVE_DEPEND += ZLIB
VSBL_LIBARCHIVE_DEPEND += CORE
VSBL_LIBARCHIVE_DEPEND += OPENSSL
LIBARCHIVE_FASTBUILD = YES
LIBARCHIVE_SUBSCRIBE = UTILS_UNIX
VSBL_LIBARCHIVE_PATH = $(WIND_BASE)/contrib/libarchive-3.4.2
VSBL_LIBARCHIVE_VERSION = LIBARCHIVE_3_4_2_3
endif
endif

