# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_SAFE_HVIF Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_HVIF
VSBL_GUEST_SUPPORT_VX7_SAFE_HVIF_SRC = 
VSBL_GUEST_SUPPORT_VX7_SAFE_HVIF_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_1_0_3_6_HVIF_1_0_3_6
VSBL_GUEST_SUPPORT_VX7_SAFE_HVIF_SRC += GUEST_SUPPORT_VX7_SAFE_HVIF
VSBL_GUEST_SUPPORT_VX7_SAFE_HVIF_DEPEND += GUEST_SUPPORT_VX7_HVIF
GUEST_SUPPORT_VX7_SAFE_HVIF_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_SAFE_HVIF_PATH = $(WIND_BASE)/os/hv/guest_support_vx7_safe/hvif
VSBL_GUEST_SUPPORT_VX7_SAFE_HVIF_VERSION = GUEST_SUPPORT_VX7_SAFE_1_0_3_6_HVIF_1_0_3_6
endif
endif

