# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_VNIC Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_VNIC
VSBL_GUEST_SUPPORT_VX7_VNIC_SRC = 
VSBL_GUEST_SUPPORT_VX7_VNIC_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_1_0_1_3_VNIC_1_0_1_3
VSBL_GUEST_SUPPORT_VX7_VNIC_SRC += GUEST_SUPPORT_VX7_VNIC
VSBL_GUEST_SUPPORT_VX7_VNIC_DEPEND += GUEST_SUPPORT_VX7_HVIF
GUEST_SUPPORT_VX7_VNIC_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_VNIC_PATH = $(WIND_BASE)/os/hv/guest_support_vx7/vnic
VSBL_GUEST_SUPPORT_VX7_VNIC_VERSION = GUEST_SUPPORT_VX7_1_0_1_3_VNIC_1_0_1_3
endif
endif

