# Automatically generated file: do not edit

##########################
# SERVICE_SOCKET Section
##########################


ifdef _WRS_CONFIG_SERVICE_SOCKET
VSBL_SERVICE_SOCKET_SRC = 
VSBL_SERVICE_SOCKET_DEPEND = 

ifdef _WRS_CONFIG_SERVICE_4_0_1_1_SOCKET_4_0_1_1
VSBL_SERVICE_SOCKET_SRC += SERVICE_SOCKET
VSBL_SERVICE_SOCKET_DEPEND += NET_BASE
VSBL_SERVICE_SOCKET_DEPEND += CORE
VSBL_SERVICE_SOCKET_DEPEND += CORE
SERVICE_SOCKET_FASTBUILD = YES
VSBL_SERVICE_SOCKET_PATH = $(WIND_BASE)/os/service/socket
VSBL_SERVICE_SOCKET_VERSION = SERVICE_4_0_1_1_SOCKET_4_0_1_1
endif
endif

