# Automatically generated file: do not edit

##########################
# CONTAINER_RUNTIME Section
##########################


ifdef _WRS_CONFIG_CONTAINER_RUNTIME
VSBL_CONTAINER_RUNTIME_SRC = 
VSBL_CONTAINER_RUNTIME_DEPEND = 

ifdef _WRS_CONFIG_CONTAINER_1_0_1_0_RUNTIME_1_0_1_0
VSBL_CONTAINER_RUNTIME_SRC += CONTAINER_RUNTIME
VSBL_CONTAINER_RUNTIME_DEPEND += CJSON
VSBL_CONTAINER_RUNTIME_DEPEND += CORE_RTP
VSBL_CONTAINER_RUNTIME_DEPEND += PARG
VSBL_CONTAINER_RUNTIME_DEPEND += UZLIB
CONTAINER_RUNTIME_FASTBUILD = YES
VSBL_CONTAINER_RUNTIME_PATH = $(WIND_BASE)/os/container/runtime
VSBL_CONTAINER_RUNTIME_VERSION = CONTAINER_1_0_1_0_RUNTIME_1_0_1_0
endif
endif

