# Automatically generated file: do not edit

##########################
# PYTHON_CYTHON Section
##########################


ifdef _WRS_CONFIG_PYTHON_CYTHON
VSBL_PYTHON_CYTHON_SRC = 
VSBL_PYTHON_CYTHON_DEPEND = 

ifdef _WRS_CONFIG_PYTHON_3_8_0_6_CYTHON_0_29_14_0
VSBL_PYTHON_CYTHON_SRC += PYTHON_CYTHON
VSBL_PYTHON_CYTHON_DEPEND += CORE_RTP
VSBL_PYTHON_CYTHON_DEPEND += PYTHON
PYTHON_CYTHON_FASTBUILD = YES
VSBL_PYTHON_CYTHON_PATH = $(WIND_BASE)/contrib/python-3.8.0/cython
VSBL_PYTHON_CYTHON_VERSION = PYTHON_3_8_0_6_CYTHON_0_29_14_0
endif
endif

