# Automatically generated file: do not edit

##########################
# GUEST_SUPPORT_VX7_SAFE_SAFEIPC Section
##########################


ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_SAFEIPC
VSBL_GUEST_SUPPORT_VX7_SAFE_SAFEIPC_SRC = 
VSBL_GUEST_SUPPORT_VX7_SAFE_SAFEIPC_DEPEND = 

ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_1_0_3_6_SAFEIPC_1_0_3_6
ifdef _WRS_CONFIG_GUEST_SUPPORT_VX7_SAFE_SOCKET
VSBL_GUEST_SUPPORT_VX7_SAFE_SAFEIPC_SRC += GUEST_SUPPORT_VX7_SAFE_SOCKET
endif
VSBL_GUEST_SUPPORT_VX7_SAFE_SAFEIPC_SRC += GUEST_SUPPORT_VX7_SAFE_SAFEIPC
GUEST_SUPPORT_VX7_SAFE_SAFEIPC_FASTBUILD = YES
VSBL_GUEST_SUPPORT_VX7_SAFE_SAFEIPC_PATH = $(WIND_BASE)/os/hv/guest_support_vx7_safe/safeipc
VSBL_GUEST_SUPPORT_VX7_SAFE_SAFEIPC_VERSION = GUEST_SUPPORT_VX7_SAFE_1_0_3_6_SAFEIPC_1_0_3_6
endif
endif

