# Automatically generated file: do not edit

##########################
# SECURITY_MISC_SCEP Section
##########################


ifdef _WRS_CONFIG_SECURITY_MISC_SCEP
VSBL_SECURITY_MISC_SCEP_SRC = 
VSBL_SECURITY_MISC_SCEP_DEPEND = 

ifdef _WRS_CONFIG_SECURITY_MISC_2_0_2_5_SCEP_2_0_2_5
VSBL_SECURITY_MISC_SCEP_SRC += SECURITY_MISC_SCEP
VSBL_SECURITY_MISC_SCEP_DEPEND += IPNET_COREIP
VSBL_SECURITY_MISC_SCEP_DEPEND += SECURITY_MISC_SEC_CRYPTO
SECURITY_MISC_SCEP_FASTBUILD = YES
VSBL_SECURITY_MISC_SCEP_PATH = $(WIND_BASE)/os/security/security_misc/scep
VSBL_SECURITY_MISC_SCEP_VERSION = SECURITY_MISC_2_0_2_5_SCEP_2_0_2_5
endif
endif

