# Automatically generated file: do not edit

##########################
# CONTAINER Section
##########################


ifdef _WRS_CONFIG_CONTAINER
VSBL_CONTAINER_SRC = 
VSBL_CONTAINER_DEPEND = 

ifdef _WRS_CONFIG_CONTAINER_1_0_1_0
ifdef _WRS_CONFIG_CONTAINER_EXAMPLES
VSBL_CONTAINER_SRC += CONTAINER_EXAMPLES
endif
ifdef _WRS_CONFIG_CONTAINER_MANAGER
VSBL_CONTAINER_SRC += CONTAINER_MANAGER
endif
ifdef _WRS_CONFIG_CONTAINER_RUNTIME
VSBL_CONTAINER_SRC += CONTAINER_RUNTIME
endif
VSBL_CONTAINER_SRC += CONTAINER
CONTAINER_FASTBUILD = YES
VSBL_CONTAINER_PATH = $(WIND_BASE)/os/container
VSBL_CONTAINER_VERSION = CONTAINER_1_0_1_0
endif
endif

