# Automatically generated file: do not edit

##########################
# XLNX_ZYNQ Section
##########################


ifdef _WRS_CONFIG_XLNX_ZYNQ
VSBL_XLNX_ZYNQ_SRC = 
VSBL_XLNX_ZYNQ_DEPEND = 

ifdef _WRS_CONFIG_XLNX_ZYNQ_2_0_6_1
VSBL_XLNX_ZYNQ_SRC += XLNX_ZYNQ
VSBL_XLNX_ZYNQ_DEPEND += FDT
VSBL_XLNX_ZYNQ_DEPEND += PSCI
VSBL_XLNX_ZYNQ_DEPEND += UTILS
VSBL_XLNX_ZYNQ_DEPEND += VXBUS
VSBL_XLNX_ZYNQ_DEPEND += XLNX_COMMON
VSBL_XLNX_ZYNQ_DEPEND += CORE
VSBL_XLNX_ZYNQ_DEPEND += ARM
XLNX_ZYNQ_FASTBUILD = YES
VSBL_XLNX_ZYNQ_PATH = $(WIND_BASE)/os/psl/xilinx/xlnx_zynq
VSBL_XLNX_ZYNQ_VERSION = XLNX_ZYNQ_2_0_6_1
endif
endif

