# Automatically generated file: do not edit

##########################
# SIFIVE_RISCV Section
##########################


ifdef _WRS_CONFIG_SIFIVE_RISCV
VSBL_SIFIVE_RISCV_SRC = 
VSBL_SIFIVE_RISCV_DEPEND = 

ifdef _WRS_CONFIG_SIFIVE_RISCV_1_0_0_2
VSBL_SIFIVE_RISCV_SRC += SIFIVE_RISCV
VSBL_SIFIVE_RISCV_DEPEND += FDT
VSBL_SIFIVE_RISCV_DEPEND += UTILS
VSBL_SIFIVE_RISCV_DEPEND += VXBUS
SIFIVE_RISCV_FASTBUILD = YES
VSBL_SIFIVE_RISCV_PATH = $(WIND_BASE)/os/psl/sifive/sifive_riscv
VSBL_SIFIVE_RISCV_VERSION = SIFIVE_RISCV_1_0_0_2
endif
endif

